//! Namespace `NvidiaChassis`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_oem_nvidia_baseboard`.

const std = @import("std");

const core = @import("redfish_core");

pub const NvidiaCbcChassis = struct {
    /// Indicates the revision of the cable cartridge backplane FRU data information.
    ///
    /// This property shall indicate the revision of the cable cartridge backplane FRU data information.
    RevisionId: ?i64 = null,
    /// Indicates the chassis physical slot Number of the compute tray.
    ///
    /// This property shall indicate the chassis physical slot Number of the compute tray.
    ChassisPhysicalSlotNumber: ?i64 = null,
    /// Indicates the compute tray index within the chassis.
    ///
    /// This property shall indicate the compute tray index within the chassis.
    ComputeTrayIndex: ?i64 = null,
    /// Indicates the topology of the chassis.
    ///
    /// This property shall indicate the topology of the chassis.
    TopologyId: ?i64 = null,
};

test {
    std.testing.refAllDecls(@This());
}
