//! Liteon OEM extensions
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_oem_liteon`.

const std = @import("std");

pub const core = @import("redfish_core");

pub const liteon_power_supply = @import("liteon_power_supply.zig");
pub const liteon_power_supply_collection = @import("liteon_power_supply_collection.zig");

test {
    std.testing.refAllDecls(@This());
}
