//! The curated payload corpus, and where each file came from.
//!
//! DO NOT EDIT BY HAND. See `tests/README.md` for the curation rule and the
//! script that produced this.

pub const Case = struct {
    /// Module of `redfish_schema_std` declaring the type.
    module: []const u8,
    /// The type the payload must deserialize into.
    type_name: []const u8,
    /// Path within DMTF's `mockups/` directory, for provenance.
    source: []const u8,
    text: []const u8,
};

pub const cases = [_]Case{
    .{
        .module = "switch",
        .type_name = "Switch",
        .source = "public-cxl-multiswitch/Fabrics/CXL/Switches/CXL1/index.json",
        .text = @embedFile("payloads/switch.Switch.json"),
    },
    .{
        .module = "acceleration_function_collection",
        .type_name = "AccelerationFunctionCollection",
        .source = "public-rackmount1/Systems/437XR1138R2/Processors/FPGA1/AccelerationFunctions/index.json",
        .text = @embedFile("payloads/acceleration_function_collection.AccelerationFunctionCollection.json"),
    },
    .{
        .module = "acceleration_function",
        .type_name = "AccelerationFunction",
        .source = "public-rackmount1/Systems/437XR1138R2/Processors/FPGA1/AccelerationFunctions/Compression/index.json",
        .text = @embedFile("payloads/acceleration_function.AccelerationFunction.json"),
    },
    .{
        .module = "account_service",
        .type_name = "AccountService",
        .source = "public-rackmount1/AccountService/index.json",
        .text = @embedFile("payloads/account_service.AccountService.json"),
    },
    .{
        .module = "action_info",
        .type_name = "ActionInfo",
        .source = "public-rackmount1/CertificateService/GenerateCSRActionInfo/index.json",
        .text = @embedFile("payloads/action_info.ActionInfo.json"),
    },
    .{
        .module = "address_pool_collection",
        .type_name = "AddressPoolCollection",
        .source = "public-smartnic/Fabrics/Ethernet/AddressPools/index.json",
        .text = @embedFile("payloads/address_pool_collection.AddressPoolCollection.json"),
    },
    .{
        .module = "address_pool",
        .type_name = "AddressPool",
        .source = "public-smartnic/Fabrics/Ethernet/AddressPools/AddressPool1/index.json",
        .text = @embedFile("payloads/address_pool.AddressPool.json"),
    },
    .{
        .module = "aggregate",
        .type_name = "Aggregate",
        .source = "DSP2046-examples/Aggregate-v1-example.json",
        .text = @embedFile("payloads/aggregate.Aggregate.json"),
    },
    .{
        .module = "aggregation_service",
        .type_name = "AggregationService",
        .source = "DSP2046-examples/AggregationService-v1-example.json",
        .text = @embedFile("payloads/aggregation_service.AggregationService.json"),
    },
    .{
        .module = "aggregation_source",
        .type_name = "AggregationSource",
        .source = "DSP2046-examples/AggregationSource-v1-example.json",
        .text = @embedFile("payloads/aggregation_source.AggregationSource.json"),
    },
    .{
        .module = "allow_deny_collection",
        .type_name = "AllowDenyCollection",
        .source = "public-smartnic/Chassis/Card1/NetworkAdapters/Slot1/NetworkDeviceFunctions/SC2KP1F0/AllowDeny/index.json",
        .text = @embedFile("payloads/allow_deny_collection.AllowDenyCollection.json"),
    },
    .{
        .module = "allow_deny",
        .type_name = "AllowDeny",
        .source = "public-smartnic/Chassis/Card1/NetworkAdapters/Slot1/NetworkDeviceFunctions/SC2KP1F0/AllowDeny/Rule2/index.json",
        .text = @embedFile("payloads/allow_deny.AllowDeny.json"),
    },
    .{
        .module = "application_collection",
        .type_name = "ApplicationCollection",
        .source = "public-applications/Systems/VM1/OperatingSystem/Applications/index.json",
        .text = @embedFile("payloads/application_collection.ApplicationCollection.json"),
    },
    .{
        .module = "application",
        .type_name = "Application",
        .source = "public-applications/Systems/VM1/OperatingSystem/Applications/Logger/index.json",
        .text = @embedFile("payloads/application.Application.json"),
    },
    .{
        .module = "assembly",
        .type_name = "Assembly",
        .source = "public-telemetry/Chassis/1/Assembly/index.json",
        .text = @embedFile("payloads/assembly.Assembly.json"),
    },
    .{
        .module = "attribute_registry",
        .type_name = "AttributeRegistry",
        .source = "DSP2046-examples/AttributeRegistry-v1-example.json",
        .text = @embedFile("payloads/attribute_registry.AttributeRegistry.json"),
    },
    .{
        .module = "automation_instrumentation",
        .type_name = "AutomationInstrumentation",
        .source = "public-iiot/AutomationNodes/YAxisMover/AutomationInstrumentation/index.json",
        .text = @embedFile("payloads/automation_instrumentation.AutomationInstrumentation.json"),
    },
    .{
        .module = "automation_node_collection",
        .type_name = "AutomationNodeCollection",
        .source = "public-iiot/AutomationNodes/index.json",
        .text = @embedFile("payloads/automation_node_collection.AutomationNodeCollection.json"),
    },
    .{
        .module = "automation_node",
        .type_name = "AutomationNode",
        .source = "public-iiot/AutomationNodes/VelocityMover/index.json",
        .text = @embedFile("payloads/automation_node.AutomationNode.json"),
    },
    .{
        .module = "battery_collection",
        .type_name = "BatteryCollection",
        .source = "public-rackmount1/Chassis/1U/PowerSubsystem/Batteries/index.json",
        .text = @embedFile("payloads/battery_collection.BatteryCollection.json"),
    },
    .{
        .module = "battery_metrics",
        .type_name = "BatteryMetrics",
        .source = "public-rackmount1/Chassis/1U/PowerSubsystem/Batteries/Module1/Metrics/index.json",
        .text = @embedFile("payloads/battery_metrics.BatteryMetrics.json"),
    },
    .{
        .module = "battery",
        .type_name = "Battery",
        .source = "public-rackmount1/Chassis/1U/PowerSubsystem/Batteries/Module1/index.json",
        .text = @embedFile("payloads/battery.Battery.json"),
    },
    .{
        .module = "bios",
        .type_name = "Bios",
        .source = "public-rackmount1/Systems/437XR1138R2/Bios/index.json",
        .text = @embedFile("payloads/bios.Bios.json"),
    },
    .{
        .module = "boot_option",
        .type_name = "BootOption",
        .source = "DSP2046-examples/BootOption-v1-example.json",
        .text = @embedFile("payloads/boot_option.BootOption.json"),
    },
    .{
        .module = "cable_collection",
        .type_name = "CableCollection",
        .source = "public-iiot/Cables/index.json",
        .text = @embedFile("payloads/cable_collection.CableCollection.json"),
    },
    .{
        .module = "cable",
        .type_name = "Cable",
        .source = "public-cables/Cables/sata0/index.json",
        .text = @embedFile("payloads/cable.Cable.json"),
    },
    .{
        .module = "certificate_collection",
        .type_name = "CertificateCollection",
        .source = "public-tower/Systems/437XR1238R2/SecureBoot/SecureBootDatabases/db/Certificates/index.json",
        .text = @embedFile("payloads/certificate_collection.CertificateCollection.json"),
    },
    .{
        .module = "certificate_enrollment_collection",
        .type_name = "CertificateEnrollmentCollection",
        .source = "public-rackmount1/CertificateService/CertificateEnrollments/index.json",
        .text = @embedFile("payloads/certificate_enrollment_collection.CertificateEnrollmentCollection.json"),
    },
    .{
        .module = "certificate_enrollment",
        .type_name = "CertificateEnrollment",
        .source = "public-rackmount1/CertificateService/CertificateEnrollments/1/index.json",
        .text = @embedFile("payloads/certificate_enrollment.CertificateEnrollment.json"),
    },
    .{
        .module = "certificate_locations",
        .type_name = "CertificateLocations",
        .source = "public-rackmount1/CertificateService/CertificateLocations/index.json",
        .text = @embedFile("payloads/certificate_locations.CertificateLocations.json"),
    },
    .{
        .module = "certificate_service",
        .type_name = "CertificateService",
        .source = "public-rackmount1/CertificateService/index.json",
        .text = @embedFile("payloads/certificate_service.CertificateService.json"),
    },
    .{
        .module = "certificate",
        .type_name = "Certificate",
        .source = "public-rackmount1/Managers/BMC/NetworkProtocol/HTTPS/Certificates/1/index.json",
        .text = @embedFile("payloads/certificate.Certificate.json"),
    },
    .{
        .module = "chassis_collection",
        .type_name = "ChassisCollection",
        .source = "public-cxl-multiswitch/Chassis/index.json",
        .text = @embedFile("payloads/chassis_collection.ChassisCollection.json"),
    },
    .{
        .module = "chassis",
        .type_name = "Chassis",
        .source = "public-tower/Chassis/Tower/index.json",
        .text = @embedFile("payloads/chassis.Chassis.json"),
    },
    .{
        .module = "circuit_collection",
        .type_name = "CircuitCollection",
        .source = "public-power-shelf/PowerEquipment/PowerShelves/1/Branches/index.json",
        .text = @embedFile("payloads/circuit_collection.CircuitCollection.json"),
    },
    .{
        .module = "circuit",
        .type_name = "Circuit",
        .source = "public-pdu/PowerEquipment/RackPDUs/1/Mains/AC1/index.json",
        .text = @embedFile("payloads/circuit.Circuit.json"),
    },
    .{
        .module = "component_integrity_collection",
        .type_name = "ComponentIntegrityCollection",
        .source = "public-rackmount1/ComponentIntegrity/index.json",
        .text = @embedFile("payloads/component_integrity_collection.ComponentIntegrityCollection.json"),
    },
    .{
        .module = "component_integrity",
        .type_name = "ComponentIntegrity",
        .source = "public-rackmount1/ComponentIntegrity/SS-SPDM-0/index.json",
        .text = @embedFile("payloads/component_integrity.ComponentIntegrity.json"),
    },
    .{
        .module = "component_integrity",
        .type_name = "SpdmGetSignedMeasurementsResponse",
        .source = "DSP2046-examples/ComponentIntegrity-v1-SPDMGetSignedMeasurements-response-example.json",
        .text = @embedFile("payloads/component_integrity.SpdmGetSignedMeasurementsResponse.json"),
    },
    .{
        .module = "composition_reservation_collection",
        .type_name = "CompositionReservationCollection",
        .source = "public-compose-action/CompositionService/CompositionReservations/index.json",
        .text = @embedFile("payloads/composition_reservation_collection.CompositionReservationCollection.json"),
    },
    .{
        .module = "composition_reservation",
        .type_name = "CompositionReservation",
        .source = "public-compose-action/CompositionService/CompositionReservations/1/index.json",
        .text = @embedFile("payloads/composition_reservation.CompositionReservation.json"),
    },
    .{
        .module = "composition_service",
        .type_name = "CompositionService",
        .source = "public-compose-action/CompositionService/index.json",
        .text = @embedFile("payloads/composition_service.CompositionService.json"),
    },
    .{
        .module = "computer_system_collection",
        .type_name = "ComputerSystemCollection",
        .source = "public-composability/Systems/index.json",
        .text = @embedFile("payloads/computer_system_collection.ComputerSystemCollection.json"),
    },
    .{
        .module = "computer_system",
        .type_name = "ComputerSystem",
        .source = "public-rackmount1/Systems/437XR1138R2/index.json",
        .text = @embedFile("payloads/computer_system.ComputerSystem.json"),
    },
    .{
        .module = "connection_collection",
        .type_name = "ConnectionCollection",
        .source = "public-cxl-multiswitch/Fabrics/CXL/Connections/index.json",
        .text = @embedFile("payloads/connection_collection.ConnectionCollection.json"),
    },
    .{
        .module = "connection_method",
        .type_name = "ConnectionMethod",
        .source = "DSP2046-examples/ConnectionMethod-v1-example.json",
        .text = @embedFile("payloads/connection_method.ConnectionMethod.json"),
    },
    .{
        .module = "connection",
        .type_name = "Connection",
        .source = "public-cxl-multiswitch/Fabrics/CXL/Connections/15/index.json",
        .text = @embedFile("payloads/connection.Connection.json"),
    },
    .{
        .module = "container_collection",
        .type_name = "ContainerCollection",
        .source = "public-applications/Systems/VM1/OperatingSystem/Containers/index.json",
        .text = @embedFile("payloads/container_collection.ContainerCollection.json"),
    },
    .{
        .module = "container_image_collection",
        .type_name = "ContainerImageCollection",
        .source = "public-applications/Systems/VM1/OperatingSystem/ContainerImages/index.json",
        .text = @embedFile("payloads/container_image_collection.ContainerImageCollection.json"),
    },
    .{
        .module = "container_image",
        .type_name = "ContainerImage",
        .source = "public-applications/Systems/VM1/OperatingSystem/ContainerImages/WebLogic/index.json",
        .text = @embedFile("payloads/container_image.ContainerImage.json"),
    },
    .{
        .module = "container",
        .type_name = "Container",
        .source = "public-applications/Systems/VM1/OperatingSystem/Containers/Database/index.json",
        .text = @embedFile("payloads/container.Container.json"),
    },
    .{
        .module = "control_collection",
        .type_name = "ControlCollection",
        .source = "public-iiot/Chassis/3AxisMotion/Controls/index.json",
        .text = @embedFile("payloads/control_collection.ControlCollection.json"),
    },
    .{
        .module = "control",
        .type_name = "Control",
        .source = "public-iiot/Chassis/Node5/Controls/Thermostat/index.json",
        .text = @embedFile("payloads/control.Control.json"),
    },
    .{
        .module = "coolant_connector_collection",
        .type_name = "CoolantConnectorCollection",
        .source = "public-cooling-unit/ThermalEquipment/CDUs/1/PrimaryCoolantConnectors/index.json",
        .text = @embedFile("payloads/coolant_connector_collection.CoolantConnectorCollection.json"),
    },
    .{
        .module = "coolant_connector",
        .type_name = "CoolantConnector",
        .source = "public-cooling-unit/ThermalEquipment/CDUs/1/SecondaryCoolantConnectors/1/index.json",
        .text = @embedFile("payloads/coolant_connector.CoolantConnector.json"),
    },
    .{
        .module = "cooling_loop",
        .type_name = "CoolingLoop",
        .source = "DSP2046-examples/CoolingLoop-v1-example.json",
        .text = @embedFile("payloads/cooling_loop.CoolingLoop.json"),
    },
    .{
        .module = "cooling_unit_collection",
        .type_name = "CoolingUnitCollection",
        .source = "public-cooling-unit/ThermalEquipment/CDUs/index.json",
        .text = @embedFile("payloads/cooling_unit_collection.CoolingUnitCollection.json"),
    },
    .{
        .module = "cooling_unit",
        .type_name = "CoolingUnit",
        .source = "public-cooling-unit/ThermalEquipment/CDUs/1/index.json",
        .text = @embedFile("payloads/cooling_unit.CoolingUnit.json"),
    },
    .{
        .module = "cxl_logical_device_collection",
        .type_name = "CxlLogicalDeviceCollection",
        .source = "public-cxl-multiswitch/Chassis/PooledCXLType3-2/PCIeDevices/1/CXLLogicalDevices/index.json",
        .text = @embedFile("payloads/cxl_logical_device_collection.CxlLogicalDeviceCollection.json"),
    },
    .{
        .module = "cxl_logical_device",
        .type_name = "CxlLogicalDevice",
        .source = "public-cxl/Chassis/PooledCXLType3/PCIeDevices/1/CXLLogicalDevices/6/index.json",
        .text = @embedFile("payloads/cxl_logical_device.CxlLogicalDevice.json"),
    },
    .{
        .module = "drive_collection",
        .type_name = "DriveCollection",
        .source = "public-mpf/Chassis/1U/Drives/index.json",
        .text = @embedFile("payloads/drive_collection.DriveCollection.json"),
    },
    .{
        .module = "drive_metrics",
        .type_name = "DriveMetrics",
        .source = "DSP2046-examples/DriveMetrics-v1-example.json",
        .text = @embedFile("payloads/drive_metrics.DriveMetrics.json"),
    },
    .{
        .module = "drive",
        .type_name = "Drive",
        .source = "public-tower/Chassis/Tower/Drives/M.2-2/index.json",
        .text = @embedFile("payloads/drive.Drive.json"),
    },
    .{
        .module = "endpoint_collection",
        .type_name = "EndpointCollection",
        .source = "public-sasfabric/Fabrics/SAS/Endpoints/index.json",
        .text = @embedFile("payloads/endpoint_collection.EndpointCollection.json"),
    },
    .{
        .module = "endpoint_group_collection",
        .type_name = "EndpointGroupCollection",
        .source = "public-nvmeof-jbof/Fabrics/NVMeoF/EndpointGroups/index.json",
        .text = @embedFile("payloads/endpoint_group_collection.EndpointGroupCollection.json"),
    },
    .{
        .module = "endpoint_group",
        .type_name = "EndpointGroup",
        .source = "public-nvmeof-jbof/Fabrics/NVMeoF/EndpointGroups/1/index.json",
        .text = @embedFile("payloads/endpoint_group.EndpointGroup.json"),
    },
    .{
        .module = "endpoint",
        .type_name = "Endpoint",
        .source = "public-sasfabric/Fabrics/SAS/Endpoints/Enclosure2/index.json",
        .text = @embedFile("payloads/endpoint.Endpoint.json"),
    },
    .{
        .module = "environment_metrics",
        .type_name = "EnvironmentMetrics",
        .source = "public-tower/Chassis/Tower/EnvironmentMetrics/index.json",
        .text = @embedFile("payloads/environment_metrics.EnvironmentMetrics.json"),
    },
    .{
        .module = "ethernet_interface_collection",
        .type_name = "EthernetInterfaceCollection",
        .source = "public-bladed-partitions/Systems/ComposedPartition2/EthernetInterfaces/index.json",
        .text = @embedFile("payloads/ethernet_interface_collection.EthernetInterfaceCollection.json"),
    },
    .{
        .module = "ethernet_interface",
        .type_name = "EthernetInterface",
        .source = "public-telemetry/Managers/1/EthernetInterfaces/1/index.json",
        .text = @embedFile("payloads/ethernet_interface.EthernetInterface.json"),
    },
    .{
        .module = "event_destination_collection",
        .type_name = "EventDestinationCollection",
        .source = "public-tower/EventService/Subscriptions/index.json",
        .text = @embedFile("payloads/event_destination_collection.EventDestinationCollection.json"),
    },
    .{
        .module = "event_destination",
        .type_name = "EventDestination",
        .source = "public-tower/EventService/Subscriptions/2/index.json",
        .text = @embedFile("payloads/event_destination.EventDestination.json"),
    },
    .{
        .module = "event_service",
        .type_name = "EventService",
        .source = "public-tower/EventService/index.json",
        .text = @embedFile("payloads/event_service.EventService.json"),
    },
    .{
        .module = "event",
        .type_name = "Event",
        .source = "non-resource-examples/EventExampleWithOrigin.json",
        .text = @embedFile("payloads/event.Event.json"),
    },
    .{
        .module = "external_account_provider_collection",
        .type_name = "ExternalAccountProviderCollection",
        .source = "public-tower/AccountService/ExternalAccountProviders/index.json",
        .text = @embedFile("payloads/external_account_provider_collection.ExternalAccountProviderCollection.json"),
    },
    .{
        .module = "external_account_provider",
        .type_name = "ExternalAccountProvider",
        .source = "public-tower/AccountService/ExternalAccountProviders/ExternalRedfishService/index.json",
        .text = @embedFile("payloads/external_account_provider.ExternalAccountProvider.json"),
    },
    .{
        .module = "fabric_adapter_collection",
        .type_name = "FabricAdapterCollection",
        .source = "public-cxl-multiswitch/Chassis/PooledCXLType3-2/FabricAdapters/index.json",
        .text = @embedFile("payloads/fabric_adapter_collection.FabricAdapterCollection.json"),
    },
    .{
        .module = "fabric_adapter",
        .type_name = "FabricAdapter",
        .source = "DSP2046-examples/FabricAdapter-v1-example.json",
        .text = @embedFile("payloads/fabric_adapter.FabricAdapter.json"),
    },
    .{
        .module = "fabric_collection",
        .type_name = "FabricCollection",
        .source = "public-smartnic/Fabrics/index.json",
        .text = @embedFile("payloads/fabric_collection.FabricCollection.json"),
    },
    .{
        .module = "fabric",
        .type_name = "Fabric",
        .source = "public-cxl/Fabrics/CXL/index.json",
        .text = @embedFile("payloads/fabric.Fabric.json"),
    },
    .{
        .module = "facility_collection",
        .type_name = "FacilityCollection",
        .source = "public-power-shelf/Facilities/index.json",
        .text = @embedFile("payloads/facility_collection.FacilityCollection.json"),
    },
    .{
        .module = "facility",
        .type_name = "Facility",
        .source = "public-power-shelf/Facilities/Room237/index.json",
        .text = @embedFile("payloads/facility.Facility.json"),
    },
    .{
        .module = "fan_collection",
        .type_name = "FanCollection",
        .source = "public-tower/Chassis/Tower/ThermalSubsystem/Fans/index.json",
        .text = @embedFile("payloads/fan_collection.FanCollection.json"),
    },
    .{
        .module = "fan",
        .type_name = "Fan",
        .source = "public-rackmount1/Chassis/1U/ThermalSubsystem/Fans/Bay2/index.json",
        .text = @embedFile("payloads/fan.Fan.json"),
    },
    .{
        .module = "filter_collection",
        .type_name = "FilterCollection",
        .source = "public-cooling-unit/ThermalEquipment/CDUs/1/Filters/index.json",
        .text = @embedFile("payloads/filter_collection.FilterCollection.json"),
    },
    .{
        .module = "filter",
        .type_name = "Filter",
        .source = "public-cooling-unit/ThermalEquipment/CDUs/1/Filters/1/index.json",
        .text = @embedFile("payloads/filter.Filter.json"),
    },
    .{
        .module = "graphics_controller_collection",
        .type_name = "GraphicsControllerCollection",
        .source = "public-tower/Systems/437XR1238R2/GraphicsControllers/index.json",
        .text = @embedFile("payloads/graphics_controller_collection.GraphicsControllerCollection.json"),
    },
    .{
        .module = "graphics_controller",
        .type_name = "GraphicsController",
        .source = "public-tower/Systems/437XR1238R2/GraphicsControllers/GPU2/index.json",
        .text = @embedFile("payloads/graphics_controller.GraphicsController.json"),
    },
    .{
        .module = "heater_collection",
        .type_name = "HeaterCollection",
        .source = "public-rackmount1/Chassis/1U/ThermalSubsystem/Heaters/index.json",
        .text = @embedFile("payloads/heater_collection.HeaterCollection.json"),
    },
    .{
        .module = "heater_metrics",
        .type_name = "HeaterMetrics",
        .source = "public-rackmount1/Chassis/1U/ThermalSubsystem/Heaters/CPU1Heater/Metrics/index.json",
        .text = @embedFile("payloads/heater_metrics.HeaterMetrics.json"),
    },
    .{
        .module = "heater",
        .type_name = "Heater",
        .source = "public-rackmount1/Chassis/1U/ThermalSubsystem/Heaters/CPU1Heater/index.json",
        .text = @embedFile("payloads/heater.Heater.json"),
    },
    .{
        .module = "host_interface_collection",
        .type_name = "HostInterfaceCollection",
        .source = "public-rackmount1/Managers/BMC/HostInterfaces/index.json",
        .text = @embedFile("payloads/host_interface_collection.HostInterfaceCollection.json"),
    },
    .{
        .module = "host_interface",
        .type_name = "HostInterface",
        .source = "public-rackmount1/Managers/BMC/HostInterfaces/1/index.json",
        .text = @embedFile("payloads/host_interface.HostInterface.json"),
    },
    .{
        .module = "job_collection",
        .type_name = "JobCollection",
        .source = "public-iiot/JobService/Jobs/index.json",
        .text = @embedFile("payloads/job_collection.JobCollection.json"),
    },
    .{
        .module = "job_document_collection",
        .type_name = "JobDocumentCollection",
        .source = "public-iiot/JobService/Documents/index.json",
        .text = @embedFile("payloads/job_document_collection.JobDocumentCollection.json"),
    },
    .{
        .module = "job_document",
        .type_name = "JobDocument",
        .source = "public-iiot/JobService/Documents/Recipe1/index.json",
        .text = @embedFile("payloads/job_document.JobDocument.json"),
    },
    .{
        .module = "job_executor_collection",
        .type_name = "JobExecutorCollection",
        .source = "public-iiot/JobService/Executors/index.json",
        .text = @embedFile("payloads/job_executor_collection.JobExecutorCollection.json"),
    },
    .{
        .module = "job_executor",
        .type_name = "JobExecutor",
        .source = "public-iiot/JobService/Executors/1/index.json",
        .text = @embedFile("payloads/job_executor.JobExecutor.json"),
    },
    .{
        .module = "job_service",
        .type_name = "JobService",
        .source = "public-iiot/JobService/index.json",
        .text = @embedFile("payloads/job_service.JobService.json"),
    },
    .{
        .module = "job",
        .type_name = "Job",
        .source = "public-iiot/JobService/Jobs/1/index.json",
        .text = @embedFile("payloads/job.Job.json"),
    },
    .{
        .module = "json_schema_file",
        .type_name = "JsonSchemaFile",
        .source = "DSP2046-examples/JsonSchemaFile-v1-example.json",
        .text = @embedFile("payloads/json_schema_file.JsonSchemaFile.json"),
    },
    .{
        .module = "key_collection",
        .type_name = "KeyCollection",
        .source = "public-rackmount1/KeyService/NVMeoFSecrets/index.json",
        .text = @embedFile("payloads/key_collection.KeyCollection.json"),
    },
    .{
        .module = "key_policy_collection",
        .type_name = "KeyPolicyCollection",
        .source = "public-rackmount1/KeyService/NVMeoFKeyPolicies/index.json",
        .text = @embedFile("payloads/key_policy_collection.KeyPolicyCollection.json"),
    },
    .{
        .module = "key_policy",
        .type_name = "KeyPolicy",
        .source = "public-rackmount1/KeyService/NVMeoFKeyPolicies/0/index.json",
        .text = @embedFile("payloads/key_policy.KeyPolicy.json"),
    },
    .{
        .module = "key_service",
        .type_name = "KeyService",
        .source = "public-rackmount1/KeyService/index.json",
        .text = @embedFile("payloads/key_service.KeyService.json"),
    },
    .{
        .module = "key",
        .type_name = "Key",
        .source = "public-rackmount1/KeyService/NVMeoFSecrets/0/index.json",
        .text = @embedFile("payloads/key.Key.json"),
    },
    .{
        .module = "leak_detection",
        .type_name = "LeakDetection",
        .source = "public-cooling-unit/ThermalEquipment/CDUs/1/LeakDetection/index.json",
        .text = @embedFile("payloads/leak_detection.LeakDetection.json"),
    },
    .{
        .module = "leak_detector_collection",
        .type_name = "LeakDetectorCollection",
        .source = "public-cooling-unit/ThermalEquipment/CDUs/1/LeakDetection/LeakDetectors/index.json",
        .text = @embedFile("payloads/leak_detector_collection.LeakDetectorCollection.json"),
    },
    .{
        .module = "leak_detector",
        .type_name = "LeakDetector",
        .source = "public-cooling-unit/Chassis/CDU/LeakDetectors/Moisture/index.json",
        .text = @embedFile("payloads/leak_detector.LeakDetector.json"),
    },
    .{
        .module = "license_service",
        .type_name = "LicenseService",
        .source = "DSP2046-examples/LicenseService-v1-example.json",
        .text = @embedFile("payloads/license_service.LicenseService.json"),
    },
    .{
        .module = "license",
        .type_name = "License",
        .source = "DSP2046-examples/License-v1-example.json",
        .text = @embedFile("payloads/license.License.json"),
    },
    .{
        .module = "log_entry_collection",
        .type_name = "LogEntryCollection",
        .source = "public-smartnic/Systems/437XR1138R2/LogServices/Log1/Entries/index.json",
        .text = @embedFile("payloads/log_entry_collection.LogEntryCollection.json"),
    },
    .{
        .module = "log_entry",
        .type_name = "LogEntry",
        .source = "public-cxl/Chassis/CXL-Chassis/LogServices/LocalLog1/Entries/1/index.json",
        .text = @embedFile("payloads/log_entry.LogEntry.json"),
    },
    .{
        .module = "log_service_collection",
        .type_name = "LogServiceCollection",
        .source = "public-iiot/Managers/AutomationManager/LogServices/index.json",
        .text = @embedFile("payloads/log_service_collection.LogServiceCollection.json"),
    },
    .{
        .module = "log_service",
        .type_name = "LogService",
        .source = "public-cxl/Chassis/CXL-Chassis/LogServices/LocalLog1/index.json",
        .text = @embedFile("payloads/log_service.LogService.json"),
    },
    .{
        .module = "manager_account_collection",
        .type_name = "ManagerAccountCollection",
        .source = "public-oem-examples/AccountService/Accounts/index.json",
        .text = @embedFile("payloads/manager_account_collection.ManagerAccountCollection.json"),
    },
    .{
        .module = "manager_account",
        .type_name = "ManagerAccount",
        .source = "public-rackmount1/AccountService/Accounts/1/index.json",
        .text = @embedFile("payloads/manager_account.ManagerAccount.json"),
    },
    .{
        .module = "manager_collection",
        .type_name = "ManagerCollection",
        .source = "public-bladed-partitions/Managers/index.json",
        .text = @embedFile("payloads/manager_collection.ManagerCollection.json"),
    },
    .{
        .module = "manager_diagnostic_data",
        .type_name = "ManagerDiagnosticData",
        .source = "DSP2046-examples/ManagerDiagnosticData-v1-example.json",
        .text = @embedFile("payloads/manager_diagnostic_data.ManagerDiagnosticData.json"),
    },
    .{
        .module = "manager_network_protocol",
        .type_name = "ManagerNetworkProtocol",
        .source = "public-rackmount1/Managers/BMC/NetworkProtocol/index.json",
        .text = @embedFile("payloads/manager_network_protocol.ManagerNetworkProtocol.json"),
    },
    .{
        .module = "manager",
        .type_name = "Manager",
        .source = "public-bladed-partitions/Managers/EncMgr2/index.json",
        .text = @embedFile("payloads/manager.Manager.json"),
    },
    .{
        .module = "media_controller",
        .type_name = "MediaController",
        .source = "DSP2046-examples/MediaController-v1-example.json",
        .text = @embedFile("payloads/media_controller.MediaController.json"),
    },
    .{
        .module = "memory_chunks_collection",
        .type_name = "MemoryChunksCollection",
        .source = "public-pmem-configuration/Systems/AddPMEM/MemoryDomains/PMEM-1/MemoryChunks/index.json",
        .text = @embedFile("payloads/memory_chunks_collection.MemoryChunksCollection.json"),
    },
    .{
        .module = "memory_chunks",
        .type_name = "MemoryChunks",
        .source = "public-pmem-configuration/Systems/Config-4-PMEM/MemoryDomains/PMEM-1/MemoryChunks/PMEM-Persistent-5/index.json",
        .text = @embedFile("payloads/memory_chunks.MemoryChunks.json"),
    },
    .{
        .module = "memory_collection",
        .type_name = "MemoryCollection",
        .source = "public-tower/Systems/437XR1238R2/Memory/index.json",
        .text = @embedFile("payloads/memory_collection.MemoryCollection.json"),
    },
    .{
        .module = "memory_domain_collection",
        .type_name = "MemoryDomainCollection",
        .source = "public-cxl-multiswitch/Chassis/PooledCXLType3-2/MemoryDomains/index.json",
        .text = @embedFile("payloads/memory_domain_collection.MemoryDomainCollection.json"),
    },
    .{
        .module = "memory_domain",
        .type_name = "MemoryDomain",
        .source = "public-pmem-configuration/Systems/Config-4-PMEM/MemoryDomains/PMEM-1/index.json",
        .text = @embedFile("payloads/memory_domain.MemoryDomain.json"),
    },
    .{
        .module = "memory_extent",
        .type_name = "MemoryExtent",
        .source = "DSP2046-examples/MemoryExtent-v1-example.json",
        .text = @embedFile("payloads/memory_extent.MemoryExtent.json"),
    },
    .{
        .module = "memory_metrics",
        .type_name = "MemoryMetrics",
        .source = "public-telemetry/Systems/1/Memory/2/MemoryMetrics/index.json",
        .text = @embedFile("payloads/memory_metrics.MemoryMetrics.json"),
    },
    .{
        .module = "memory_region_collection",
        .type_name = "MemoryRegionCollection",
        .source = "public-cxl/Chassis/PooledCXLType3/PCIeDevices/1/CXLLogicalDevices/6/MemoryRegions/index.json",
        .text = @embedFile("payloads/memory_region_collection.MemoryRegionCollection.json"),
    },
    .{
        .module = "memory_region",
        .type_name = "MemoryRegion",
        .source = "public-cxl/Chassis/PooledCXLType3/PCIeDevices/1/CXLLogicalDevices/6/MemoryRegions/1/index.json",
        .text = @embedFile("payloads/memory_region.MemoryRegion.json"),
    },
    .{
        .module = "memory",
        .type_name = "Memory",
        .source = "public-cxl-multiswitch/Chassis/CXLType3/Memory/3DXP/index.json",
        .text = @embedFile("payloads/memory.Memory.json"),
    },
    .{
        .module = "message_registry_file_collection",
        .type_name = "MessageRegistryFileCollection",
        .source = "public-tower/Registries/index.json",
        .text = @embedFile("payloads/message_registry_file_collection.MessageRegistryFileCollection.json"),
    },
    .{
        .module = "message_registry_file",
        .type_name = "MessageRegistryFile",
        .source = "DSP2046-examples/MessageRegistryFile-v1-example.json",
        .text = @embedFile("payloads/message_registry_file.MessageRegistryFile.json"),
    },
    .{
        .module = "message_registry",
        .type_name = "MessageRegistry",
        .source = "public-tower/Registries/Base.1.5.0.json",
        .text = @embedFile("payloads/message_registry.MessageRegistry.json"),
    },
    .{
        .module = "metric_definition_collection",
        .type_name = "MetricDefinitionCollection",
        .source = "public-telemetry/TelemetryService/MetricDefinitions/index.json",
        .text = @embedFile("payloads/metric_definition_collection.MetricDefinitionCollection.json"),
    },
    .{
        .module = "metric_definition",
        .type_name = "MetricDefinition",
        .source = "public-telemetry/TelemetryService/MetricDefinitions/OutletAirflowTemp/index.json",
        .text = @embedFile("payloads/metric_definition.MetricDefinition.json"),
    },
    .{
        .module = "metric_report_collection",
        .type_name = "MetricReportCollection",
        .source = "public-telemetry/TelemetryService/MetricReports/index.json",
        .text = @embedFile("payloads/metric_report_collection.MetricReportCollection.json"),
    },
    .{
        .module = "metric_report_definition_collection",
        .type_name = "MetricReportDefinitionCollection",
        .source = "public-telemetry/TelemetryService/MetricReportDefinitions/index.json",
        .text = @embedFile("payloads/metric_report_definition_collection.MetricReportDefinitionCollection.json"),
    },
    .{
        .module = "metric_report_definition",
        .type_name = "MetricReportDefinition",
        .source = "public-telemetry/TelemetryService/MetricReportDefinitions/PowerMetrics/index.json",
        .text = @embedFile("payloads/metric_report_definition.MetricReportDefinition.json"),
    },
    .{
        .module = "metric_report",
        .type_name = "MetricReport",
        .source = "public-telemetry/TelemetryService/MetricReports/PowerMetricStats/index.json",
        .text = @embedFile("payloads/metric_report.MetricReport.json"),
    },
    .{
        .module = "network_adapter_collection",
        .type_name = "NetworkAdapterCollection",
        .source = "public-acd/Chassis/1U/NetworkAdapters/index.json",
        .text = @embedFile("payloads/network_adapter_collection.NetworkAdapterCollection.json"),
    },
    .{
        .module = "network_adapter_metrics",
        .type_name = "NetworkAdapterMetrics",
        .source = "public-acd/Chassis/1U/NetworkAdapters/Slot3/Metrics/index.json",
        .text = @embedFile("payloads/network_adapter_metrics.NetworkAdapterMetrics.json"),
    },
    .{
        .module = "network_adapter",
        .type_name = "NetworkAdapter",
        .source = "public-acd/Chassis/1U/NetworkAdapters/Slot3/index.json",
        .text = @embedFile("payloads/network_adapter.NetworkAdapter.json"),
    },
    .{
        .module = "network_device_function_collection",
        .type_name = "NetworkDeviceFunctionCollection",
        .source = "public-acd/Chassis/1U/NetworkAdapters/Slot3/NetworkDeviceFunctions/index.json",
        .text = @embedFile("payloads/network_device_function_collection.NetworkDeviceFunctionCollection.json"),
    },
    .{
        .module = "network_device_function_metrics",
        .type_name = "NetworkDeviceFunctionMetrics",
        .source = "public-acd/Chassis/1U/NetworkAdapters/Slot3/NetworkDeviceFunctions/CSP_P4/Metrics/index.json",
        .text = @embedFile("payloads/network_device_function_metrics.NetworkDeviceFunctionMetrics.json"),
    },
    .{
        .module = "network_device_function",
        .type_name = "NetworkDeviceFunction",
        .source = "public-tower/Chassis/Tower/NetworkAdapters/NIC1/NetworkDeviceFunctions/2/index.json",
        .text = @embedFile("payloads/network_device_function.NetworkDeviceFunction.json"),
    },
    .{
        .module = "network_interface_collection",
        .type_name = "NetworkInterfaceCollection",
        .source = "public-smartnic/Systems/437XR1138R2/NetworkInterfaces/index.json",
        .text = @embedFile("payloads/network_interface_collection.NetworkInterfaceCollection.json"),
    },
    .{
        .module = "network_interface",
        .type_name = "NetworkInterface",
        .source = "public-smartnic/Systems/437XR1138R2/NetworkInterfaces/4AWAIJ/index.json",
        .text = @embedFile("payloads/network_interface.NetworkInterface.json"),
    },
    .{
        .module = "network_port_collection",
        .type_name = "NetworkPortCollection",
        .source = "public-nvmeof-jbof/Systems/NVMeoF-SoC/NetworkInterfaces/1/NetworkPorts/index.json",
        .text = @embedFile("payloads/network_port_collection.NetworkPortCollection.json"),
    },
    .{
        .module = "network_port",
        .type_name = "NetworkPort",
        .source = "public-nvmeof-jbof/Chassis/1/NetworkAdapters/1/NetworkPorts/1/index.json",
        .text = @embedFile("payloads/network_port.NetworkPort.json"),
    },
    .{
        .module = "operating_config",
        .type_name = "OperatingConfig",
        .source = "DSP2046-examples/OperatingConfig-v1-example.json",
        .text = @embedFile("payloads/operating_config.OperatingConfig.json"),
    },
    .{
        .module = "operating_system",
        .type_name = "OperatingSystem",
        .source = "public-applications/Systems/VM1/OperatingSystem/index.json",
        .text = @embedFile("payloads/operating_system.OperatingSystem.json"),
    },
    .{
        .module = "outbound_connection_collection",
        .type_name = "OutboundConnectionCollection",
        .source = "public-rackmount1/AccountService/OutboundConnections/index.json",
        .text = @embedFile("payloads/outbound_connection_collection.OutboundConnectionCollection.json"),
    },
    .{
        .module = "outbound_connection",
        .type_name = "OutboundConnection",
        .source = "public-rackmount1/AccountService/OutboundConnections/1/index.json",
        .text = @embedFile("payloads/outbound_connection.OutboundConnection.json"),
    },
    .{
        .module = "outlet_collection",
        .type_name = "OutletCollection",
        .source = "public-pdu/PowerEquipment/RackPDUs/1/Outlets/index.json",
        .text = @embedFile("payloads/outlet_collection.OutletCollection.json"),
    },
    .{
        .module = "outlet_group_collection",
        .type_name = "OutletGroupCollection",
        .source = "public-pdu/PowerEquipment/TransferSwitches/1/OutletGroups/index.json",
        .text = @embedFile("payloads/outlet_group_collection.OutletGroupCollection.json"),
    },
    .{
        .module = "outlet_group",
        .type_name = "OutletGroup",
        .source = "public-pdu/PowerEquipment/TransferSwitches/1/OutletGroups/Rack5Storage/index.json",
        .text = @embedFile("payloads/outlet_group.OutletGroup.json"),
    },
    .{
        .module = "outlet",
        .type_name = "Outlet",
        .source = "public-pdu/PowerEquipment/TransferSwitches/1/Outlets/A3/index.json",
        .text = @embedFile("payloads/outlet.Outlet.json"),
    },
    .{
        .module = "pcie_device_collection",
        .type_name = "PcieDeviceCollection",
        .source = "public-tower/Chassis/Tower/PCIeDevices/index.json",
        .text = @embedFile("payloads/pcie_device_collection.PcieDeviceCollection.json"),
    },
    .{
        .module = "pcie_device",
        .type_name = "PcieDevice",
        .source = "public-cxl-multiswitch/Chassis/PooledCXLType3-2/PCIeDevices/1/index.json",
        .text = @embedFile("payloads/pcie_device.PcieDevice.json"),
    },
    .{
        .module = "pcie_function_collection",
        .type_name = "PcieFunctionCollection",
        .source = "public-cxl-multiswitch/Chassis/PooledCXLType3-2/PCIeDevices/1/PCIeFunctions/index.json",
        .text = @embedFile("payloads/pcie_function_collection.PcieFunctionCollection.json"),
    },
    .{
        .module = "pcie_function",
        .type_name = "PcieFunction",
        .source = "public-cxl-multiswitch/Chassis/PooledCXLType3-2/PCIeDevices/1/PCIeFunctions/6/index.json",
        .text = @embedFile("payloads/pcie_function.PcieFunction.json"),
    },
    .{
        .module = "pcie_slots",
        .type_name = "PcieSlots",
        .source = "public-tower/Chassis/Tower/PCIeSlots/index.json",
        .text = @embedFile("payloads/pcie_slots.PcieSlots.json"),
    },
    .{
        .module = "port_collection",
        .type_name = "PortCollection",
        .source = "public-sasfabric/Fabrics/SAS/Switches/Switch2/Ports/index.json",
        .text = @embedFile("payloads/port_collection.PortCollection.json"),
    },
    .{
        .module = "port_metrics",
        .type_name = "PortMetrics",
        .source = "public-acd/Chassis/1U/NetworkAdapters/Slot3/Ports/CSP_P4/Metrics/index.json",
        .text = @embedFile("payloads/port_metrics.PortMetrics.json"),
    },
    .{
        .module = "port",
        .type_name = "Port",
        .source = "public-cxl/Fabrics/CXL/Switches/CXL/Ports/U1/index.json",
        .text = @embedFile("payloads/port.Port.json"),
    },
    .{
        .module = "power_distribution_collection",
        .type_name = "PowerDistributionCollection",
        .source = "public-power-shelf/PowerEquipment/ElectricalBuses/index.json",
        .text = @embedFile("payloads/power_distribution_collection.PowerDistributionCollection.json"),
    },
    .{
        .module = "power_distribution_metrics",
        .type_name = "PowerDistributionMetrics",
        .source = "public-power-shelf/PowerEquipment/PowerShelves/1/Metrics/index.json",
        .text = @embedFile("payloads/power_distribution_metrics.PowerDistributionMetrics.json"),
    },
    .{
        .module = "power_distribution",
        .type_name = "PowerDistribution",
        .source = "public-pdu/PowerEquipment/TransferSwitches/1/index.json",
        .text = @embedFile("payloads/power_distribution.PowerDistribution.json"),
    },
    .{
        .module = "power_domain_collection",
        .type_name = "PowerDomainCollection",
        .source = "public-power-shelf/Facilities/Room237/PowerDomains/index.json",
        .text = @embedFile("payloads/power_domain_collection.PowerDomainCollection.json"),
    },
    .{
        .module = "power_domain",
        .type_name = "PowerDomain",
        .source = "public-power-shelf/Facilities/Room237/PowerDomains/Row1/index.json",
        .text = @embedFile("payloads/power_domain.PowerDomain.json"),
    },
    .{
        .module = "power_equipment",
        .type_name = "PowerEquipment",
        .source = "public-pdu/PowerEquipment/index.json",
        .text = @embedFile("payloads/power_equipment.PowerEquipment.json"),
    },
    .{
        .module = "power_subsystem",
        .type_name = "PowerSubsystem",
        .source = "public-power-shelf/Chassis/PowerShelf/PowerSubsystem/index.json",
        .text = @embedFile("payloads/power_subsystem.PowerSubsystem.json"),
    },
    .{
        .module = "power_supply_collection",
        .type_name = "PowerSupplyCollection",
        .source = "public-power-shelf/Chassis/PowerShelf/PowerSubsystem/PowerSupplies/index.json",
        .text = @embedFile("payloads/power_supply_collection.PowerSupplyCollection.json"),
    },
    .{
        .module = "power_supply_metrics",
        .type_name = "PowerSupplyMetrics",
        .source = "public-tower/Chassis/Tower/PowerSubsystem/PowerSupplies/Bay1/Metrics/index.json",
        .text = @embedFile("payloads/power_supply_metrics.PowerSupplyMetrics.json"),
    },
    .{
        .module = "power_supply",
        .type_name = "PowerSupply",
        .source = "public-rackmount1/Chassis/1U/PowerSubsystem/PowerSupplies/Bay1/index.json",
        .text = @embedFile("payloads/power_supply.PowerSupply.json"),
    },
    .{
        .module = "power",
        .type_name = "Power",
        .source = "public-telemetry/Chassis/1/Power/index.json",
        .text = @embedFile("payloads/power.Power.json"),
    },
    .{
        .module = "privilege_registry",
        .type_name = "PrivilegeRegistry",
        .source = "DSP2046-examples/PrivilegeRegistry-v1-example.json",
        .text = @embedFile("payloads/privilege_registry.PrivilegeRegistry.json"),
    },
    .{
        .module = "processor_collection",
        .type_name = "ProcessorCollection",
        .source = "public-tower/Systems/437XR1238R2/Processors/CPU8/SubProcessors/index.json",
        .text = @embedFile("payloads/processor_collection.ProcessorCollection.json"),
    },
    .{
        .module = "processor_metrics",
        .type_name = "ProcessorMetrics",
        .source = "public-rackmount1/Systems/437XR1138R2/Processors/FPGA1/ProcessorMetrics/index.json",
        .text = @embedFile("payloads/processor_metrics.ProcessorMetrics.json"),
    },
    .{
        .module = "processor",
        .type_name = "Processor",
        .source = "public-rackmount1/Systems/437XR1138R2/Processors/FPGA1/index.json",
        .text = @embedFile("payloads/processor.Processor.json"),
    },
    .{
        .module = "pump_collection",
        .type_name = "PumpCollection",
        .source = "public-liquid-cooled-server/Chassis/1U/ThermalSubsystem/Pumps/index.json",
        .text = @embedFile("payloads/pump_collection.PumpCollection.json"),
    },
    .{
        .module = "pump",
        .type_name = "Pump",
        .source = "public-cooling-unit/ThermalEquipment/CDUs/1/Pumps/2/index.json",
        .text = @embedFile("payloads/pump.Pump.json"),
    },
    .{
        .module = "registered_client",
        .type_name = "RegisteredClient",
        .source = "DSP2046-examples/RegisteredClient-v1-example.json",
        .text = @embedFile("payloads/registered_client.RegisteredClient.json"),
    },
    .{
        .module = "reservoir_collection",
        .type_name = "ReservoirCollection",
        .source = "public-cooling-unit/ThermalEquipment/CDUs/1/Reservoirs/index.json",
        .text = @embedFile("payloads/reservoir_collection.ReservoirCollection.json"),
    },
    .{
        .module = "reservoir",
        .type_name = "Reservoir",
        .source = "DSP2046-examples/Reservoir-v1-example.json",
        .text = @embedFile("payloads/reservoir.Reservoir.json"),
    },
    .{
        .module = "resource_block_collection",
        .type_name = "ResourceBlockCollection",
        .source = "public-composability/CompositionService/ResourceBlocks/index.json",
        .text = @embedFile("payloads/resource_block_collection.ResourceBlockCollection.json"),
    },
    .{
        .module = "resource_block",
        .type_name = "ResourceBlock",
        .source = "public-constrained-composition/CompositionService/ResourceBlocks/ComputeBlock1/index.json",
        .text = @embedFile("payloads/resource_block.ResourceBlock.json"),
    },
    .{
        .module = "role_collection",
        .type_name = "RoleCollection",
        .source = "public-telemetry/AccountService/Roles/index.json",
        .text = @embedFile("payloads/role_collection.RoleCollection.json"),
    },
    .{
        .module = "role",
        .type_name = "Role",
        .source = "public-tower/AccountService/Roles/Administrator/index.json",
        .text = @embedFile("payloads/role.Role.json"),
    },
    .{
        .module = "route_entry",
        .type_name = "RouteEntry",
        .source = "DSP2046-examples/RouteEntry-v1-example.json",
        .text = @embedFile("payloads/route_entry.RouteEntry.json"),
    },
    .{
        .module = "route_set_entry",
        .type_name = "RouteSetEntry",
        .source = "DSP2046-examples/RouteSetEntry-v1-example.json",
        .text = @embedFile("payloads/route_set_entry.RouteSetEntry.json"),
    },
    .{
        .module = "secure_boot_database_collection",
        .type_name = "SecureBootDatabaseCollection",
        .source = "public-tower/Systems/437XR1238R2/SecureBoot/SecureBootDatabases/index.json",
        .text = @embedFile("payloads/secure_boot_database_collection.SecureBootDatabaseCollection.json"),
    },
    .{
        .module = "secure_boot_database",
        .type_name = "SecureBootDatabase",
        .source = "public-tower/Systems/437XR1238R2/SecureBoot/SecureBootDatabases/dbx/index.json",
        .text = @embedFile("payloads/secure_boot_database.SecureBootDatabase.json"),
    },
    .{
        .module = "secure_boot",
        .type_name = "SecureBoot",
        .source = "public-tower/Systems/437XR1238R2/SecureBoot/index.json",
        .text = @embedFile("payloads/secure_boot.SecureBoot.json"),
    },
    .{
        .module = "security_policy",
        .type_name = "SecurityPolicy",
        .source = "public-rackmount1/Managers/BMC/SecurityPolicy/index.json",
        .text = @embedFile("payloads/security_policy.SecurityPolicy.json"),
    },
    .{
        .module = "sensor_collection",
        .type_name = "SensorCollection",
        .source = "public-pdu/PowerEquipment/TransferSwitches/1/Sensors/index.json",
        .text = @embedFile("payloads/sensor_collection.SensorCollection.json"),
    },
    .{
        .module = "sensor",
        .type_name = "Sensor",
        .source = "public-rackmount1/Chassis/1U/Sensors/CPU1Temp/index.json",
        .text = @embedFile("payloads/sensor.Sensor.json"),
    },
    .{
        .module = "serial_interface_collection",
        .type_name = "SerialInterfaceCollection",
        .source = "public-iiot/Managers/AutomationManager/SerialInterfaces/index.json",
        .text = @embedFile("payloads/serial_interface_collection.SerialInterfaceCollection.json"),
    },
    .{
        .module = "serial_interface",
        .type_name = "SerialInterface",
        .source = "public-iiot/Managers/AutomationManager/SerialInterfaces/TTY0/index.json",
        .text = @embedFile("payloads/serial_interface.SerialInterface.json"),
    },
    .{
        .module = "service_conditions",
        .type_name = "ServiceConditions",
        .source = "public-rackmount1/ServiceConditions/index.json",
        .text = @embedFile("payloads/service_conditions.ServiceConditions.json"),
    },
    .{
        .module = "service_root",
        .type_name = "ServiceRoot",
        .source = "public-rackmount1/index.json",
        .text = @embedFile("payloads/service_root.ServiceRoot.json"),
    },
    .{
        .module = "session_collection",
        .type_name = "SessionCollection",
        .source = "public-rackmount1/SessionService/Sessions/index.json",
        .text = @embedFile("payloads/session_collection.SessionCollection.json"),
    },
    .{
        .module = "session_service",
        .type_name = "SessionService",
        .source = "public-rackmount1/SessionService/index.json",
        .text = @embedFile("payloads/session_service.SessionService.json"),
    },
    .{
        .module = "session",
        .type_name = "Session",
        .source = "public-rackmount1/SessionService/Sessions/1234567890ABCDEG/index.json",
        .text = @embedFile("payloads/session.Session.json"),
    },
    .{
        .module = "signature_collection",
        .type_name = "SignatureCollection",
        .source = "public-tower/Systems/437XR1238R2/SecureBoot/SecureBootDatabases/dbx/Signatures/index.json",
        .text = @embedFile("payloads/signature_collection.SignatureCollection.json"),
    },
    .{
        .module = "signature",
        .type_name = "Signature",
        .source = "public-tower/Systems/437XR1238R2/SecureBoot/SecureBootDatabases/dbxDefault/Signatures/1/index.json",
        .text = @embedFile("payloads/signature.Signature.json"),
    },
    .{
        .module = "simple_storage_collection",
        .type_name = "SimpleStorageCollection",
        .source = "public-smartnic/Systems/437XR1138R2/SimpleStorage/index.json",
        .text = @embedFile("payloads/simple_storage_collection.SimpleStorageCollection.json"),
    },
    .{
        .module = "simple_storage",
        .type_name = "SimpleStorage",
        .source = "public-constrained-composition/CompositionService/ResourceBlocks/DriveBlock7/SimpleStorage/Block7SASTray/index.json",
        .text = @embedFile("payloads/simple_storage.SimpleStorage.json"),
    },
    .{
        .module = "software_inventory_collection",
        .type_name = "SoftwareInventoryCollection",
        .source = "public-rackmount1/UpdateService/FirmwareInventory/index.json",
        .text = @embedFile("payloads/software_inventory_collection.SoftwareInventoryCollection.json"),
    },
    .{
        .module = "software_inventory",
        .type_name = "SoftwareInventory",
        .source = "public-rackmount1/UpdateService/FirmwareInventory/BMC/index.json",
        .text = @embedFile("payloads/software_inventory.SoftwareInventory.json"),
    },
    .{
        .module = "storage_collection",
        .type_name = "StorageCollection",
        .source = "public-compose-action/Systems/BladeServer-1/Storage/index.json",
        .text = @embedFile("payloads/storage_collection.StorageCollection.json"),
    },
    .{
        .module = "storage_controller_collection",
        .type_name = "StorageControllerCollection",
        .source = "public-mpf/Systems/437XR1138R2/Storage/1/Controllers/index.json",
        .text = @embedFile("payloads/storage_controller_collection.StorageControllerCollection.json"),
    },
    .{
        .module = "storage_controller_metrics",
        .type_name = "StorageControllerMetrics",
        .source = "DSP2046-examples/StorageControllerMetrics-v1-example.json",
        .text = @embedFile("payloads/storage_controller_metrics.StorageControllerMetrics.json"),
    },
    .{
        .module = "storage_controller",
        .type_name = "StorageController",
        .source = "public-nvmeof-jbof/Storage/NVMeoF/Controllers/2/index.json",
        .text = @embedFile("payloads/storage_controller.StorageController.json"),
    },
    .{
        .module = "storage_metrics",
        .type_name = "StorageMetrics",
        .source = "DSP2046-examples/StorageMetrics-v1-example.json",
        .text = @embedFile("payloads/storage_metrics.StorageMetrics.json"),
    },
    .{
        .module = "storage",
        .type_name = "Storage",
        .source = "public-tower/Systems/437XR1238R2/Storage/RAIDIntegrated/index.json",
        .text = @embedFile("payloads/storage.Storage.json"),
    },
    .{
        .module = "switch_collection",
        .type_name = "SwitchCollection",
        .source = "public-sasfabric/Fabrics/SAS/Switches/index.json",
        .text = @embedFile("payloads/switch_collection.SwitchCollection.json"),
    },
    .{
        .module = "switch_metrics",
        .type_name = "SwitchMetrics",
        .source = "DSP2046-examples/SwitchMetrics-v1-example.json",
        .text = @embedFile("payloads/switch_metrics.SwitchMetrics.json"),
    },
    .{
        .module = "task_collection",
        .type_name = "TaskCollection",
        .source = "public-rackmount1/TaskService/Tasks/index.json",
        .text = @embedFile("payloads/task_collection.TaskCollection.json"),
    },
    .{
        .module = "task_service",
        .type_name = "TaskService",
        .source = "public-pmem-configuration/TaskService/index.json",
        .text = @embedFile("payloads/task_service.TaskService.json"),
    },
    .{
        .module = "task",
        .type_name = "Task",
        .source = "public-pmem-configuration/TaskService/TaskMonitors/1/index.json",
        .text = @embedFile("payloads/task.Task.json"),
    },
    .{
        .module = "telemetry_data_collection",
        .type_name = "TelemetryDataCollection",
        .source = "public-telemetry/TelemetryService/TelemetryData/index.json",
        .text = @embedFile("payloads/telemetry_data_collection.TelemetryDataCollection.json"),
    },
    .{
        .module = "telemetry_data",
        .type_name = "TelemetryData",
        .source = "public-telemetry/TelemetryService/TelemetryData/TelemetrySnapshot/index.json",
        .text = @embedFile("payloads/telemetry_data.TelemetryData.json"),
    },
    .{
        .module = "telemetry_service",
        .type_name = "TelemetryService",
        .source = "public-telemetry/TelemetryService/index.json",
        .text = @embedFile("payloads/telemetry_service.TelemetryService.json"),
    },
    .{
        .module = "thermal_equipment",
        .type_name = "ThermalEquipment",
        .source = "public-cooling-unit/ThermalEquipment/index.json",
        .text = @embedFile("payloads/thermal_equipment.ThermalEquipment.json"),
    },
    .{
        .module = "thermal_metrics",
        .type_name = "ThermalMetrics",
        .source = "DSP2046-examples/ThermalMetrics-v1-example.json",
        .text = @embedFile("payloads/thermal_metrics.ThermalMetrics.json"),
    },
    .{
        .module = "thermal_subsystem",
        .type_name = "ThermalSubsystem",
        .source = "public-rackmount1/Chassis/1U/ThermalSubsystem/index.json",
        .text = @embedFile("payloads/thermal_subsystem.ThermalSubsystem.json"),
    },
    .{
        .module = "thermal",
        .type_name = "Thermal",
        .source = "public-bladed/Chassis/MultiBladeEncl/Thermal/index.json",
        .text = @embedFile("payloads/thermal.Thermal.json"),
    },
    .{
        .module = "triggers_collection",
        .type_name = "TriggersCollection",
        .source = "public-telemetry/TelemetryService/Triggers/index.json",
        .text = @embedFile("payloads/triggers_collection.TriggersCollection.json"),
    },
    .{
        .module = "triggers",
        .type_name = "Triggers",
        .source = "public-telemetry/TelemetryService/Triggers/PlatformPowerCapTriggers/index.json",
        .text = @embedFile("payloads/triggers.Triggers.json"),
    },
    .{
        .module = "trusted_component_collection",
        .type_name = "TrustedComponentCollection",
        .source = "public-rackmount1/Chassis/1U/TrustedComponents/index.json",
        .text = @embedFile("payloads/trusted_component_collection.TrustedComponentCollection.json"),
    },
    .{
        .module = "trusted_component",
        .type_name = "TrustedComponent",
        .source = "public-rackmount1/Chassis/1U/TrustedComponents/AC-RoT0/index.json",
        .text = @embedFile("payloads/trusted_component.TrustedComponent.json"),
    },
    .{
        .module = "update_service_capabilities",
        .type_name = "UpdateServiceCapabilities",
        .source = "DSP2046-examples/UpdateServiceCapabilities-v1-example.json",
        .text = @embedFile("payloads/update_service_capabilities.UpdateServiceCapabilities.json"),
    },
    .{
        .module = "update_service",
        .type_name = "UpdateService",
        .source = "public-rackmount1/UpdateService/index.json",
        .text = @embedFile("payloads/update_service.UpdateService.json"),
    },
    .{
        .module = "usb_controller_collection",
        .type_name = "UsbControllerCollection",
        .source = "public-tower/Systems/437XR1238R2/USBControllers/index.json",
        .text = @embedFile("payloads/usb_controller_collection.UsbControllerCollection.json"),
    },
    .{
        .module = "usb_controller",
        .type_name = "UsbController",
        .source = "public-tower/Systems/437XR1238R2/USBControllers/USB2/index.json",
        .text = @embedFile("payloads/usb_controller.UsbController.json"),
    },
    .{
        .module = "vcat_entry",
        .type_name = "VcatEntry",
        .source = "DSP2046-examples/VCATEntry-v1-example.json",
        .text = @embedFile("payloads/vcat_entry.VcatEntry.json"),
    },
    .{
        .module = "virtual_cxl_switch_collection",
        .type_name = "VirtualCxlSwitchCollection",
        .source = "public-cxl-multiswitch/Fabrics/CXL/Switches/CXL1/VCSs/index.json",
        .text = @embedFile("payloads/virtual_cxl_switch_collection.VirtualCxlSwitchCollection.json"),
    },
    .{
        .module = "virtual_cxl_switch",
        .type_name = "VirtualCxlSwitch",
        .source = "public-cxl-multiswitch/Fabrics/CXL/Switches/CXL1/VCSs/1/index.json",
        .text = @embedFile("payloads/virtual_cxl_switch.VirtualCxlSwitch.json"),
    },
    .{
        .module = "virtual_media_collection",
        .type_name = "VirtualMediaCollection",
        .source = "public-rackmount1/Systems/437XR1138R2/VirtualMedia/index.json",
        .text = @embedFile("payloads/virtual_media_collection.VirtualMediaCollection.json"),
    },
    .{
        .module = "virtual_media",
        .type_name = "VirtualMedia",
        .source = "public-telemetry/Managers/1/VirtualMedia/CD1/index.json",
        .text = @embedFile("payloads/virtual_media.VirtualMedia.json"),
    },
    .{
        .module = "virtual_pci2pci_bridge_collection",
        .type_name = "VirtualPci2pciBridgeCollection",
        .source = "public-cxl-multiswitch/Fabrics/CXL/Switches/CXL1/VCSs/1/VPPBs/index.json",
        .text = @embedFile("payloads/virtual_pci2pci_bridge_collection.VirtualPci2pciBridgeCollection.json"),
    },
    .{
        .module = "virtual_pci2pci_bridge",
        .type_name = "VirtualPci2pciBridge",
        .source = "public-cxl/Fabrics/CXL/Switches/CXL/VCSs/2/VPPBs/2/index.json",
        .text = @embedFile("payloads/virtual_pci2pci_bridge.VirtualPci2pciBridge.json"),
    },
    .{
        .module = "vlan_network_interface_collection",
        .type_name = "VlanNetworkInterfaceCollection",
        .source = "public-mpf/Systems/437XR1138R2/EthernetInterfaces/12446A3B0411/VLANs/index.json",
        .text = @embedFile("payloads/vlan_network_interface_collection.VlanNetworkInterfaceCollection.json"),
    },
    .{
        .module = "vlan_network_interface",
        .type_name = "VlanNetworkInterface",
        .source = "public-mpf/Systems/437XR1138R2/EthernetInterfaces/12446A3B0411/VLANs/2/index.json",
        .text = @embedFile("payloads/vlan_network_interface.VlanNetworkInterface.json"),
    },
    .{
        .module = "volume_collection",
        .type_name = "VolumeCollection",
        .source = "public-mpf/Systems/437XR1138R2/Storage/1/Volumes/index.json",
        .text = @embedFile("payloads/volume_collection.VolumeCollection.json"),
    },
    .{
        .module = "volume",
        .type_name = "Volume",
        .source = "public-nvmeof-jbof/Storage/NVMeoF/Volumes/4/index.json",
        .text = @embedFile("payloads/volume.Volume.json"),
    },
    .{
        .module = "zone_collection",
        .type_name = "ZoneCollection",
        .source = "public-compose-action/CompositionService/ResourceZones/index.json",
        .text = @embedFile("payloads/zone_collection.ZoneCollection.json"),
    },
    .{
        .module = "zone",
        .type_name = "Zone",
        .source = "public-bladed-partitions/CompositionService/ResourceZones/EncZone1/index.json",
        .text = @embedFile("payloads/zone.Zone.json"),
    },
};
