//! Namespace `BootOption`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const computer_system = @import("computer_system.zig");
const resource = @import("resource.zig");

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The `BootOption` schema reports information about a single boot option in a system.  It represents the properties of a bootable device available in the system.
///
/// This resource shall represent a single boot option within a system.
pub const BootOption = struct {
    /// Where the resource lives.
    @"@odata.id": core.ODataId,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: resource.Id,
    Description: ?resource.Description = null,
    Name: resource.Name,
    /// The unique boot option.
    ///
    /// This property shall correspond to the boot option or device.  For UEFI systems, this string shall match the UEFI boot option variable name, such as `Boot####`.  The BootOrder array of a computer system resource contains this value.
    BootOptionReference: ?[]const u8 = null,
    /// The user-readable display name of the boot option that appears in the boot order list in the user interface.
    ///
    /// This property shall contain a user-readable boot option name, as it should appear in the boot order list in the user interface.
    DisplayName: ?[]const u8 = null,
    /// An indication of whether the boot option is enabled.  If `true`, it is enabled.  If `false`, the boot option that the boot order array on the computer system contains is skipped.  In the UEFI context, this property influences the load option active flag for the boot option.
    ///
    /// This property shall indicate whether the boot option is enabled.  If `true`, it is enabled.  If `false`, the boot option that the boot order array on the computer system contains shall be skipped.  In the UEFI context, this property shall influence the load option active flag for the boot option.
    BootOptionEnabled: ?bool = null,
    /// The UEFI device path to access this UEFI boot option.
    ///
    /// This property shall contain the UEFI Specification-defined UEFI device path that identifies and locates the device for this boot option.
    UefiDevicePath: ?[]const u8 = null,
    /// The alias of this boot source.
    ///
    /// This property shall contain the string alias of this boot source that describes the type of boot.
    Alias: ?computer_system.BootSource = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// An array of links to resources or objects associated with this boot option.
    ///
    /// This property shall contain an array of links to resources or objects that are associated with this boot option.
    RelatedItem: ?[]const core.NavProperty(resource.Item) = null,
};

/// What a client may change of `BootOption.BootOption`.
///
/// The `BootOption` schema reports information about a single boot option in a system.  It represents the properties of a bootable device available in the system.
pub const BootOptionUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// An indication of whether the boot option is enabled.  If `true`, it is enabled.  If `false`, the boot option that the boot order array on the computer system contains is skipped.  In the UEFI context, this property influences the load option active flag for the boot option.
    ///
    /// This property shall indicate whether the boot option is enabled.  If `true`, it is enabled.  If `false`, the boot option that the boot order array on the computer system contains shall be skipped.  In the UEFI context, this property shall influence the load option active flag for the boot option.
    BootOptionEnabled: core.Nullable(bool) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// What a client may supply when creating an instance of `BootOption.BootOption`.
///
/// The `BootOption` schema reports information about a single boot option in a system.  It represents the properties of a bootable device available in the system.
pub const BootOptionCreate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// An indication of whether the boot option is enabled.  If `true`, it is enabled.  If `false`, the boot option that the boot order array on the computer system contains is skipped.  In the UEFI context, this property influences the load option active flag for the boot option.
    ///
    /// This property shall indicate whether the boot option is enabled.  If `true`, it is enabled.  If `false`, the boot option that the boot order array on the computer system contains shall be skipped.  In the UEFI context, this property shall influence the load option active flag for the boot option.
    BootOptionEnabled: core.Nullable(bool) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
