//! Namespace `CertificateEnrollment`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const certificate = @import("certificate.zig");
const certificate_collection = @import("certificate_collection.zig");
const resource = @import("resource.zig");

pub const AcmeChallengeType = enum {
    /// HTTP challenge type for domain validation.
    ///
    /// This value shall indicate the RFC8555-defined http-01 challenge type for domain validation.
    Http01,
    /// DNS challenge type for domain validation.
    ///
    /// This value shall indicate the RFC8555-defined dns-01 challenge type for domain validation.
    Dns01,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const EnrollmentProtocolType = enum {
    /// Automatic Certificate Management Environment (ACME) protocol.
    ///
    /// This value shall indicate the enrollment uses the Automatic Certificate Management Environment (ACME) protocol as defined by RFC8555.
    ACME,
    /// Simple Certificate Enrollment Protocol (SCEP).
    ///
    /// This value shall indicate the enrollment uses the Simple Certificate Enrollment Protocol (SCEP) protocol as defined by RFC8894.
    SCEP,
    /// OEM enrollment protocol.
    ///
    /// This value shall indicate the OEM enrollment protocol type.
    OEM,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const LastOperationType = enum {
    /// Certificate renewal operation.
    Renew,
    /// Update ACME email operation.  Applicable only when the enrollment protocol is ACME.
    UpdateAcmeEmail,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const OperationStatus = enum {
    /// The operation completed successfully.
    Success,
    /// The operation failed.
    Failed,
    /// The operation is in progress.
    InProgress,
    /// The operation status is unknown.
    Unknown,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// ACME protocol specific configuration.
///
/// This type shall contain configuration specific to the ACME protocol.
pub const AcmeConfiguration = struct {
    /// The email address for ACME account registration.
    ///
    /// This property shall contain the email address used for ACME account registration and notifications.
    Email: ?[]const u8 = null,
    /// The ACME challenge type used for domain validation.
    ///
    /// This property shall contain the ACME challenge type used for domain validation during automatic certificate enrollment.
    ChallengeType: ?AcmeChallengeType = null,
};

/// What a client may change of `CertificateEnrollment.ACMEConfiguration`.
///
/// ACME protocol specific configuration.
pub const AcmeConfigurationUpdate = struct {
    /// The email address for ACME account registration.
    ///
    /// This property shall contain the email address used for ACME account registration and notifications.
    Email: core.Nullable([]const u8) = .absent,
    /// The external account binding (EAB) key identifier.
    ///
    /// This property shall contain the external account binding (EAB) key identifier used for ACME account registration with certificate authorities that require EAB.  This property shall be `null` in responses.
    EABKeyId: core.Nullable([]const u8) = .absent,
    /// The external account binding (EAB) key value.
    ///
    /// This property shall contain a Base64-encoded string, with padding characters, of the external account binding (EAB) key value used for ACME account registration with certificate authorities that require EAB.  This property shall be `null` in responses.
    EABKey: core.Nullable([]const u8) = .absent,
    /// The ACME challenge type used for domain validation.
    ///
    /// This property shall contain the ACME challenge type used for domain validation during automatic certificate enrollment.
    ChallengeType: core.Nullable(AcmeChallengeType) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
};

/// Certificate signing request parameters.
///
/// This type shall contain the parameters for generating a certificate signing request.
pub const CsrParameters = struct {
    /// The name of the component to secure.
    ///
    /// This property shall contain the of the component to secure, as defined by the RFC5280 'commonName' attribute.
    CommonName: ?[]const u8 = null,
    /// The additional host names of the component to secure.
    ///
    /// This property shall contain an array of additional host names of the component to secure, as defined by the RFC5280 'subjectAltName' attribute.
    AlternativeNames: ?[]const ?[]const u8 = null,
    /// The name of the organization making the request.
    ///
    /// This property shall contain the name of the organization making the request, as defined by the RFC5280 'organizationName' attribute.
    Organization: ?[]const u8 = null,
    /// The name of the unit or division of the organization making the request.
    ///
    /// This property shall contain the name of the unit or division of the organization making the request, as defined by the RFC5280 'organizationalUnitName' attribute.
    OrganizationalUnit: ?[]const u8 = null,
    /// The city or locality of the organization making the request.
    ///
    /// This property shall contain the city or locality of the organization making the request, as defined by the RFC5280 'localityName' attribute.
    City: ?[]const u8 = null,
    /// The state, province, or region of the organization making the request.
    ///
    /// This property shall contain the state, province, or region of the organization making the request, as defined by the RFC5280 'stateOrProvinceName' attribute.
    State: ?[]const u8 = null,
    /// The two-letter country code of the organization making the request.
    ///
    /// This property shall contain the two-letter ISO code for the country of the organization making the request, as defined by the RFC5280 'countryName' attribute.
    Country: ?[]const u8 = null,
    /// The email address of the contact within the organization making the request.
    ///
    /// This property shall contain the email address of the contact within the organization making the request, as defined by the RFC2985 'emailAddress' attribute.
    Email: ?[]const u8 = null,
    /// The type of key-pair for use with signing algorithms.
    ///
    /// This property shall contain the type of key-pair for use with signing algorithms.  The allowable values for this property shall be the strings in the 'Algorithm Name' field of the 'TPM_ALG_ID Constants' table within the 'Trusted Computing Group Algorithm Registry'.
    KeyPairAlgorithm: ?[]const u8 = null,
    /// The length of the key, in bits, if needed based on the `KeyPairAlgorithm` property value.
    ///
    /// This property shall contain the length of the key, in bits, if needed based on the `KeyPairAlgorithm` property value.
    KeyBitLength: ?i64 = null,
    /// The curve ID to use with the key, if needed based on the `KeyPairAlgorithm` property value.
    ///
    /// This property shall contain the curve ID to use with the key, if needed based on the `KeyPairAlgorithm` property value.  The allowable values for this property shall be the strings in the 'Name' field of the 'TPM_ECC_CURVE Constants' table within the 'Trusted Computing Group Algorithm Registry'.
    KeyCurveId: ?[]const u8 = null,
    /// The usage of the key contained in the certificate.
    ///
    /// This property shall contain the usage of the key contained in the certificate.  If the client does not provide this value, the service can determine the appropriate key usage settings in the certificate signing request.
    KeyUsage: ?[]const ?certificate.KeyUsage = null,
    /// The surname of the user making the request.
    ///
    /// This property shall contain the surname of the user making the request, as defined by the RFC5280 'surname' attribute.
    Surname: ?[]const u8 = null,
    /// The given name of the user making the request.
    ///
    /// This property shall contain the given name of the user making the request, as defined by the RFC5280 'givenName' attribute.
    GivenName: ?[]const u8 = null,
    /// The initials of the user making the request.
    ///
    /// This property shall contain the initials of the user making the request, as defined by the RFC5280 'initials' attribute.
    Initials: ?[]const u8 = null,
    /// The challenge password to apply to the certificate for revocation requests.
    ///
    /// This property shall contain the challenge password to apply to the certificate for revocation requests as defined by the RFC2985 'challengePassword' attribute.
    ChallengePassword: ?[]const u8 = null,
    /// The unstructured name of the subject.
    ///
    /// This property shall contain the unstructured name of the subject, as defined by the RFC2985 'unstructuredName' attribute.
    UnstructuredName: ?[]const u8 = null,
    /// The name of the user making the request.
    ///
    /// This property shall contain the name of the user making the request, as defined by the RFC5280 'name' attribute.
    ContactPerson: ?[]const u8 = null,
};

/// What a client may change of `CertificateEnrollment.CSRParameters`.
///
/// Certificate signing request parameters.
pub const CsrParametersUpdate = struct {
    /// The name of the component to secure.
    ///
    /// This property shall contain the of the component to secure, as defined by the RFC5280 'commonName' attribute.
    CommonName: ?[]const u8 = null,
    /// The additional host names of the component to secure.
    ///
    /// This property shall contain an array of additional host names of the component to secure, as defined by the RFC5280 'subjectAltName' attribute.
    AlternativeNames: ?[]const ?[]const u8 = null,
    /// The name of the organization making the request.
    ///
    /// This property shall contain the name of the organization making the request, as defined by the RFC5280 'organizationName' attribute.
    Organization: core.Nullable([]const u8) = .absent,
    /// The name of the unit or division of the organization making the request.
    ///
    /// This property shall contain the name of the unit or division of the organization making the request, as defined by the RFC5280 'organizationalUnitName' attribute.
    OrganizationalUnit: core.Nullable([]const u8) = .absent,
    /// The city or locality of the organization making the request.
    ///
    /// This property shall contain the city or locality of the organization making the request, as defined by the RFC5280 'localityName' attribute.
    City: core.Nullable([]const u8) = .absent,
    /// The state, province, or region of the organization making the request.
    ///
    /// This property shall contain the state, province, or region of the organization making the request, as defined by the RFC5280 'stateOrProvinceName' attribute.
    State: core.Nullable([]const u8) = .absent,
    /// The two-letter country code of the organization making the request.
    ///
    /// This property shall contain the two-letter ISO code for the country of the organization making the request, as defined by the RFC5280 'countryName' attribute.
    Country: core.Nullable([]const u8) = .absent,
    /// The email address of the contact within the organization making the request.
    ///
    /// This property shall contain the email address of the contact within the organization making the request, as defined by the RFC2985 'emailAddress' attribute.
    Email: core.Nullable([]const u8) = .absent,
    /// The type of key-pair for use with signing algorithms.
    ///
    /// This property shall contain the type of key-pair for use with signing algorithms.  The allowable values for this property shall be the strings in the 'Algorithm Name' field of the 'TPM_ALG_ID Constants' table within the 'Trusted Computing Group Algorithm Registry'.
    KeyPairAlgorithm: core.Nullable([]const u8) = .absent,
    /// The length of the key, in bits, if needed based on the `KeyPairAlgorithm` property value.
    ///
    /// This property shall contain the length of the key, in bits, if needed based on the `KeyPairAlgorithm` property value.
    KeyBitLength: core.Nullable(i64) = .absent,
    /// The curve ID to use with the key, if needed based on the `KeyPairAlgorithm` property value.
    ///
    /// This property shall contain the curve ID to use with the key, if needed based on the `KeyPairAlgorithm` property value.  The allowable values for this property shall be the strings in the 'Name' field of the 'TPM_ECC_CURVE Constants' table within the 'Trusted Computing Group Algorithm Registry'.
    KeyCurveId: core.Nullable([]const u8) = .absent,
    /// The usage of the key contained in the certificate.
    ///
    /// This property shall contain the usage of the key contained in the certificate.  If the client does not provide this value, the service can determine the appropriate key usage settings in the certificate signing request.
    KeyUsage: ?[]const ?certificate.KeyUsage = null,
    /// The surname of the user making the request.
    ///
    /// This property shall contain the surname of the user making the request, as defined by the RFC5280 'surname' attribute.
    Surname: core.Nullable([]const u8) = .absent,
    /// The given name of the user making the request.
    ///
    /// This property shall contain the given name of the user making the request, as defined by the RFC5280 'givenName' attribute.
    GivenName: core.Nullable([]const u8) = .absent,
    /// The initials of the user making the request.
    ///
    /// This property shall contain the initials of the user making the request, as defined by the RFC5280 'initials' attribute.
    Initials: core.Nullable([]const u8) = .absent,
    /// The challenge password to apply to the certificate for revocation requests.
    ///
    /// This property shall contain the challenge password to apply to the certificate for revocation requests as defined by the RFC2985 'challengePassword' attribute.
    ChallengePassword: core.Nullable([]const u8) = .absent,
    /// The unstructured name of the subject.
    ///
    /// This property shall contain the unstructured name of the subject, as defined by the RFC2985 'unstructuredName' attribute.
    UnstructuredName: core.Nullable([]const u8) = .absent,
    /// The name of the user making the request.
    ///
    /// This property shall contain the name of the user making the request, as defined by the RFC5280 'name' attribute.
    ContactPerson: core.Nullable([]const u8) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The status information for an enrollment.
///
/// This type shall contain the status information for an enrollment including the last operation performed and its status.
pub const EnrollmentState = struct {
    /// The last operation performed by the automatic enrollment service.
    ///
    /// This property shall contain the last operation performed by the automatic enrollment service.
    LastOperation: ?LastOperationType = null,
    /// The date and time when the last operation was performed.
    ///
    /// This property shall contain the date and time when the last operation was performed by the automatic enrollment service.
    LastOperationTime: ?core.DateTimeOffset = null,
    /// The status of the last operation performed by automatic enrollment service.
    ///
    /// This enumeration shall describe the status of the last operation performed by automatic enrollment service.
    LastOperationStatus: ?OperationStatus = null,
};

/// The links to other resources that are related to this resource.
///
/// This Redfish Specification-described type shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
pub const Links = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// The link to the certificate collection where the enrolled certificate will be installed.
    ///
    /// This property shall contain a link to a resource collection of type `CertificateCollection` where the enrolled certificate will be installed.
    EnrolledCertificateLocation: ?core.NavProperty(certificate_collection.CertificateCollection) = null,
    /// The link to the enrolled certificate.
    ///
    /// This property shall contain a link to the enrolled certificate.
    EnrolledCertificate: ?core.NavProperty(certificate.Certificate) = null,
    /// The list of server certificates for the server referenced by the `ServerURI` property.
    ///
    /// The list of references to server certificates for the server referenced by the `ServerURI` property.  Members of this array shall reference members the `EnrollmentCACertificates` property in the `CertificateService` resource.  If `VerifyCertificate` contains `true` and this property is present, services shall compare the certificates in this list with the certificate obtained during handshaking with the enrollment server in order to verify the identity of the enrollment server.  If `VerifyCertificate` contains `true` and this property is absent, services shall compare the certificates in the `EnrollmentCACertificates` property in the `CertificateService` resource with the certificate obtained during handshaking with the enrollment server.  If the server cannot be verified, the service shall fail the automatic certificate enrollment.  If `VerifyCertificate` is `false`, the service shall not perform certificate verification.  Regardless of the contents of this list and the `EnrollmentCACertificates` property in the `CertificateService` resource, services may perform additional verification based on other factors, such as the configuration of the `SecurityPolicy` resource.
    CACertificates: ?[]const core.NavProperty(certificate.Certificate) = null,
    /// How many members `CACertificates` has in total, which is not how many this response carries.
    @"CACertificates@odata.count": ?i64 = null,
    /// The next page of `CACertificates`. Present only when this response left members out.
    @"CACertificates@odata.nextLink": ?core.ODataId = null,
};

/// What a client may change of `CertificateEnrollment.Links`.
///
/// The links to other resources that are related to this resource.
pub const LinksUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// SCEP protocol specific configuration.
///
/// This type shall contain configuration specific to the SCEP protocol.
pub const ScepConfiguration = struct {};

/// What a client may change of `CertificateEnrollment.SCEPConfiguration`.
///
/// SCEP protocol specific configuration.
pub const ScepConfigurationUpdate = struct {
    /// The challenge password for SCEP enrollment.
    ///
    /// This property shall contain the challenge password used for SCEP enrollment.  This property shall be `null` in responses.
    ChallengePassword: core.Nullable([]const u8) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// This resource shall represent an automatic certificate enrollment for a Redfish implementation.
///
/// The `CertificateEnrollment` schema describes an automatic certificate enrollment for a specific protocol such as ACME (Automatic Certificate Management Environment) or SCEP (Simple Certificate Enrollment Protocol).
pub const CertificateEnrollment = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: ?resource.Id = null,
    Description: ?resource.Description = null,
    Name: ?resource.Name = null,
    /// The configured automatic certificate enrollment protocol.
    ///
    /// This property shall contain the configured automatic certificate enrollment protocol.
    EnrollmentType: ?EnrollmentProtocolType = null,
    /// An indication of whether this automatic certificate enrollment is enabled.
    ///
    /// This property shall indicate whether this automatic certificate enrollment is enabled.  If `true`, the implementation shall automatically enroll and renew certificates according to the configuration.  If `false`, the implementation shall not perform automatic certificate enrollment operations.  If this property is not specified by the client in the create request, it shall be assumed to be `false`.
    Enabled: ?bool = null,
    /// The URI of the certificate enrollment server.
    ///
    /// This property shall contain the URI of the certificate enrollment server that provides the automatic enrollment service.
    ServerURI: ?[]const u8 = null,
    /// An indication of whether the service will verify the certificate of the server referenced by the `ServerURI` property.
    ///
    /// This property shall indicate whether the service will verify the certificate of the server referenced by the `ServerURI` property with the certificates found in the collection referenced by the `Certificates` property.  If this property is not supported by the service or specified by the client in the create request, it shall be assumed to be `false`.  Regardless of the value of this property, services may perform additional verification based on other factors, such as the configuration of the `SecurityPolicy` resource.
    VerifyCertificate: ?bool = null,
    /// The number of days before certificate expiry to begin automatic renewal of the certificate.
    ///
    /// This property shall contain the number of days before certificate expiry to begin automatic renewal of the certificate.
    RenewBeforeExpiryDays: ?i64 = null,
    /// ACME (Automatic Certificate Management Environment) protocol specific configuration for automatic certificate enrollment.
    ///
    /// This property shall contain configuration specific to the ACME protocol.  This property shall only be present when the `EnrollmentType` property contains `ACME`.
    ACME: ?AcmeConfiguration = null,
    /// SCEP (Simple Certificate Enrollment Protocol) protocol specific configuration for automatic certificate enrollment.
    ///
    /// This property shall contain configuration specific to the SCEP protocol.  This property shall only be present when the `EnrollmentType` property contains `SCEP`.
    SCEP: ?ScepConfiguration = null,
    /// The certificate signing request parameters.
    ///
    /// This property shall contain the parameters used for generating the certificate signing request.
    CSRParameters: ?CsrParameters = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?Links = null,
    /// The status information for this enrollment.
    ///
    /// This property shall contain the status information for this enrollment including the last operation performed and its status.
    EnrollmentState: ?EnrollmentState = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
};

/// What a client may change of `CertificateEnrollment.CertificateEnrollment`.
///
/// This resource shall represent an automatic certificate enrollment for a Redfish implementation.
pub const CertificateEnrollmentUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// An indication of whether this automatic certificate enrollment is enabled.
    ///
    /// This property shall indicate whether this automatic certificate enrollment is enabled.  If `true`, the implementation shall automatically enroll and renew certificates according to the configuration.  If `false`, the implementation shall not perform automatic certificate enrollment operations.  If this property is not specified by the client in the create request, it shall be assumed to be `false`.
    Enabled: ?bool = null,
    /// The URI of the certificate enrollment server.
    ///
    /// This property shall contain the URI of the certificate enrollment server that provides the automatic enrollment service.
    ServerURI: ?[]const u8 = null,
    /// An indication of whether the service will verify the certificate of the server referenced by the `ServerURI` property.
    ///
    /// This property shall indicate whether the service will verify the certificate of the server referenced by the `ServerURI` property with the certificates found in the collection referenced by the `Certificates` property.  If this property is not supported by the service or specified by the client in the create request, it shall be assumed to be `false`.  Regardless of the value of this property, services may perform additional verification based on other factors, such as the configuration of the `SecurityPolicy` resource.
    VerifyCertificate: core.Nullable(bool) = .absent,
    /// The number of days before certificate expiry to begin automatic renewal of the certificate.
    ///
    /// This property shall contain the number of days before certificate expiry to begin automatic renewal of the certificate.
    RenewBeforeExpiryDays: core.Nullable(i64) = .absent,
    /// ACME (Automatic Certificate Management Environment) protocol specific configuration for automatic certificate enrollment.
    ///
    /// This property shall contain configuration specific to the ACME protocol.  This property shall only be present when the `EnrollmentType` property contains `ACME`.
    ACME: core.Nullable(AcmeConfigurationUpdate) = .absent,
    /// SCEP (Simple Certificate Enrollment Protocol) protocol specific configuration for automatic certificate enrollment.
    ///
    /// This property shall contain configuration specific to the SCEP protocol.  This property shall only be present when the `EnrollmentType` property contains `SCEP`.
    SCEP: core.Nullable(ScepConfigurationUpdate) = .absent,
    /// The certificate signing request parameters.
    ///
    /// This property shall contain the parameters used for generating the certificate signing request.
    CSRParameters: core.Nullable(CsrParametersUpdate) = .absent,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?LinksUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// What a client may supply when creating an instance of `CertificateEnrollment.CertificateEnrollment`.
///
/// This resource shall represent an automatic certificate enrollment for a Redfish implementation.
pub const CertificateEnrollmentCreate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The configured automatic certificate enrollment protocol.
    ///
    /// This property shall contain the configured automatic certificate enrollment protocol.
    EnrollmentType: EnrollmentProtocolType,
    /// An indication of whether this automatic certificate enrollment is enabled.
    ///
    /// This property shall indicate whether this automatic certificate enrollment is enabled.  If `true`, the implementation shall automatically enroll and renew certificates according to the configuration.  If `false`, the implementation shall not perform automatic certificate enrollment operations.  If this property is not specified by the client in the create request, it shall be assumed to be `false`.
    Enabled: ?bool = null,
    /// The URI of the certificate enrollment server.
    ///
    /// This property shall contain the URI of the certificate enrollment server that provides the automatic enrollment service.
    ServerURI: []const u8,
    /// An indication of whether the service will verify the certificate of the server referenced by the `ServerURI` property.
    ///
    /// This property shall indicate whether the service will verify the certificate of the server referenced by the `ServerURI` property with the certificates found in the collection referenced by the `Certificates` property.  If this property is not supported by the service or specified by the client in the create request, it shall be assumed to be `false`.  Regardless of the value of this property, services may perform additional verification based on other factors, such as the configuration of the `SecurityPolicy` resource.
    VerifyCertificate: core.Nullable(bool) = .absent,
    /// The number of days before certificate expiry to begin automatic renewal of the certificate.
    ///
    /// This property shall contain the number of days before certificate expiry to begin automatic renewal of the certificate.
    RenewBeforeExpiryDays: core.Nullable(i64) = .absent,
    /// ACME (Automatic Certificate Management Environment) protocol specific configuration for automatic certificate enrollment.
    ///
    /// This property shall contain configuration specific to the ACME protocol.  This property shall only be present when the `EnrollmentType` property contains `ACME`.
    ACME: core.Nullable(AcmeConfigurationUpdate) = .absent,
    /// SCEP (Simple Certificate Enrollment Protocol) protocol specific configuration for automatic certificate enrollment.
    ///
    /// This property shall contain configuration specific to the SCEP protocol.  This property shall only be present when the `EnrollmentType` property contains `SCEP`.
    SCEP: core.Nullable(ScepConfigurationUpdate) = .absent,
    /// The certificate signing request parameters.
    ///
    /// This property shall contain the parameters used for generating the certificate signing request.
    CSRParameters: core.Nullable(CsrParametersUpdate) = .absent,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?LinksUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
