//! Namespace `Chassis`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const assembly = @import("assembly.zig");
const automation_node = @import("automation_node.zig");
const cable = @import("cable.zig");
const certificate_collection = @import("certificate_collection.zig");
const computer_system = @import("computer_system.zig");
const control_collection = @import("control_collection.zig");
const cooling_loop = @import("cooling_loop.zig");
const cooling_unit = @import("cooling_unit.zig");
const drive = @import("drive.zig");
const drive_collection = @import("drive_collection.zig");
const environment_metrics = @import("environment_metrics.zig");
const fabric_adapter_collection = @import("fabric_adapter_collection.zig");
const facility = @import("facility.zig");
const fan = @import("fan.zig");
const leak_detector_collection = @import("leak_detector_collection.zig");
const log_service_collection = @import("log_service_collection.zig");
const manager = @import("manager.zig");
const media_controller_collection = @import("media_controller_collection.zig");
const memory_collection = @import("memory_collection.zig");
const memory_domain_collection = @import("memory_domain_collection.zig");
const network_adapter_collection = @import("network_adapter_collection.zig");
const outlet = @import("outlet.zig");
const pcie_device = @import("pcie_device.zig");
const pcie_device_collection = @import("pcie_device_collection.zig");
const pcie_slots = @import("pcie_slots.zig");
const power = @import("power.zig");
const power_distribution = @import("power_distribution.zig");
const power_subsystem = @import("power_subsystem.zig");
const power_supply = @import("power_supply.zig");
const processor = @import("processor.zig");
const processor_collection = @import("processor_collection.zig");
const resource = @import("resource.zig");
const resource_block = @import("resource_block.zig");
const sensor_collection = @import("sensor_collection.zig");
const settings = @import("settings.zig");
const software_inventory = @import("software_inventory.zig");
const storage = @import("storage.zig");
const @"switch" = @import("switch.zig");
const thermal = @import("thermal.zig");
const thermal_subsystem = @import("thermal_subsystem.zig");
const trusted_component_collection = @import("trusted_component_collection.zig");

pub const ChassisType = enum {
    /// An equipment rack, typically a 19-inch wide freestanding unit.
    Rack,
    /// An enclosed or semi-enclosed, typically vertically-oriented, system chassis that must be plugged into a multi-system chassis to function normally.
    Blade,
    /// A generic term for a chassis that does not fit any other description.
    Enclosure,
    /// A single, free-standing system, commonly called a tower or desktop chassis.
    StandAlone,
    /// A single-system chassis designed specifically for mounting in an equipment rack.
    RackMount,
    /// A loose device or circuit board intended to be installed in a system or other enclosure.
    Card,
    /// A small self-contained system intended to be plugged into a multi-system chassis.
    Cartridge,
    /// A collection of equipment racks.
    Row,
    /// A collection of equipment racks in a large, likely transportable, container.
    Pod,
    /// A chassis that expands the capabilities or capacity of another chassis.
    Expansion,
    /// A chassis that mates mechanically with another chassis to expand its capabilities or capacity.
    Sidecar,
    /// A logical division or portion of a physical chassis that contains multiple devices or systems that cannot be physically separated.
    Zone,
    /// An enclosed or semi-enclosed, system chassis that must be plugged into a multi-system chassis to function normally similar to a blade type chassis.
    Sled,
    /// An enclosed or semi-enclosed, typically horizontally-oriented, system chassis that must be plugged into a multi-system chassis to function normally.
    Shelf,
    /// An enclosed or semi-enclosed, typically horizontally-oriented, system chassis that can be slid into a multi-system chassis.
    Drawer,
    /// A small, typically removable, chassis or card that contains devices for a particular subsystem or function.
    Module,
    /// A small chassis, card, or device that contains devices for a particular subsystem or function.
    Component,
    /// A chassis in a drive form factor with IP-based network connections.
    IPBasedDrive,
    /// A group of racks that form a single entity or share infrastructure.
    RackGroup,
    /// A chassis that encloses storage.
    StorageEnclosure,
    /// An immersion cooling tank.
    ImmersionTank,
    /// A heat exchanger.
    HeatExchanger,
    /// A power strip, typically placed in the zero-U space of a rack.
    PowerStrip,
    /// A chassis that does not fit any of these definitions.
    Other,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const DoorState = enum {
    /// Door is closed and locked.
    ///
    /// This value shall indicate that the door is both closed and locked.  In this state, the door cannot be opened unless the value of the `Locked` property is set to `false`.
    Locked,
    /// Door is closed.
    ///
    /// This value shall indicate that the door is closed but unlocked.
    Closed,
    /// Door is open and locked.
    ///
    /// This value shall indicate that the door is open but the lock has been engaged.  It may be possible to close the door while in this state.
    LockedAndOpen,
    /// Door is open.
    ///
    /// This value shall indicate that the door is open.
    Open,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const EnvironmentalClass = enum {
    /// ASHRAE Environmental Class 'A1'.
    A1,
    /// ASHRAE Environmental Class 'A2'.
    A2,
    /// ASHRAE Environmental Class 'A3'.
    A3,
    /// ASHRAE Environmental Class 'A4'.
    A4,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const IndicatorLed = enum {
    /// The state of the indicator LED cannot be determined.
    ///
    /// This value shall represent the indicator LED is in an unknown state.  The service shall reject `PATCH` or `PUT` requests containing this value by returning the HTTP `400 Bad Request` status code.
    ///
    /// Deprecated in v1_2_0.
    /// This value has been deprecated in favor of returning `null` if the state is unknown.
    Unknown,
    /// The indicator LED is lit.
    ///
    /// This value shall represent the indicator LED is in a solid on state.  If the service does not support this value, it shall return the HTTP `400 Bad Request` status code to reject `PATCH` or `PUT` requests that contain this value.
    Lit,
    /// The indicator LED is blinking.
    ///
    /// This value shall represent the indicator LED is in a blinking state where the LED is being turned on and off in repetition.  If the service does not support this value, it shall reject `PATCH` or `PUT` requests containing this value by returning the HTTP `400 Bad Request` status code.
    Blinking,
    /// The indicator LED is off.
    ///
    /// This value shall represent the indicator LED is in a solid off state.  If the service does not support this value, it shall reject `PATCH` or `PUT` requests containing this value by returning the HTTP `400 Bad Request` status code.
    Off,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const IntrusionSensor = enum {
    /// No physical security condition is detected at this time.
    Normal,
    /// A door, lock, or other mechanism protecting the internal system hardware from being accessed is detected to be in an insecure state.
    HardwareIntrusion,
    /// Physical tampering of the monitored entity is detected.
    TamperingDetected,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const IntrusionSensorReArm = enum {
    /// A user is required to clear the sensor to restore it to the normal state.
    ///
    /// This value shall indicate a user is required to set the `IntrusionSensor` property to `Normal` to restore the sensor to its normal state.
    Manual,
    /// The sensor is automatically restored to the normal state when no security condition is detected.
    ///
    /// This value shall indicate the service sets the `IntrusionSensor` property to `Normal` when no security condition is detected.
    Automatic,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const RackMountWidth = enum {
    /// Open Rack (21.0 in or 533.4 mm).
    ///
    /// Rack mounting width and mounting hole spacing shall conform to the Open Rack standard for 21-inch racks.
    OpenU,
    /// EIA-310 19-inch.
    ///
    /// Rack mounting width and mounting hole spacing shall conform to the EIA-310 standard for 19-inch racks.
    EIA_310,
    /// EIA-310 23-inch (Telco).
    ///
    /// Rack mounting width and mounting hole spacing shall conform to the EIA-310 standard for 23-inch telecommunications equipment racks.
    EIA_310_Telco,
    /// Half-width (~9.5 in) Unit.
    ///
    /// Rack mounting width and mounting hole spacing shall be approximately 9.5 inches in width, following de facto industry practice for a rack half the width of a 19-inch EIA-310 equipment racks.
    HalfWidth,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const RackUnits = enum {
    /// An Open Rack rack unit (48 mm or 1.89 in).
    ///
    /// Rack units shall be specified in terms of the Open Compute Open Rack Specification.
    OpenU,
    /// An EIA-310 rack unit (1.75 in or 44.45 mm).
    ///
    /// Rack units shall conform to the EIA-310 standard.
    EIA_310,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const ThermalDirection = enum {
    /// A chassis with the air intake in the front and exhaust out the back.
    ///
    /// This value shall indicate a chassis with the air intake generally from the front of the chassis and the air exhaust out the back of the chassis.
    FrontToBack,
    /// A chassis with the air intake in the back and exhaust out the front.
    ///
    /// This value shall indicate a chassis with the air intake generally from the back of the chassis and the air exhaust out the front of the chassis.
    BackToFront,
    /// A chassis with air exhaust on the top.
    ///
    /// This value shall indicate a chassis with the air exhaust out the top of the chassis.
    TopExhaust,
    /// A sealed chassis with no air pathway.
    ///
    /// This value shall indicate a sealed chassis with no air pathway through the chassis.
    Sealed,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// Arguments to `Chassis.Reset`.
///
/// This action resets the chassis.  Additionally, it could reset systems or other contained resources depending on the `ResetType` used to invoke this action.
pub const ChassisResetAction = struct {
    /// The type of reset.
    ///
    /// This parameter shall contain the type of reset.  The service can accept a request without the parameter and complete an implementation-specific default reset.  Services should include the `@Redfish.AllowableValues` annotation for this parameter to ensure compatibility with clients, even when `ActionInfo` has been implemented.
    ResetType: ?resource.ResetType = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
    /// This action resets the chassis.  Additionally, it could reset systems or other contained resources depending on the `ResetType` used to invoke this action.
    ///
    /// This action shall reset the chassis.  Additionally, it may reset systems or other contained resources depending on the `ResetType` used to invoke this action.
    @"#Chassis.Reset": ?core.Action(ChassisResetAction, std.json.Value) = null,

    /// This action resets the chassis.  Additionally, it could reset systems or other contained resources depending on the `ResetType` used to invoke this action.
    ///
    /// This action shall reset the chassis.  Additionally, it may reset systems or other contained resources depending on the `ResetType` used to invoke this action.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn reset(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ChassisResetAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#Chassis.Reset" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }
};

/// A door or access panel on the chassis.
///
/// This type shall describe a door or access panel on the chassis.
pub const Door = struct {
    /// The state of the door.
    ///
    /// This property shall contain the current state of the door.
    DoorState: ?DoorState = null,
    /// Indicates if the door is locked.
    ///
    /// This property shall indicate if the door is locked.
    Locked: ?bool = null,
    /// A user-assigned label.
    ///
    /// This property shall contain a user-assigned label used to identify this resource.  If a value has not been assigned by a user, the value of this property shall be an empty string.
    UserLabel: ?[]const u8 = null,
};

/// What a client may change of `Chassis.Door`.
///
/// A door or access panel on the chassis.
pub const DoorUpdate = struct {
    /// Indicates if the door is locked.
    ///
    /// This property shall indicate if the door is locked.
    Locked: core.Nullable(bool) = .absent,
    /// A user-assigned label.
    ///
    /// This property shall contain a user-assigned label used to identify this resource.  If a value has not been assigned by a user, the value of this property shall be an empty string.
    UserLabel: ?[]const u8 = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The doors or access panels of the chassis.
///
/// This type shall describe the doors or access panels of the chassis.
pub const Doors = struct {
    /// The front door of the chassis.
    ///
    /// This property shall contain information related to the front door, as defined by the manufacturer, of the chassis.
    Front: ?Door = null,
    /// The rear door of the chassis.
    ///
    /// This property shall contain information related to the rear door, as defined by the manufacturer, of the chassis.
    Rear: ?Door = null,
};

/// What a client may change of `Chassis.Doors`.
///
/// The doors or access panels of the chassis.
pub const DoorsUpdate = struct {
    /// The front door of the chassis.
    ///
    /// This property shall contain information related to the front door, as defined by the manufacturer, of the chassis.
    Front: core.Nullable(DoorUpdate) = .absent,
    /// The rear door of the chassis.
    ///
    /// This property shall contain information related to the rear door, as defined by the manufacturer, of the chassis.
    Rear: core.Nullable(DoorUpdate) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

pub const Links = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// An array of links to the computer systems that this chassis directly and wholly contains.
    ///
    /// This property shall contain an array of links to resources of type `ComputerSystem` with which this physical container is associated.  If a chassis also links to a computer system to which this resource also links, this chassis shall not link to that computer system.
    ComputerSystems: ?[]const core.NavProperty(computer_system.ComputerSystem) = null,
    /// How many members `ComputerSystems` has in total, which is not how many this response carries.
    @"ComputerSystems@odata.count": ?i64 = null,
    /// The next page of `ComputerSystems`. Present only when this response left members out.
    @"ComputerSystems@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the managers responsible for managing this chassis.
    ///
    /// This property shall contain an array of links to resources of type `Manager` that manage this chassis.
    ManagedBy: ?[]const core.NavProperty(manager.Manager) = null,
    /// How many members `ManagedBy` has in total, which is not how many this response carries.
    @"ManagedBy@odata.count": ?i64 = null,
    /// The next page of `ManagedBy`. Present only when this response left members out.
    @"ManagedBy@odata.nextLink": ?core.ODataId = null,
    /// The link to the chassis that contains this chassis.
    ///
    /// This property shall contain a link to a resource of type `Chassis` that represents the chassis that contains this chassis.
    ContainedBy: ?core.NavProperty(Chassis) = null,
    /// An array of links to any other chassis that this chassis has in it.
    ///
    /// This property shall contain an array of links to resources of type `Chassis` that represent the chassis instances that this chassis contains.
    Contains: ?[]const core.NavProperty(Chassis) = null,
    /// How many members `Contains` has in total, which is not how many this response carries.
    @"Contains@odata.count": ?i64 = null,
    /// The next page of `Contains`. Present only when this response left members out.
    @"Contains@odata.nextLink": ?core.ODataId = null,
    /// An array of links to resources or objects that power this chassis.  Normally, the link is for either a chassis or a specific set of power supplies.
    ///
    /// This property shall contain an array of links to resources or objects that power this chassis.
    ///
    /// Deprecated in v1_20_0.
    /// This property has been deprecated in favor of the `PowerOutlets` and `PowerSupplies` link properties, and details provided in the `PowerSubsystem` resource.
    PoweredBy: ?[]const core.NavProperty(resource.Item) = null,
    /// How many members `PoweredBy` has in total, which is not how many this response carries.
    @"PoweredBy@odata.count": ?i64 = null,
    /// The next page of `PoweredBy`. Present only when this response left members out.
    @"PoweredBy@odata.nextLink": ?core.ODataId = null,
    /// An array of links to resources or objects that cool this chassis.  Normally, the link is for either a chassis or a specific set of fans.
    ///
    /// This property shall contain an array of links to resources or objects that cool this chassis.
    ///
    /// Deprecated in v1_20_0.
    /// This property has been deprecated in favor of the `Fans` link property, and details provided in the `ThermalSubsystem` resource.
    CooledBy: ?[]const core.NavProperty(resource.Item) = null,
    /// How many members `CooledBy` has in total, which is not how many this response carries.
    @"CooledBy@odata.count": ?i64 = null,
    /// The next page of `CooledBy`. Present only when this response left members out.
    @"CooledBy@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the managers located in this chassis.
    ///
    /// This property shall contain an array of links to resources of type `Manager` that are in this chassis.
    ManagersInChassis: ?[]const core.NavProperty(manager.Manager) = null,
    /// How many members `ManagersInChassis` has in total, which is not how many this response carries.
    @"ManagersInChassis@odata.count": ?i64 = null,
    /// The next page of `ManagersInChassis`. Present only when this response left members out.
    @"ManagersInChassis@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the drives located in this chassis.
    ///
    /// This property shall contain an array of links to resources of type `Drive` that are in this chassis.
    Drives: ?[]const core.NavProperty(drive.Drive) = null,
    /// How many members `Drives` has in total, which is not how many this response carries.
    @"Drives@odata.count": ?i64 = null,
    /// The next page of `Drives`. Present only when this response left members out.
    @"Drives@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the storage subsystems connected to or inside this chassis.
    ///
    /// This property shall contain an array of links to resources of type `Storage` that are connected to or contained in this chassis.
    Storage: ?[]const core.NavProperty(storage.Storage) = null,
    /// How many members `Storage` has in total, which is not how many this response carries.
    @"Storage@odata.count": ?i64 = null,
    /// The next page of `Storage`. Present only when this response left members out.
    @"Storage@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the PCIe devices located in this chassis.
    ///
    /// This property shall contain an array of links to resources of type `PCIeDevice`.
    ///
    /// Deprecated in v1_10_0.
    /// This property has been deprecated in favor of the `PCIeDevices` resource collection in the root of this resource.
    PCIeDevices: ?[]const core.NavProperty(pcie_device.PcieDevice) = null,
    /// How many members `PCIeDevices` has in total, which is not how many this response carries.
    @"PCIeDevices@odata.count": ?i64 = null,
    /// The next page of `PCIeDevices`. Present only when this response left members out.
    @"PCIeDevices@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the resource blocks located in this chassis.
    ///
    /// This property shall contain an array of links to resources of type `ResourceBlock` that this chassis contains.
    ResourceBlocks: ?[]const core.NavProperty(resource_block.ResourceBlock) = null,
    /// How many members `ResourceBlocks` has in total, which is not how many this response carries.
    @"ResourceBlocks@odata.count": ?i64 = null,
    /// The next page of `ResourceBlocks`. Present only when this response left members out.
    @"ResourceBlocks@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the switches located in this chassis.
    ///
    /// This property shall contain an array of links to resources of type `Switch` that this chassis contains.
    Switches: ?[]const core.NavProperty(@"switch".Switch) = null,
    /// How many members `Switches` has in total, which is not how many this response carries.
    @"Switches@odata.count": ?i64 = null,
    /// The next page of `Switches`. Present only when this response left members out.
    @"Switches@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the processors located in this chassis.
    ///
    /// This property shall contain an array of links to resources of type `Processor` type that this chassis contains.
    Processors: ?[]const core.NavProperty(processor.Processor) = null,
    /// How many members `Processors` has in total, which is not how many this response carries.
    @"Processors@odata.count": ?i64 = null,
    /// The next page of `Processors`. Present only when this response left members out.
    @"Processors@odata.nextLink": ?core.ODataId = null,
    /// The link to the facility that contains this chassis.
    ///
    /// This property shall contain a link to the resource of type `Facility` and shall represent the smallest facility that contains this chassis.  This property shall not appear in resources that include a `ContainedBy` property within the `Links` property.
    Facility: ?core.NavProperty(facility.Facility) = null,
    /// An array of links to the cables connected to this chassis.
    ///
    /// This property shall contain an array of links to resources of type `Cable` that represent the cables connected to this chassis.
    Cables: ?[]const core.NavProperty(cable.Cable) = null,
    /// How many members `Cables` has in total, which is not how many this response carries.
    @"Cables@odata.count": ?i64 = null,
    /// The next page of `Cables`. Present only when this response left members out.
    @"Cables@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the outlets that provide power to this chassis.
    ///
    /// This property shall contain an array of links to resources of type `Outlet` that represent the outlets that provide power to this chassis.  This property shall not be present if the `PoweredByParent` property contains `true`.
    PowerOutlets: ?[]const core.NavProperty(outlet.Outlet) = null,
    /// How many members `PowerOutlets` has in total, which is not how many this response carries.
    @"PowerOutlets@odata.count": ?i64 = null,
    /// The next page of `PowerOutlets`. Present only when this response left members out.
    @"PowerOutlets@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the power supplies that provide power to this chassis.
    ///
    /// This property shall contain an array of links to resources of type `PowerSupply` that represent the power supplies that provide power to this chassis.  This property shall not be present if the `PoweredByParent` property contains `true` or if the power supplies are contained in the `PowerSubsystem` resource for this chassis.
    PowerSupplies: ?[]const core.NavProperty(power_supply.PowerSupply) = null,
    /// How many members `PowerSupplies` has in total, which is not how many this response carries.
    @"PowerSupplies@odata.count": ?i64 = null,
    /// The next page of `PowerSupplies`. Present only when this response left members out.
    @"PowerSupplies@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the fans that cool this chassis.
    ///
    /// This property shall contain an array of links to resources of type `Fan` that represent the fans that provide cooling to this chassis.  This property shall not be present if the `ThermalManagedByParent` property contains `true` or if the fans are contained in the `ThermalSubsystem` resource for this chassis.
    Fans: ?[]const core.NavProperty(fan.Fan) = null,
    /// How many members `Fans` has in total, which is not how many this response carries.
    @"Fans@odata.count": ?i64 = null,
    /// The next page of `Fans`. Present only when this response left members out.
    @"Fans@odata.nextLink": ?core.ODataId = null,
    /// A link to power distribution functionality contained in this chassis.
    ///
    /// This property shall contain a link to a resource of type `PowerDistribution` that represents the power distribution functionality contained within this chassis.
    PowerDistribution: ?core.NavProperty(power_distribution.PowerDistribution) = null,
    /// An array of links to cooling unit functionality contained in this chassis.
    ///
    /// This property shall contain an array of links to resources of type `CoolingUnit` that represent the cooling unit functionality contained within this chassis.
    CoolingUnits: ?[]const core.NavProperty(cooling_unit.CoolingUnit) = null,
    /// How many members `CoolingUnits` has in total, which is not how many this response carries.
    @"CoolingUnits@odata.count": ?i64 = null,
    /// The next page of `CoolingUnits`. Present only when this response left members out.
    @"CoolingUnits@odata.nextLink": ?core.ODataId = null,
    /// An array of links to cooling loops connected to this chassis.
    ///
    /// This property shall contain an array of links to resources of type `CoolingLoop` that represent the cooling loops connected to this chassis.
    ConnectedCoolingLoops: ?[]const core.NavProperty(cooling_loop.CoolingLoop) = null,
    /// How many members `ConnectedCoolingLoops` has in total, which is not how many this response carries.
    @"ConnectedCoolingLoops@odata.count": ?i64 = null,
    /// The next page of `ConnectedCoolingLoops`. Present only when this response left members out.
    @"ConnectedCoolingLoops@odata.nextLink": ?core.ODataId = null,
    /// An array of links to the automation nodes contained in this chassis.
    ///
    /// This property shall contain an array of links to resources of type `AutomationNode` with which this physical container is associated.
    AutomationNodes: ?[]const core.NavProperty(automation_node.AutomationNode) = null,
    /// How many members `AutomationNodes` has in total, which is not how many this response carries.
    @"AutomationNodes@odata.count": ?i64 = null,
    /// The next page of `AutomationNodes`. Present only when this response left members out.
    @"AutomationNodes@odata.nextLink": ?core.ODataId = null,
};

/// What a client may change of `Chassis.Links`.
pub const LinksUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The physical security state of the chassis.
///
/// This type shall describe the physical security state of the chassis.
pub const PhysicalSecurity = struct {
    /// A numerical identifier to represent the physical security sensor.
    ///
    /// This property shall contain a numerical identifier for this physical security sensor that is unique within this resource.
    ///
    /// Deprecated in v1_22_0.
    /// This property has been deprecated in order to allow for multiple physical sensors to construct this object.
    IntrusionSensorNumber: ?i64 = null,
    /// The physical security state of the chassis, such as if hardware intrusion is detected.
    ///
    /// This property shall contain the physical security state of the chassis.  If the `IntrusionSensorReArm` property contains `Manual`, a client may set this property to `Normal` to reset the physical security state.
    IntrusionSensor: ?IntrusionSensor = null,
    /// The policy that describes how the physical security state of the chassis returns to a normal state.
    ///
    /// This property shall contain the policy that describes how the `IntrusionSensor` property returns to the `Normal` value.
    IntrusionSensorReArm: ?IntrusionSensorReArm = null,
};

/// What a client may change of `Chassis.PhysicalSecurity`.
///
/// The physical security state of the chassis.
pub const PhysicalSecurityUpdate = struct {
    /// The physical security state of the chassis, such as if hardware intrusion is detected.
    ///
    /// This property shall contain the physical security state of the chassis.  If the `IntrusionSensorReArm` property contains `Manual`, a client may set this property to `Normal` to reset the physical security state.
    IntrusionSensor: core.Nullable(IntrusionSensor) = .absent,
    /// The policy that describes how the physical security state of the chassis returns to a normal state.
    ///
    /// This property shall contain the policy that describes how the `IntrusionSensor` property returns to the `Normal` value.
    IntrusionSensorReArm: core.Nullable(IntrusionSensorReArm) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The `Chassis` schema represents the physical components of a system.  This resource represents the sheet-metal confined spaces and logical zones such as racks, enclosures, chassis and all other containers.  Subsystems, such as sensors, that operate outside of a system's data plane are linked either directly or indirectly through this resource.  A subsystem that operates outside of a system's data plane are not accessible to software that runs on the system.  It also describes the location, such as a slot, socket, or bay, where a unit can be installed, by populating a resource instance with an absent state if a unit is not present.
///
/// This resource shall represent a chassis or other physical enclosure for a Redfish implementation.  It may also represent a location, such as a slot, socket, or bay, where a unit may be installed, but the `State` property within the `Status` property contains `Absent`.
pub const Chassis = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The pending settings for this resource. PATCH `SettingsObject` rather than the resource itself; the service applies the result on the schedule this names.
    @"@Redfish.Settings": ?settings.Settings = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: ?resource.Id = null,
    Description: ?resource.Description = null,
    Name: ?resource.Name = null,
    /// The type of physical form factor of the chassis.
    ///
    /// This property shall indicate the physical form factor for the type of chassis.
    ChassisType: ?ChassisType = null,
    /// The manufacturer of this chassis.
    ///
    /// This property shall contain the name of the organization responsible for producing the chassis.  This organization may be the entity from whom the chassis is purchased, but this is not necessarily true.
    Manufacturer: ?[]const u8 = null,
    /// The model number of the chassis.
    ///
    /// This property shall contain the name by which the manufacturer generally refers to the chassis.
    Model: ?[]const u8 = null,
    /// The SKU of the chassis.
    ///
    /// This property shall contain the stock-keeping unit number for this chassis.
    SKU: ?[]const u8 = null,
    /// The serial number of the chassis.
    ///
    /// This property shall contain a manufacturer-allocated number that identifies the chassis.
    SerialNumber: ?[]const u8 = null,
    /// The part number of the chassis.
    ///
    /// This property shall contain a part number assigned by the organization that is responsible for producing or manufacturing the chassis.
    PartNumber: ?[]const u8 = null,
    /// The user-assigned asset tag of this chassis.
    ///
    /// This property shall contain an identifying string that tracks the chassis for inventory purposes.  Modifying this property may modify the `AssetTag` in the resource that represents the functional view of this chassis, such as a `ComputerSystem` resource.
    AssetTag: ?[]const u8 = null,
    /// The state of the indicator LED, which identifies the chassis.
    ///
    /// This property shall contain the indicator light state for the indicator light associated with this system.
    ///
    /// Deprecated in v1_14_0.
    /// This property has been deprecated in favor of the `LocationIndicatorActive` property.
    IndicatorLED: ?IndicatorLed = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?Links = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// The status and health of the resource and its subordinate or dependent resources.
    ///
    /// This property shall contain any status or health properties of the resource.
    Status: ?resource.Status = null,
    /// The current power state of the chassis.
    ///
    /// This property shall contain the power state of the chassis.
    PowerState: ?resource.PowerState = null,
    /// The physical security state of the chassis.
    ///
    /// This property shall contain the physical security state of the chassis.  Services may construct this state from multiple physical sensors.
    PhysicalSecurity: ?PhysicalSecurity = null,
    /// The location of the chassis.
    ///
    /// This property shall contain the location information of the associated chassis.
    Location: ?resource.Location = null,
    /// The height of the chassis.
    ///
    /// This property shall represent the height of the chassis, in millimeter units, as specified by the manufacturer.
    HeightMm: ?core.Decimal = null,
    /// The width of the chassis.
    ///
    /// This property shall represent the width of the chassis, in millimeter units, as specified by the manufacturer.
    WidthMm: ?core.Decimal = null,
    /// The depth of the chassis.
    ///
    /// This property shall represent the depth (length) of the chassis, in millimeter units, as specified by the manufacturer.
    DepthMm: ?core.Decimal = null,
    /// The weight of the chassis.
    ///
    /// This property shall represent the published mass, commonly referred to as weight, of the chassis, in kilogram units.
    WeightKg: ?core.Decimal = null,
    /// The UUID for this chassis.
    ///
    /// This property shall contain the universally unique identifier number for this chassis.
    UUID: ?resource.Uuid = null,
    /// The ASHRAE Environmental Class for this chassis.
    ///
    /// This property shall contain the ASHRAE Environmental Class for this chassis, as defined by ASHRAE Thermal Guidelines for Data Processing Environments.  These classes define respective environmental limits that include temperature, relative humidity, dew point, and maximum allowable elevation.
    EnvironmentalClass: ?EnvironmentalClass = null,
    /// The upper bound of the total power consumed by the chassis.
    ///
    /// This property shall contain the upper bound of the total power consumed by the chassis.
    MaxPowerWatts: ?core.Decimal = null,
    /// The lower bound of the total power consumed by the chassis.
    ///
    /// This property shall contain the lower bound of the total power consumed by the chassis.
    MinPowerWatts: ?core.Decimal = null,
    /// An indicator allowing an operator to physically locate this resource.
    ///
    /// This property shall contain the state of the indicator used to physically identify or locate this resource.  A write to this property shall update the value of `IndicatorLED` in this resource, if supported, to reflect the implementation of the locating function.  Modifying this property may modify the `LocationIndicatorActive` in the resource that represents the functional view of this chassis, such as a `ComputerSystem` resource.
    LocationIndicatorActive: ?bool = null,
    /// An array of DSP0274-defined measurement blocks.
    ///
    /// This property shall contain an array of DSP0274-defined measurement blocks.
    ///
    /// Deprecated in v1_19_0.
    /// This property has been deprecated in favor of the `ComponentIntegrity` resource.
    Measurements: ?[]const software_inventory.MeasurementBlock = null,
    /// The spare part number of the chassis.
    ///
    /// This property shall contain the spare part number of the chassis.
    SparePartNumber: ?[]const u8 = null,
    /// The URIs of the management interfaces for the external electrical source connections for this chassis.
    ///
    /// This property shall contain an array of URIs to the management applications or devices that provide monitoring or control of the external electrical sources that provide power to this chassis.
    ElectricalSourceManagerURIs: ?[]const ?[]const u8 = null,
    /// The names of the external electrical sources, such as circuits or outlets, connected to this chassis.
    ///
    /// This property shall contain an array of strings that identify the external electrical sources, such as the names of circuits or outlets, that provide power to this chassis.
    ElectricalSourceNames: ?[]const ?[]const u8 = null,
    /// Indicates that the chassis receives power from the containing chassis.
    ///
    /// This property shall indicate whether the chassis receives power from the chassis that contains it.  The value `true` shall indicate that the containing chassis provides power.  The value `false` shall indicate the chassis receives power from its own power subsystem, another chassis instance's power supplies, or outlets.
    PoweredByParent: ?bool = null,
    /// Indicates that the chassis is thermally managed by the parent chassis.
    ///
    /// This property shall indicate whether the chassis relies on the containing chassis to provide thermal management.  The value `true` shall indicate that the chassis relies on the containing chassis to provide thermal management.  The value `false` shall indicate the chassis provides thermal management, and may provide details in a `ThermalSubsystem` resource, or by populating the `Fans` property in Links.
    ThermalManagedByParent: ?bool = null,
    /// Indicates the thermal management path through the chassis.
    ///
    /// This property shall indicate the general direction of the thermal management path through the chassis.
    ThermalDirection: ?ThermalDirection = null,
    /// The hardware version of this chassis.
    ///
    /// This property shall contain the hardware version of this chassis as determined by the vendor or supplier.
    Version: ?[]const u8 = null,
    /// An indication of whether this component can be inserted or removed while the equipment is in operation.
    ///
    /// This property shall indicate whether the component can be inserted or removed while the underlying equipment otherwise remains in its current operational state.  Components indicated as hot-pluggable shall allow the component to become operable without altering the operational state of the underlying equipment.  Components that cannot be inserted or removed from equipment in operation, or components that cannot become operable without affecting the operational state of that equipment, shall be indicated as not hot-pluggable.
    HotPluggable: ?bool = null,
    /// An indication of whether this component can be independently replaced as allowed by the vendor's replacement policy.
    ///
    /// This property shall indicate whether this component can be independently replaced as allowed by the vendor's replacement policy.  A value of `false` indicates the component needs to be replaced by policy as part of another component.  If the `LocationType` property of this component contains `Embedded`, this property shall contain `false`.
    Replaceable: ?bool = null,
    /// The doors or access panels of the chassis.
    ///
    /// This property shall contain information about the doors or access panels of the chassis.
    Doors: ?Doors = null,
    /// The URIs of the management interfaces for the external heating or cooling equipment for this chassis.
    ///
    /// This property shall contain an array of URIs to the management applications or devices that provide monitoring or control of the external heating or cooling equipment that provide thermal management for this chassis.
    HeatingCoolingManagerURIs: ?[]const ?[]const u8 = null,
    /// The names of the external heating or cooling equipment, such as coolant distribution units, connected to this chassis.
    ///
    /// This property shall contain an array of strings that identify the external heating or cooling equipment, such as the names of specific coolant distribution units, that provide thermal management for this chassis.
    HeatingCoolingEquipmentNames: ?[]const ?[]const u8 = null,
    /// An indication of whether the chassis is prepared by the system for removal.
    ///
    /// This property shall indicate whether the chassis is ready for removal.  Setting the value to `true` shall cause the service to perform appropriate actions to quiesce the device.  A task may spawn while the device is quiescing.
    ReadyToRemove: ?bool = null,
    /// The usable capacity of rack units provided by this chassis.
    ///
    /// This property shall contain the amount of space, in `RackUnits` and including fractional units, contained within this chassis that are usable to hold rack-mountable equipment.  This property shall not be present if `ChassisType` does not contain `Rack`.
    RackMountCapacityUnits: ?core.Decimal = null,
    /// The type of rack-mount units.
    ///
    /// This property shall contain the type of units used to describe rack-mountable equipment.
    RackUnits: ?RackUnits = null,
    /// The width of the rack-mountable chassis or rack-mounting space.
    ///
    /// This property shall contain the type of width that describes the rack-mountable equipment space.
    RackMountWidth: ?RackMountWidth = null,
    /// The usable depth of the rack-mountable area of the chassis.
    ///
    /// This property shall represent the depth (length) of the chassis, in millimeter units, that is available to contain rack-mounted equipment.
    RackMountDepthMm: ?core.Decimal = null,
    /// The height of the rack-mountable chassis in rack units.
    ///
    /// This property shall contain the height of the rack-mountable chassis, in rack units specified by the value of `RackUnits`.
    HeightRackUnits: ?core.Decimal = null,
    /// The link to the logs for this chassis.
    ///
    /// This property shall contain a link to a resource collection of type `LogServiceCollection`.
    LogServices: ?core.NavProperty(log_service_collection.LogServiceCollection) = null,
    /// The link to the thermal properties, such as fans, cooling, and sensors, for this chassis.
    ///
    /// This property shall contain a link to a resource of type `Thermal` that represents the thermal characteristics of this chassis.
    ///
    /// Deprecated in v1_15_0.
    /// This link has been deprecated in favor of the `ThermalSubsystem` link property.
    Thermal: ?core.NavProperty(thermal.Thermal) = null,
    /// The link to the power properties, or power supplies, power policies, and sensors, for this chassis.
    ///
    /// This property shall contain a link to a resource of type `Power` that represents the power characteristics of this chassis.
    ///
    /// Deprecated in v1_15_0.
    /// This link has been deprecated in favor of the `PowerSubsystem` link property.
    Power: ?core.NavProperty(power.Power) = null,
    /// The link to the collection of network adapters associated with this chassis.
    ///
    /// This property shall contain a link to a resource collection of type `NetworkAdapterCollection`.
    NetworkAdapters: ?core.NavProperty(network_adapter_collection.NetworkAdapterCollection) = null,
    /// The link to the assembly associated with this chassis.
    ///
    /// This property shall contain a link to a resource of type `Assembly`.
    Assembly: ?core.NavProperty(assembly.Assembly) = null,
    /// The link to the PCIe slot properties for this chassis.
    ///
    /// This property shall contain a link to the resource of type `PCIeSlots` that represents the PCIe slot information for this chassis.
    ///
    /// Deprecated in v1_24_0.
    /// This property has been deprecated in favor of the `PCIeDevices` property.  The `PCIeSlots` schema has been deprecated in favor of the `PCIeDevice` schema.  Empty PCIe slots are represented by `PCIeDevice` resources using the `Absent` value of the `State` property within `Status`.
    PCIeSlots: ?core.NavProperty(pcie_slots.PcieSlots) = null,
    /// The link to the collection of sensors located in the equipment and sub-components.
    ///
    /// This property shall contain a link to a resource collection of type `SensorCollection` that contains the sensors located in the chassis and sub-components.
    Sensors: ?core.NavProperty(sensor_collection.SensorCollection) = null,
    /// The link to the collection of PCIe devices located in this chassis.
    ///
    /// This property shall contain a link to a resource collection of type `PCIeDeviceCollection`.
    PCIeDevices: ?core.NavProperty(pcie_device_collection.PcieDeviceCollection) = null,
    /// The link to the collection of media controllers located in this chassis.
    ///
    /// This property shall contain a link to a resource collection of type `MediaControllerCollection`.
    ///
    /// Deprecated in v1_20_0.
    /// This property has been deprecated in favor of `FabricAdapters`.
    MediaControllers: ?core.NavProperty(media_controller_collection.MediaControllerCollection) = null,
    /// The link to the collection of memory located in this chassis that belong to fabric-related resource pools.
    ///
    /// This property shall contain a link to a resource collection of type `MemoryCollection` that represents memory in this chassis that belong to fabric-related resource pools.
    Memory: ?core.NavProperty(memory_collection.MemoryCollection) = null,
    /// The link to the collection of memory domains located in this chassis that belong to fabric-related resource pools.
    ///
    /// This property shall contain a link to a resource collection of type `MemoryDomainCollection` that represents memory domains in this chassis that belong to fabric-related resource pools.
    MemoryDomains: ?core.NavProperty(memory_domain_collection.MemoryDomainCollection) = null,
    /// The link to the collection of drives within this chassis.
    ///
    /// This property shall contain a link to a resource collection of type `DriveCollection`.
    Drives: ?core.NavProperty(drive_collection.DriveCollection) = null,
    /// The link to the power subsystem properties for this chassis.
    ///
    /// This property shall contain a link to a resource of type `PowerSubsystem` that represents the power subsystem information for this chassis.
    PowerSubsystem: ?core.NavProperty(power_subsystem.PowerSubsystem) = null,
    /// The link to the thermal subsystem properties for this chassis.
    ///
    /// This property shall contain a link to a resource of type `ThermalSubsystem` that represents the thermal subsystem information for this chassis.
    ThermalSubsystem: ?core.NavProperty(thermal_subsystem.ThermalSubsystem) = null,
    /// The link to the environment metrics for this chassis.
    ///
    /// This property shall contain a link to a resource of type `EnvironmentMetrics` that specifies the environment metrics for this chassis, all containing chassis, and devices contained by any of these chassis instances.  When determining power and energy readings, care should be taken to ensure any reported values do not overlap or result in double-counting.
    EnvironmentMetrics: ?core.NavProperty(environment_metrics.EnvironmentMetrics) = null,
    /// The link to a collection of certificates for device identity and attestation.
    ///
    /// This property shall contain a link to a resource collection of type `CertificateCollection` that contains certificates for device identity and attestation.
    Certificates: ?core.NavProperty(certificate_collection.CertificateCollection) = null,
    /// The link to the collection of controls located in this chassis.
    ///
    /// This property shall contain a link to a resource collection of type `ControlCollection`.
    Controls: ?core.NavProperty(control_collection.ControlCollection) = null,
    /// The link to the collection of fabric adapters located in this chassis that provide access to fabric-related resource pools.
    ///
    /// This property shall contain a link to a resource collection of type `FabricAdapterCollection` that represents fabric adapters in this chassis that provide access to fabric-related resource pools.
    FabricAdapters: ?core.NavProperty(fabric_adapter_collection.FabricAdapterCollection) = null,
    /// The link to the trusted components in this chassis.
    ///
    /// This property shall contain a link to a resource collection of type `TrustedComponentCollection`.
    TrustedComponents: ?core.NavProperty(trusted_component_collection.TrustedComponentCollection) = null,
    /// The link to the collection of processors located in this chassis that belong to fabric-related resource pools.
    ///
    /// This property shall contain a link to a resource collection of type `ProcessorCollection` that represents processors in this chassis that belong to fabric-related resource pools.
    Processors: ?core.NavProperty(processor_collection.ProcessorCollection) = null,
    /// The link to the collection of leak detectors located in this chassis.
    ///
    /// This property shall contain a link to a resource collection of type `LeakDetectorCollection`.
    LeakDetectors: ?core.NavProperty(leak_detector_collection.LeakDetectorCollection) = null,

    const closed = core.ClosedStruct(@This());
    pub const jsonParse = closed.jsonParse;
    pub const jsonParseFromValue = closed.jsonParseFromValue;
};

/// What a client may change of `Chassis.Chassis`.
///
/// The `Chassis` schema represents the physical components of a system.  This resource represents the sheet-metal confined spaces and logical zones such as racks, enclosures, chassis and all other containers.  Subsystems, such as sensors, that operate outside of a system's data plane are linked either directly or indirectly through this resource.  A subsystem that operates outside of a system's data plane are not accessible to software that runs on the system.  It also describes the location, such as a slot, socket, or bay, where a unit can be installed, by populating a resource instance with an absent state if a unit is not present.
pub const ChassisUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The user-assigned asset tag of this chassis.
    ///
    /// This property shall contain an identifying string that tracks the chassis for inventory purposes.  Modifying this property may modify the `AssetTag` in the resource that represents the functional view of this chassis, such as a `ComputerSystem` resource.
    AssetTag: core.Nullable([]const u8) = .absent,
    /// The state of the indicator LED, which identifies the chassis.
    ///
    /// This property shall contain the indicator light state for the indicator light associated with this system.
    ///
    /// Deprecated in v1_14_0.
    /// This property has been deprecated in favor of the `LocationIndicatorActive` property.
    IndicatorLED: core.Nullable(IndicatorLed) = .absent,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?LinksUpdate = null,
    /// The physical security state of the chassis.
    ///
    /// This property shall contain the physical security state of the chassis.  Services may construct this state from multiple physical sensors.
    PhysicalSecurity: ?PhysicalSecurityUpdate = null,
    /// The location of the chassis.
    ///
    /// This property shall contain the location information of the associated chassis.
    Location: ?resource.LocationUpdate = null,
    /// The ASHRAE Environmental Class for this chassis.
    ///
    /// This property shall contain the ASHRAE Environmental Class for this chassis, as defined by ASHRAE Thermal Guidelines for Data Processing Environments.  These classes define respective environmental limits that include temperature, relative humidity, dew point, and maximum allowable elevation.
    EnvironmentalClass: core.Nullable(EnvironmentalClass) = .absent,
    /// An indicator allowing an operator to physically locate this resource.
    ///
    /// This property shall contain the state of the indicator used to physically identify or locate this resource.  A write to this property shall update the value of `IndicatorLED` in this resource, if supported, to reflect the implementation of the locating function.  Modifying this property may modify the `LocationIndicatorActive` in the resource that represents the functional view of this chassis, such as a `ComputerSystem` resource.
    LocationIndicatorActive: core.Nullable(bool) = .absent,
    /// The URIs of the management interfaces for the external electrical source connections for this chassis.
    ///
    /// This property shall contain an array of URIs to the management applications or devices that provide monitoring or control of the external electrical sources that provide power to this chassis.
    ElectricalSourceManagerURIs: ?[]const ?[]const u8 = null,
    /// The names of the external electrical sources, such as circuits or outlets, connected to this chassis.
    ///
    /// This property shall contain an array of strings that identify the external electrical sources, such as the names of circuits or outlets, that provide power to this chassis.
    ElectricalSourceNames: ?[]const ?[]const u8 = null,
    /// The doors or access panels of the chassis.
    ///
    /// This property shall contain information about the doors or access panels of the chassis.
    Doors: ?DoorsUpdate = null,
    /// The URIs of the management interfaces for the external heating or cooling equipment for this chassis.
    ///
    /// This property shall contain an array of URIs to the management applications or devices that provide monitoring or control of the external heating or cooling equipment that provide thermal management for this chassis.
    HeatingCoolingManagerURIs: ?[]const ?[]const u8 = null,
    /// The names of the external heating or cooling equipment, such as coolant distribution units, connected to this chassis.
    ///
    /// This property shall contain an array of strings that identify the external heating or cooling equipment, such as the names of specific coolant distribution units, that provide thermal management for this chassis.
    HeatingCoolingEquipmentNames: ?[]const ?[]const u8 = null,
    /// An indication of whether the chassis is prepared by the system for removal.
    ///
    /// This property shall indicate whether the chassis is ready for removal.  Setting the value to `true` shall cause the service to perform appropriate actions to quiesce the device.  A task may spawn while the device is quiescing.
    ReadyToRemove: core.Nullable(bool) = .absent,
    /// The usable capacity of rack units provided by this chassis.
    ///
    /// This property shall contain the amount of space, in `RackUnits` and including fractional units, contained within this chassis that are usable to hold rack-mountable equipment.  This property shall not be present if `ChassisType` does not contain `Rack`.
    RackMountCapacityUnits: core.Nullable(core.Decimal) = .absent,
    /// The type of rack-mount units.
    ///
    /// This property shall contain the type of units used to describe rack-mountable equipment.
    RackUnits: core.Nullable(RackUnits) = .absent,
    /// The width of the rack-mountable chassis or rack-mounting space.
    ///
    /// This property shall contain the type of width that describes the rack-mountable equipment space.
    RackMountWidth: core.Nullable(RackMountWidth) = .absent,
    /// The usable depth of the rack-mountable area of the chassis.
    ///
    /// This property shall represent the depth (length) of the chassis, in millimeter units, that is available to contain rack-mounted equipment.
    RackMountDepthMm: core.Nullable(core.Decimal) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// What a client may supply when creating an instance of `Chassis.Chassis`.
///
/// The `Chassis` schema represents the physical components of a system.  This resource represents the sheet-metal confined spaces and logical zones such as racks, enclosures, chassis and all other containers.  Subsystems, such as sensors, that operate outside of a system's data plane are linked either directly or indirectly through this resource.  A subsystem that operates outside of a system's data plane are not accessible to software that runs on the system.  It also describes the location, such as a slot, socket, or bay, where a unit can be installed, by populating a resource instance with an absent state if a unit is not present.
pub const ChassisCreate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The user-assigned asset tag of this chassis.
    ///
    /// This property shall contain an identifying string that tracks the chassis for inventory purposes.  Modifying this property may modify the `AssetTag` in the resource that represents the functional view of this chassis, such as a `ComputerSystem` resource.
    AssetTag: core.Nullable([]const u8) = .absent,
    /// The state of the indicator LED, which identifies the chassis.
    ///
    /// This property shall contain the indicator light state for the indicator light associated with this system.
    ///
    /// Deprecated in v1_14_0.
    /// This property has been deprecated in favor of the `LocationIndicatorActive` property.
    IndicatorLED: core.Nullable(IndicatorLed) = .absent,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?LinksUpdate = null,
    /// The physical security state of the chassis.
    ///
    /// This property shall contain the physical security state of the chassis.  Services may construct this state from multiple physical sensors.
    PhysicalSecurity: ?PhysicalSecurityUpdate = null,
    /// The location of the chassis.
    ///
    /// This property shall contain the location information of the associated chassis.
    Location: ?resource.LocationUpdate = null,
    /// The ASHRAE Environmental Class for this chassis.
    ///
    /// This property shall contain the ASHRAE Environmental Class for this chassis, as defined by ASHRAE Thermal Guidelines for Data Processing Environments.  These classes define respective environmental limits that include temperature, relative humidity, dew point, and maximum allowable elevation.
    EnvironmentalClass: core.Nullable(EnvironmentalClass) = .absent,
    /// An indicator allowing an operator to physically locate this resource.
    ///
    /// This property shall contain the state of the indicator used to physically identify or locate this resource.  A write to this property shall update the value of `IndicatorLED` in this resource, if supported, to reflect the implementation of the locating function.  Modifying this property may modify the `LocationIndicatorActive` in the resource that represents the functional view of this chassis, such as a `ComputerSystem` resource.
    LocationIndicatorActive: core.Nullable(bool) = .absent,
    /// The URIs of the management interfaces for the external electrical source connections for this chassis.
    ///
    /// This property shall contain an array of URIs to the management applications or devices that provide monitoring or control of the external electrical sources that provide power to this chassis.
    ElectricalSourceManagerURIs: ?[]const ?[]const u8 = null,
    /// The names of the external electrical sources, such as circuits or outlets, connected to this chassis.
    ///
    /// This property shall contain an array of strings that identify the external electrical sources, such as the names of circuits or outlets, that provide power to this chassis.
    ElectricalSourceNames: ?[]const ?[]const u8 = null,
    /// The doors or access panels of the chassis.
    ///
    /// This property shall contain information about the doors or access panels of the chassis.
    Doors: ?DoorsUpdate = null,
    /// The URIs of the management interfaces for the external heating or cooling equipment for this chassis.
    ///
    /// This property shall contain an array of URIs to the management applications or devices that provide monitoring or control of the external heating or cooling equipment that provide thermal management for this chassis.
    HeatingCoolingManagerURIs: ?[]const ?[]const u8 = null,
    /// The names of the external heating or cooling equipment, such as coolant distribution units, connected to this chassis.
    ///
    /// This property shall contain an array of strings that identify the external heating or cooling equipment, such as the names of specific coolant distribution units, that provide thermal management for this chassis.
    HeatingCoolingEquipmentNames: ?[]const ?[]const u8 = null,
    /// An indication of whether the chassis is prepared by the system for removal.
    ///
    /// This property shall indicate whether the chassis is ready for removal.  Setting the value to `true` shall cause the service to perform appropriate actions to quiesce the device.  A task may spawn while the device is quiescing.
    ReadyToRemove: core.Nullable(bool) = .absent,
    /// The usable capacity of rack units provided by this chassis.
    ///
    /// This property shall contain the amount of space, in `RackUnits` and including fractional units, contained within this chassis that are usable to hold rack-mountable equipment.  This property shall not be present if `ChassisType` does not contain `Rack`.
    RackMountCapacityUnits: core.Nullable(core.Decimal) = .absent,
    /// The type of rack-mount units.
    ///
    /// This property shall contain the type of units used to describe rack-mountable equipment.
    RackUnits: core.Nullable(RackUnits) = .absent,
    /// The width of the rack-mountable chassis or rack-mounting space.
    ///
    /// This property shall contain the type of width that describes the rack-mountable equipment space.
    RackMountWidth: core.Nullable(RackMountWidth) = .absent,
    /// The usable depth of the rack-mountable area of the chassis.
    ///
    /// This property shall represent the depth (length) of the chassis, in millimeter units, that is available to contain rack-mounted equipment.
    RackMountDepthMm: core.Nullable(core.Decimal) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
