//! Namespace `Circuit`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const outlet = @import("outlet.zig");
const resource = @import("resource.zig");
const sensor = @import("sensor.zig");

pub const BreakerStates = enum {
    /// The breaker is powered on.
    Normal,
    /// The breaker has been tripped.
    Tripped,
    /// The breaker is off.
    Off,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const CircuitType = enum {
    /// A mains input or utility circuit.
    Mains,
    /// A branch (output) circuit.
    Branch,
    /// A subfeed (output) circuit.
    Subfeed,
    /// A feeder (output) circuit.
    Feeder,
    /// An electrical bus circuit.
    Bus,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const NominalVoltageType = enum {
    /// AC 100-127V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage in the complete range of 100-127VAC.  Range values are generally used to describe support on device inputs or inlets.
    AC100To127V,
    /// AC 100-240V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage in the complete range of 100-240VAC.  Range values are generally used to describe support on device inputs or inlets.
    AC100To240V,
    /// AC 100-277V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage in the complete range of 100-277VAC.  Range values are generally used to describe support on device inputs or inlets.
    AC100To277V,
    /// AC 120V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 120VAC.  Specific values are generally used to describe support on device outputs or outlets.
    AC120V,
    /// AC 200-240V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage in the complete range of 200-240VAC.  Range values are generally used to describe support on device inputs or inlets.
    AC200To240V,
    /// AC 200-277V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage in the complete range of 200-277VAC.  Range values are generally used to describe support on device inputs or inlets.
    AC200To277V,
    /// AC 208V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 208VAC.  Specific AC voltage values are generally used to describe support on device outputs or outlets.
    AC208V,
    /// AC 230V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 230AC.  Specific AC voltage values are generally used to describe support on device outputs or outlets.
    AC230V,
    /// AC 240V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 240VAC.  Specific AC voltage values are generally used to describe support on device outputs or outlets.
    AC240V,
    /// AC 200-240V and DC 380V.
    ///
    /// This value shall indicate the device supports a nominal voltage in the complete range of 200-240VAC or a value of 380VDC.  Range values are generally used to describe support on device inputs or inlets.
    AC240AndDC380V,
    /// AC 277V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 277VAC.  Specific AC high-voltage values may be used to describe support on device inputs or outputs.
    AC277V,
    /// AC 200-277V and DC 380V.
    ///
    /// This value shall indicate the device supports a nominal voltage in the complete range of 200-277VAC or a value of 380VDC.  Range values are generally used to describe support on device inputs or inlets.
    AC277AndDC380V,
    /// AC 400V or 415V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 400VAC or 415VAC.  Specific AC high-voltage values may be used to describe support on device inputs or outputs.
    AC400V,
    /// AC 480V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 480VAC.  Specific AC high-voltage values may be used to describe support on device inputs or outputs.
    AC480V,
    /// DC 48V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 48VDC.
    DC48V,
    /// DC 240V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 240VDC.
    DC240V,
    /// DC 380V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 380VDC.
    DC380V,
    /// DC 400V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 400VDC.
    DC400V,
    /// DC 800V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 800VDC.
    DC800V,
    /// -48V DC.
    ///
    /// This value shall indicate the device supports a nominal voltage of -48VDC.
    DCNeg48V,
    /// DC 16V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 16VDC.
    DC16V,
    /// DC 12V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 12VDC.
    DC12V,
    /// DC 9V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 9VDC.
    DC9V,
    /// DC 5V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 5VDC.
    DC5V,
    /// DC 3.3V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 3.3VDC.
    DC3_3V,
    /// DC 1.8V nominal.
    ///
    /// This value shall indicate the device supports a nominal voltage of 1.8VDC.
    DC1_8V,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const PhaseWiringType = enum {
    /// Single-phase / 3-wire (Line1, Neutral, Protective Earth).
    ///
    /// This value shall represent a single-phase / 3-wire (Line1, Neutral, Protective Earth) wiring.
    OnePhase3Wire,
    /// Two-phase / 3-wire (Line1, Line2, Protective Earth).
    ///
    /// This value shall represent a two-phase / 3-wire (Line1, Line2, Protective Earth) wiring.
    TwoPhase3Wire,
    /// Single or two-phase / 3-wire (Line1, Line2 or Neutral, Protective Earth).
    ///
    /// This value shall represent a single or two-phase / 3-wire (Line1, Line2 or Neutral, Protective Earth) wiring.  This value shall be used when both phase configurations are supported.  This is most common where detachable cordsets are used.  If poly-phase properties such as `PolyPhaseVoltage` are supported, the service should populate the measurements as if the circuit is wired as Line1, Neutral, and Protective Earth.
    OneOrTwoPhase3Wire,
    /// Two-phase / 4-wire (Line1, Line2, Neutral, Protective Earth).
    ///
    /// This value shall represent a two-phase / 4-wire (Line1, Line2, Neutral, Protective Earth) wiring.
    TwoPhase4Wire,
    /// Three-phase / 4-wire (Line1, Line2, Line3, Protective Earth).
    ///
    /// This value shall represent a three-phase / 4-wire (Line1, Line2, Line3, Protective Earth) wiring.
    ThreePhase4Wire,
    /// Three-phase / 5-wire (Line1, Line2, Line3, Neutral, Protective Earth).
    ///
    /// This value shall represent a three-phase / 5-wire (Line1, Line2, Line3, Neutral, Protective Earth) wiring.
    ThreePhase5Wire,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const PlugType = enum {
    /// NEMA 5-15P (Single-phase 125V; 15A; 1P3W).
    ///
    /// This value shall represent a plug that matches the NEMA specified 5-15 straight (non-locking) plug (Single-phase 125V; 15A; 1P3W).
    NEMA_5_15P,
    /// NEMA L5-15P (Single-phase 125V; 15A; 1P3W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L5-15 plug (Single-phase 125V; 15A; 1P3W).
    NEMA_L5_15P,
    /// NEMA 5-20P (Single-phase 125V; 20A; 1P3W).
    ///
    /// This value shall represent a plug that matches the NEMA specified 5-20 straight (non-locking) plug that exhibits a T-slot (Single-phase 125V; 20A; 1P3W).
    NEMA_5_20P,
    /// NEMA L5-20P (Single-phase 125V; 20A; 1P3W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L5-20 plug (Single-phase 125V; 20A; 1P3W).
    NEMA_L5_20P,
    /// NEMA L5-30P (Single-phase 125V; 30A; 1P3W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L5-30 plug (Single-phase 125V; 30A; 1P3W).
    NEMA_L5_30P,
    /// NEMA 6-15P (Single-phase 250V; 15A; 2P3W).
    ///
    /// This value shall represent a plug that matches the NEMA specified 6-15 straight (non-locking) plug (Single-phase 250V; 15A; 2P3W).
    NEMA_6_15P,
    /// NEMA L6-15P (Single-phase 250V; 15A; 2P3W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L6-15 plug (Single-phase 250V; 15A; 2P3W).
    NEMA_L6_15P,
    /// NEMA 6-20P (Single-phase 250V; 20A; 2P3W).
    ///
    /// This value shall represent a plug that matches the NEMA specified 6-20 straight (non-locking) plug (Single-phase 250V; 20A; 2P3W).
    NEMA_6_20P,
    /// NEMA L6-20P (Single-phase 250V; 20A; 2P3W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L6-20 plug (Single-phase 250V; 20A; 2P3W).
    NEMA_L6_20P,
    /// NEMA L6-30P (Single-phase 250V; 30A; 2P3W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L6-30 plug (Single-phase 250V; 30A; 2P3W).
    NEMA_L6_30P,
    /// NEMA L14-20P (Split-phase 125/250V; 20A; 2P4W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L14-20 plug (Split-phase 125/250V; 20A; 2P4W).
    NEMA_L14_20P,
    /// NEMA L14-30P (Split-phase 125/250V; 30A; 2P4W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L14-30 plug (Split-phase 125/250V; 30A; 2P4W).
    NEMA_L14_30P,
    /// NEMA L15-20P (Three-phase 250V; 20A; 3P4W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L15-20 plug (Three-phase 250V; 20A; 3P4W).
    NEMA_L15_20P,
    /// NEMA L15-30P (Three-phase 250V; 30A; 3P4W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L15-30 plug (Three-phase 250V; 30A; 3P4W).
    NEMA_L15_30P,
    /// NEMA L21-20P (Three-phase 120/208V; 20A; 3P5W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L21-20 plug (Three-phase 120/208V; 20A; 3P5W).
    NEMA_L21_20P,
    /// NEMA L21-30P (Three-phase 120/208V; 30A; 3P5W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L21-30 plug (Three-phase 120/208V; 30A; 3P5W).
    NEMA_L21_30P,
    /// NEMA L22-20P (Three-phase 277/480V; 20A; 3P5W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L22-20 plug (Three-phase 277/480V; 20A; 3P5W).
    NEMA_L22_20P,
    /// NEMA L22-30P (Three-phase 277/480V; 30A; 3P5W).
    ///
    /// This value shall represent a plug that matches the NEMA specified locking L22-30 plug (Three-phase 277/480V; 30A; 3P5W).
    NEMA_L22_30P,
    /// California Standard CS8265 (Single-phase 250V; 50A; 2P3W).
    ///
    /// This value shall represent a plug that matches the 'California Standard' CS8265 style plug (Single-phase 250V; 50A; 2P3W).
    California_CS8265,
    /// California Standard CS8365 (Three-phase 250V; 50A; 3P4W).
    ///
    /// This value shall represent a plug that matches the 'California Standard' CS8365 style plug (Three-phase 250V; 50A; 3P4W).
    California_CS8365,
    /// IEC C14 (Single-phase 250V; 10A; 1P3W).
    ///
    /// This value shall represent a plug that matches the IEC 60320 specified C14 input (Single-phase 250V; 10A; 1P3W).
    IEC_60320_C14,
    /// IEC C20 (Single-phase 250V; 16A; 1P3W).
    ///
    /// This value shall represent a plug that matches the IEC 60320 specified C20 input (Single-phase 250V; 16A; 1P3W).
    IEC_60320_C20,
    /// IEC 60309 316P6 (Single-phase 200-250V; 16A; 1P3W; Blue, 6-hour).
    ///
    /// This value shall represent a plug that matches the IEC 60309 316P6 plug (Single-phase 200-250V; 16A; 1P3W; Blue, 6-hour).
    IEC_60309_316P6,
    /// IEC 60309 332P6 (Single-phase 200-250V; 32A; 1P3W; Blue, 6-hour).
    ///
    /// This value shall represent a plug that matches the IEC 60309 332P6 plug (Single-phase 200-250V; 32A; 1P3W; Blue, 6-hour).
    IEC_60309_332P6,
    /// IEC 60309 363P6 (Single-phase 200-250V; 63A; 1P3W; Blue, 6-hour).
    ///
    /// This value shall represent a plug that matches the IEC 60309 363P6 plug (Single-phase 200-250V; 63A; 1P3W; Blue, 6-hour).
    IEC_60309_363P6,
    /// IEC 60309 516P6 (Three-phase 200-240/346-415V; 16A; 3P5W; Red; 6-hour).
    ///
    /// This value shall represent a plug that matches the IEC 60309 516P6 plug (Three-phase 200-240/346-415V; 16A; 3P5W; Red; 6-hour).
    IEC_60309_516P6,
    /// IEC 60309 532P6 (Three-phase 200-240/346-415V; 32A; 3P5W; Red; 6-hour).
    ///
    /// This value shall represent a plug that matches the IEC 60309 plug 532P6 (Three-phase 200-240/346-415V; 32A; 3P5W; Red; 6-hour).
    IEC_60309_532P6,
    /// IEC 60309 563P6 (Three-phase 200-240/346-415V; 63A; 3P5W; Red; 6-hour).
    ///
    /// This value shall represent a plug that matches the IEC 60309 563P6 plug (Three-phase 200-240/346-415V; 63A; 3P5W; Red; 6-hour).
    IEC_60309_563P6,
    /// IEC 60309 460P9 (Three-phase 200-250V; 60A; 3P4W; Blue; 9-hour).
    ///
    /// This value shall represent a plug that matches the IEC 60309 460P9 plug (Three-phase 200-250V; 60A; 3P4W; Blue; 9-hour).
    IEC_60309_460P9,
    /// IEC 60309 560P9 (Three-phase 120-144/208-250V; 60A; 3P5W; Blue; 9-hour).
    ///
    /// This value shall represent a plug that matches the IEC 60309 plug 560P9 (Three-phase 120-144/208-250V; 60A; 3P5W; Blue; 9-hour).
    IEC_60309_560P9,
    /// Field-wired; Three-phase 200-250V; 60A; 3P4W.
    ///
    /// This value shall represent field-wired input that is three-phase 200-250V; 60A; 3P4W.
    Field_208V_3P4W_60A,
    /// Field-wired; Three-phase 200-240/346-415V; 32A; 3P5W.
    ///
    /// This value shall represent field-wired input that is three-phase 200-240/346-415V; 32A; 3P5W.
    Field_400V_3P5W_32A,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// The enumerations of `PowerRestorePolicyTypes` specify the choice of power state when power is applied.
pub const PowerRestorePolicyTypes = enum {
    /// Always power on when external power is applied.
    AlwaysOn,
    /// Always remain powered off when external power is applied.
    AlwaysOff,
    /// Return to the last power state (on or off) when external power is applied.
    LastState,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const PowerState = enum {
    /// Power on.
    On,
    /// Power off.
    Off,
    /// Power cycle.
    ///
    /// This value shall indicate the resource will transition to a power off state, then transition to a power on state.  Upon successful completion, the `PowerState` property, if supported, shall contain the value `On`.
    PowerCycle,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const VoltageType = enum {
    /// Alternating Current (AC) circuit.
    AC,
    /// Direct Current (DC) circuit.
    DC,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// Arguments to `Circuit.BreakerControl`.
///
/// This action attempts to reset the circuit breaker.
pub const CircuitBreakerControlAction = struct {
    /// The desired power state of the circuit if the breaker is reset successfully.
    ///
    /// This parameter shall contain the desired power state of the circuit.
    PowerState: ?PowerState = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Arguments to `Circuit.PowerControl`.
///
/// This action turns the circuit on or off.
pub const CircuitPowerControlAction = struct {
    /// The desired power state of the circuit.
    ///
    /// This parameter shall contain the desired power state of the circuit.
    PowerState: ?PowerState = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Arguments to `Circuit.ResetMetrics`.
///
/// This action resets metrics related to this circuit.
pub const CircuitResetMetricsAction = struct {
    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
    /// This action attempts to reset the circuit breaker.
    ///
    /// This action shall control the state of the circuit breaker or over-current protection device.
    @"#Circuit.BreakerControl": ?core.Action(CircuitBreakerControlAction, std.json.Value) = null,
    /// This action turns the circuit on or off.
    ///
    /// This action shall control the power state of the circuit.
    @"#Circuit.PowerControl": ?core.Action(CircuitPowerControlAction, std.json.Value) = null,
    /// This action resets metrics related to this circuit.
    ///
    /// This action shall reset any time intervals or counted values for this circuit.
    @"#Circuit.ResetMetrics": ?core.Action(CircuitResetMetricsAction, std.json.Value) = null,

    /// This action attempts to reset the circuit breaker.
    ///
    /// This action shall control the state of the circuit breaker or over-current protection device.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn breakerControl(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: CircuitBreakerControlAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#Circuit.BreakerControl" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }

    /// This action turns the circuit on or off.
    ///
    /// This action shall control the power state of the circuit.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn powerControl(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: CircuitPowerControlAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#Circuit.PowerControl" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }

    /// This action resets metrics related to this circuit.
    ///
    /// This action shall reset any time intervals or counted values for this circuit.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn resetMetrics(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: CircuitResetMetricsAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#Circuit.ResetMetrics" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }
};

/// The current sensors for this circuit.
///
/// This type shall contain properties that describe current sensor readings for a circuit.
pub const CurrentSensors = struct {
    /// Line 1 current (A).
    ///
    /// This property shall contain the line current, in ampere units, for L1.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Current`.  This property shall not be present if the equipment does not include an L1 measurement.
    Line1: ?sensor.SensorExcerptCurrent = null,
    /// Line 2 current (A).
    ///
    /// This property shall contain the line current, in ampere units, for L2.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Current`.  This property shall not be present if the equipment does not include an L2 measurement.
    Line2: ?sensor.SensorExcerptCurrent = null,
    /// Line 3 current (A).
    ///
    /// This property shall contain the line current, in ampere units, for L3.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Current`.  This property shall not be present if the equipment does not include an L3 measurement.
    Line3: ?sensor.SensorExcerptCurrent = null,
    /// Neutral line current (A).
    ///
    /// This property shall contain the line current, in ampere units, for the Neutral line.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Current`.  This property shall not be present if the equipment does not include a Neutral line measurement.
    Neutral: ?sensor.SensorExcerptCurrent = null,
};

/// The energy readings for this circuit.
///
/// This type shall contain properties that describe energy sensor readings for a circuit.
pub const EnergySensors = struct {
    /// The Line 1 to Line 2 energy (kWh) for this circuit.
    ///
    /// This property shall contain the energy, in kilowatt-hour units, between L1 and L2.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `EnergykWh`.  This property shall not be present if the equipment does not include an L1-L2 measurement.
    Line1ToLine2: ?sensor.SensorExcerptEnergykWh = null,
    /// The Line 2 to Line 3 energy (kWh) for this circuit.
    ///
    /// This property shall contain the energy, in kilowatt-hour units, between L2 and L3.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `EnergykWh`.  This property shall not be present if the equipment does not include an L2-L3 measurement.
    Line2ToLine3: ?sensor.SensorExcerptEnergykWh = null,
    /// The Line 3 to Line 1 energy (kWh) for this circuit.
    ///
    /// This property shall contain the energy, in kilowatt-hour units, between L3 and L1.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `EnergykWh`.  This property shall not be present if the equipment does not include an L3-L1 measurement.
    Line3ToLine1: ?sensor.SensorExcerptEnergykWh = null,
    /// The Line 1 to Neutral energy (kWh) for this circuit.
    ///
    /// This property shall contain the energy, in kilowatt-hour units, between L1 and Neutral.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `EnergykWh`.  This property shall not be present if the equipment does not include an L1-Neutral measurement.
    Line1ToNeutral: ?sensor.SensorExcerptEnergykWh = null,
    /// The Line 2 to Neutral energy (kWh) for this circuit.
    ///
    /// This property shall contain the energy, in kilowatt-hour units, between L2 and Neutral.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `EnergykWh`.  This property shall not be present if the equipment does not include an L2-Neutral measurement.
    Line2ToNeutral: ?sensor.SensorExcerptEnergykWh = null,
    /// The Line 3 to Neutral energy (kWh) for this circuit.
    ///
    /// This property shall contain the energy, in kilowatt-hour units, between L3 and Neutral.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `EnergykWh`.  This property shall not be present if the equipment does not include an L3-Neutral measurement.
    Line3ToNeutral: ?sensor.SensorExcerptEnergykWh = null,
};

pub const Links = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// A reference to the branch circuit related to this circuit.
    ///
    /// This property shall contain a link to a resource of type `Circuit` that represents the branch circuit associated with this circuit.
    BranchCircuit: ?core.NavProperty(Circuit) = null,
    /// An array of references to the outlets contained by this circuit.
    ///
    /// This property shall contain an array of links to resources of type `Outlet` that represent the outlets associated with this circuit.
    Outlets: ?[]const core.NavProperty(outlet.Outlet) = null,
    /// A link to the circuit that provides power to this circuit.
    ///
    /// This property shall contain a link to a resource of type `Circuit` that represents the circuit that provides power to this circuit.  This property should be used when the power source is not represented by an Outlet resource, such as a feeder circuit.
    SourceCircuit: ?core.NavProperty(Circuit) = null,
    /// A link to the power outlet that provides power to this circuit.
    ///
    /// This property shall contain a link to a resource of type `Outlet` that represents the outlet that provides power to this circuit.
    PowerOutlet: ?core.NavProperty(outlet.Outlet) = null,
    /// An array of links to the circuits powered by this circuit.
    ///
    /// This property shall contain an array of links to resources of type `Circuit` that represent the circuits powered by this circuit.
    DistributionCircuits: ?[]const core.NavProperty(Circuit) = null,
};

/// What a client may change of `Circuit.Links`.
pub const LinksUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// This property contains the power sensors.
///
/// This type shall contain properties that describe power sensor readings for a circuit.
pub const PowerSensors = struct {
    /// The Line 1 to Line 2 power (W) for this circuit.
    ///
    /// This property shall contain the power, in watt units, between L1 and L2.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Power`.  This property shall not be present if the equipment does not include an L1-L2 measurement.
    Line1ToLine2: ?sensor.SensorExcerptPower = null,
    /// The Line 2 to Line 3 power (W) for this circuit.
    ///
    /// This property shall contain the power, in watt units, between L2 and L3.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Power`.  This property shall not be present if the equipment does not include an L2-L3 measurement.
    Line2ToLine3: ?sensor.SensorExcerptPower = null,
    /// The Line 3 to Line 1 power (W) for this circuit.
    ///
    /// This property shall contain the power, in watt units, between L3 and L1.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Power`.  This property shall not be present if the equipment does not include an L3-L1 measurement.
    Line3ToLine1: ?sensor.SensorExcerptPower = null,
    /// The Line 1 to Neutral power (W) for this circuit.
    ///
    /// This property shall contain the power, in watt units, between L1 and Neutral.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Power`.  This property shall not be present if the equipment does not include an L1-Neutral measurement.
    Line1ToNeutral: ?sensor.SensorExcerptPower = null,
    /// The Line 2 to Neutral power (W) for this circuit.
    ///
    /// This property shall contain the power, in watt units, between L2 and Neutral.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Power`.  This property shall not be present if the equipment does not include an L2-Neutral measurement.
    Line2ToNeutral: ?sensor.SensorExcerptPower = null,
    /// The Line 3 to Neutral power (W) for this circuit.
    ///
    /// This property shall contain the power, in watt units, between L3 and Neutral.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Power`.  This property shall not be present if the equipment does not include an L3-Neutral measurement.
    Line3ToNeutral: ?sensor.SensorExcerptPower = null,
};

/// The voltage readings for this circuit.
///
/// This type shall contain properties that describe voltage sensor readings for a circuit.
pub const VoltageSensors = struct {
    /// The Line 1 to Line 2 voltage (V) for this circuit.
    ///
    /// This property shall contain the line-to-line voltage, in volt units, between L1 and L2.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Voltage`.  This property shall not be present if the equipment does not include an L1-L2 measurement.
    Line1ToLine2: ?sensor.SensorExcerptVoltage = null,
    /// The Line 2 to Line 3 voltage (V) for this circuit.
    ///
    /// This property shall contain the line-to-line voltage, in volt units, between L2 and L3.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Voltage`.  This property shall not be present if the equipment does not include an L2-L3 measurement.
    Line2ToLine3: ?sensor.SensorExcerptVoltage = null,
    /// The Line 3 to Line 1 voltage (V) for this circuit.
    ///
    /// This property shall contain the line-to-line voltage, in volt units, between L3 and L1.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Voltage`.  This property shall not be present if the equipment does not include an L3-L1 measurement.
    Line3ToLine1: ?sensor.SensorExcerptVoltage = null,
    /// The Line 1 to Neutral voltage (V) for this circuit.
    ///
    /// This property shall contain the line-to-line voltage, in volt units, between L1 and Neutral.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Voltage`.  This property shall not be present if the equipment does not include an L1-Neutral measurement.
    Line1ToNeutral: ?sensor.SensorExcerptVoltage = null,
    /// The Line 2 to Neutral voltage (V) for this circuit.
    ///
    /// This property shall contain the line-to-line voltage, in volt units, between L2 and Neutral.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Voltage`.  This property shall not be present if the equipment does not include an L2-Neutral measurement.
    Line2ToNeutral: ?sensor.SensorExcerptVoltage = null,
    /// The Line 3 to Neutral voltage (V) for this circuit.
    ///
    /// This property shall contain the line-to-line voltage, in volt units, between L3 and Neutral.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Voltage`.  This property shall not be present if the equipment does not include an L3-Neutral measurement.
    Line3ToNeutral: ?sensor.SensorExcerptVoltage = null,
};

/// This `Circuit` schema contains the definition for an electrical circuit.
///
/// This resource shall be used to represent an electrical circuit for a Redfish implementation.
pub const Circuit = struct {
    /// Where the resource lives.
    @"@odata.id": core.ODataId,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: resource.Id,
    Description: ?resource.Description = null,
    Name: resource.Name,
    /// The status and health of the resource and its subordinate or dependent resources.
    ///
    /// This property shall contain any status or health properties of the resource.
    Status: ?resource.Status = null,
    /// The type of circuit.
    ///
    /// This property shall contain the type of circuit.
    CircuitType: ?CircuitType = null,
    /// Designates if this is a critical circuit.
    ///
    /// This property shall indicate whether the circuit is designated as a critical circuit, and therefore is excluded from autonomous logic that could affect the state of the circuit.  The value shall be `true` if the circuit is deemed critical, and `false` if the circuit is not critical.
    CriticalCircuit: ?bool = null,
    /// The combination of current-carrying conductors.
    ///
    /// This property shall contain the combination of current-carrying conductors that distribute power.
    ElectricalContext: ?sensor.ElectricalContext = null,
    /// The number of ungrounded current-carrying conductors (phases) and the total number of conductors (wires).
    ///
    /// This property shall contain the number of ungrounded current-carrying conductors (phases) and the total number of conductors (wires).
    PhaseWiringType: ?PhaseWiringType = null,
    /// The type of voltage applied to the circuit.
    ///
    /// This property shall contain the type of voltage applied to the circuit.
    VoltageType: ?VoltageType = null,
    /// The type of plug according to NEMA, IEC, or regional standards.
    ///
    /// This property shall contain the type of physical plug used for this circuit, as defined by IEC, NEMA, or regional standards.
    PlugType: ?PlugType = null,
    /// The nominal voltage for this circuit.
    ///
    /// This property shall contain the nominal voltage for this circuit, in volt units.
    NominalVoltage: ?NominalVoltageType = null,
    /// The rated maximum current allowed for this circuit.
    ///
    /// This property shall contain the rated maximum current for this circuit, in ampere units, after any required de-rating, due to safety agency or other regulatory requirements, has been applied.
    RatedCurrentAmps: ?core.Decimal = null,
    /// The state of the indicator LED, which identifies the circuit.
    ///
    /// This property shall contain the indicator light state for the indicator light associated with this circuit.
    ///
    /// Deprecated in v1_1_0.
    /// This property has been deprecated in favor of the `LocationIndicatorActive` property.
    IndicatorLED: ?resource.IndicatorLed = null,
    /// The state of the overcurrent protection device.
    ///
    /// This property shall contain the state of the overcurrent protection device.
    BreakerState: ?BreakerStates = null,
    /// The number of seconds to delay power up after a power cycle or a `PowerControl` action.  Zero seconds indicates no delay to power up.
    ///
    /// This property shall contain the number of seconds to delay power up after a power cycle or a `PowerControl` action.  The value `0` shall indicate no delay to power up.
    PowerOnDelaySeconds: ?core.Decimal = null,
    /// The number of seconds to delay power off after a `PowerControl` action.  Zero seconds indicates no delay to power off.
    ///
    /// This property shall contain the number of seconds to delay power off after a `PowerControl` action.  The value `0` shall indicate no delay to power off.
    PowerOffDelaySeconds: ?core.Decimal = null,
    /// The number of seconds to delay power on after a `PowerControl` action to cycle power.  Zero seconds indicates no delay.
    ///
    /// This property shall contain the number of seconds to delay power on after a `PowerControl` action to cycle power.  The value `0` shall indicate no delay to power on.
    PowerCycleDelaySeconds: ?core.Decimal = null,
    /// The number of seconds to delay power on after power has been restored.  Zero seconds indicates no delay.
    ///
    /// This property shall contain the number of seconds to delay power on after a power fault.  The value `0` shall indicate no delay to power on.
    PowerRestoreDelaySeconds: ?core.Decimal = null,
    /// The desired power state of the circuit when power is restored after a power loss.
    ///
    /// This property shall contain the desired `PowerState` of the circuit when power is applied.  The value `LastState` shall return the circuit to the `PowerState` it was in when power was lost.
    PowerRestorePolicy: ?PowerRestorePolicyTypes = null,
    /// The power state of the circuit.
    ///
    /// This property shall contain the power state of the circuit.
    PowerState: ?resource.PowerState = null,
    /// Indicates if the circuit can be powered.
    ///
    /// This property shall indicate the power enable state of the circuit.  The value `true` shall indicate that the circuit can be powered on, and `false` shall indicate that the circuit cannot be powered.
    PowerEnabled: ?bool = null,
    /// The voltage readings for this circuit.
    ///
    /// This property shall contain the voltage sensors for this circuit.  For 3-wire circuits, this property shall contain a duplicate copy of the voltage sensor referenced in the `Voltage` property, if present.  For other circuits, this property should contain multiple voltage sensor readings used to fully describe the circuit.
    PolyPhaseVoltage: ?VoltageSensors = null,
    /// The current readings for this circuit.
    ///
    /// This property shall contain the current sensors for this circuit.  For 3-wire circuits, this property shall contain a duplicate copy of the current sensor referenced in the `CurrentAmps` property, if present.  For other circuits, this property should contain multiple current sensor readings used to fully describe the circuit.
    PolyPhaseCurrentAmps: ?CurrentSensors = null,
    /// The power readings for this circuit.
    ///
    /// This property shall contain the power sensors for this circuit.  For 3-wire circuits, this property shall contain a duplicate copy of the power sensor referenced in the `PowerWatts` property, if present.  For other circuits, this property should contain multiple power sensor readings used to fully describe the circuit.
    PolyPhasePowerWatts: ?PowerSensors = null,
    /// The energy readings for this circuit.
    ///
    /// This property shall contain the energy sensors for this circuit.  For 3-wire circuits, this property shall contain a duplicate copy of the energy sensor referenced in the `EnergykWh` property, if present.  For other circuits, this property should contain multiple energy sensor readings used to fully describe the circuit.
    PolyPhaseEnergykWh: ?EnergySensors = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?Links = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// An indicator allowing an operator to physically locate this resource.
    ///
    /// This property shall contain the state of the indicator used to physically identify or locate this resource.  A write to this property shall update the value of `IndicatorLED` in this resource, if supported, to reflect the implementation of the locating function.
    LocationIndicatorActive: ?bool = null,
    /// A user-assigned label.
    ///
    /// This property shall contain a user-assigned label used to identify this resource.  If a value has not been assigned by a user, the value of this property shall be an empty string.
    UserLabel: ?[]const u8 = null,
    /// The URI of the management interface for the upstream electrical source connection for this circuit.
    ///
    /// This property shall contain a URI to the management application or device that provides monitoring or control of the upstream electrical source that provides power to this circuit.  If a value has not been assigned by a user, the value of this property shall be an empty string.
    ElectricalSourceManagerURI: ?[]const u8 = null,
    /// The name of the upstream electrical source, such as a circuit or outlet, connected to this circuit.
    ///
    /// This property shall contain a string that identifies the upstream electrical source, such as the name of a circuit or outlet, that provides power to this circuit.  If a value has not been assigned by a user, the value of this property shall be an empty string.
    ElectricalSourceName: ?[]const u8 = null,
    /// An array of names of downstream devices that are powered by this circuit.
    ///
    /// This property shall contain an array of user-assigned identifying strings that describe downstream devices that are powered by this circuit.
    ElectricalConsumerNames: ?[]const []const u8 = null,
    /// Indicates whether power control requests are locked.
    ///
    /// This property shall indicate whether requests to the `PowerControl` action are locked.  If `true`, services shall reject requests to the `PowerControl` action.
    PowerControlLocked: ?bool = null,
    /// Indicates whether the configuration is locked.
    ///
    /// This property shall indicate whether modification requests to this resource are not permitted.  If `true`, services shall reject modification requests to other properties in this resource.
    ConfigurationLocked: ?bool = null,
    /// Indicates whether the power state is undergoing a delayed transition.
    ///
    /// This property shall indicate whether the `PowerState` property will undergo a transition between on and off states due to a configured delay.  The transition may be due to the configuration of the power on, off, or restore delay properties.  If `true`, the `PowerState` property will transition at the conclusion of a configured delay.
    PowerStateInTransition: ?bool = null,
    /// The nominal frequency (Hz) for this circuit.
    ///
    /// This property shall contain the nominal frequency for this circuit, in hertz units.
    NominalFrequencyHz: ?core.Decimal = null,
    /// The voltage (V) for this circuit.
    ///
    /// This property shall contain the voltage, in volt units, for this circuit.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Voltage`.  This property shall not be present if `PhaseWiringType` contains a value that indicates a 4-wire or greater configuration, such as `TwoPhase4Wire`.
    Voltage: ?sensor.SensorExcerptVoltage = null,
    /// The current (A) for this circuit.
    ///
    /// This property shall contain the current, in ampere units, for this circuit.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Current`.  This property shall not be present if `PhaseWiringType` contains a value that indicates a 4-wire or greater configuration, such as `TwoPhase4Wire`.
    CurrentAmps: ?sensor.SensorExcerptCurrent = null,
    /// The power (W) for this circuit.
    ///
    /// This property shall contain the total power, in watt units, for this circuit that represents the `Total` `ElectricalContext` sensor when multiple power sensors exist for this circuit.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Power`.
    PowerWatts: ?sensor.SensorExcerptPower = null,
    /// The energy (kWh) for this circuit.
    ///
    /// This property shall contain the total energy, in kilowatt-hour units, for this circuit that represents the `Total` `ElectricalContext` sensor when multiple energy sensors exist for this circuit.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `EnergykWh`.
    EnergykWh: ?sensor.SensorExcerptEnergykWh = null,
    /// The frequency (Hz) for this circuit.
    ///
    /// This property shall contain the frequency, in hertz units, for this circuit.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Frequency`.
    FrequencyHz: ?sensor.SensorExcerpt = null,
    /// The power load (percent) for this circuit.
    ///
    /// This property shall contain the power load, in percent units, for this circuit that represents the `Total` `ElectricalContext` for this circuit.
    PowerLoadPercent: ?sensor.SensorExcerpt = null,
    /// The voltage imbalance (percent) between phases.
    ///
    /// This property shall contain the voltage imbalance, in percent units, between phases in a poly-phase circuit.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Percent`.
    UnbalancedVoltagePercent: ?sensor.SensorExcerpt = null,
    /// The current imbalance (percent) between phases.
    ///
    /// This property shall contain the current imbalance, in percent units, between phases in a poly-phase circuit.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Percent`.
    UnbalancedCurrentPercent: ?sensor.SensorExcerpt = null,
};

/// What a client may change of `Circuit.Circuit`.
///
/// This `Circuit` schema contains the definition for an electrical circuit.
pub const CircuitUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// Designates if this is a critical circuit.
    ///
    /// This property shall indicate whether the circuit is designated as a critical circuit, and therefore is excluded from autonomous logic that could affect the state of the circuit.  The value shall be `true` if the circuit is deemed critical, and `false` if the circuit is not critical.
    CriticalCircuit: core.Nullable(bool) = .absent,
    /// The state of the indicator LED, which identifies the circuit.
    ///
    /// This property shall contain the indicator light state for the indicator light associated with this circuit.
    ///
    /// Deprecated in v1_1_0.
    /// This property has been deprecated in favor of the `LocationIndicatorActive` property.
    IndicatorLED: core.Nullable(resource.IndicatorLed) = .absent,
    /// The number of seconds to delay power up after a power cycle or a `PowerControl` action.  Zero seconds indicates no delay to power up.
    ///
    /// This property shall contain the number of seconds to delay power up after a power cycle or a `PowerControl` action.  The value `0` shall indicate no delay to power up.
    PowerOnDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The number of seconds to delay power off after a `PowerControl` action.  Zero seconds indicates no delay to power off.
    ///
    /// This property shall contain the number of seconds to delay power off after a `PowerControl` action.  The value `0` shall indicate no delay to power off.
    PowerOffDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The number of seconds to delay power on after a `PowerControl` action to cycle power.  Zero seconds indicates no delay.
    ///
    /// This property shall contain the number of seconds to delay power on after a `PowerControl` action to cycle power.  The value `0` shall indicate no delay to power on.
    PowerCycleDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The number of seconds to delay power on after power has been restored.  Zero seconds indicates no delay.
    ///
    /// This property shall contain the number of seconds to delay power on after a power fault.  The value `0` shall indicate no delay to power on.
    PowerRestoreDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The desired power state of the circuit when power is restored after a power loss.
    ///
    /// This property shall contain the desired `PowerState` of the circuit when power is applied.  The value `LastState` shall return the circuit to the `PowerState` it was in when power was lost.
    PowerRestorePolicy: ?PowerRestorePolicyTypes = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?LinksUpdate = null,
    /// An indicator allowing an operator to physically locate this resource.
    ///
    /// This property shall contain the state of the indicator used to physically identify or locate this resource.  A write to this property shall update the value of `IndicatorLED` in this resource, if supported, to reflect the implementation of the locating function.
    LocationIndicatorActive: core.Nullable(bool) = .absent,
    /// A user-assigned label.
    ///
    /// This property shall contain a user-assigned label used to identify this resource.  If a value has not been assigned by a user, the value of this property shall be an empty string.
    UserLabel: ?[]const u8 = null,
    /// The URI of the management interface for the upstream electrical source connection for this circuit.
    ///
    /// This property shall contain a URI to the management application or device that provides monitoring or control of the upstream electrical source that provides power to this circuit.  If a value has not been assigned by a user, the value of this property shall be an empty string.
    ElectricalSourceManagerURI: ?[]const u8 = null,
    /// The name of the upstream electrical source, such as a circuit or outlet, connected to this circuit.
    ///
    /// This property shall contain a string that identifies the upstream electrical source, such as the name of a circuit or outlet, that provides power to this circuit.  If a value has not been assigned by a user, the value of this property shall be an empty string.
    ElectricalSourceName: ?[]const u8 = null,
    /// An array of names of downstream devices that are powered by this circuit.
    ///
    /// This property shall contain an array of user-assigned identifying strings that describe downstream devices that are powered by this circuit.
    ElectricalConsumerNames: core.Nullable([]const []const u8) = .absent,
    /// Indicates whether power control requests are locked.
    ///
    /// This property shall indicate whether requests to the `PowerControl` action are locked.  If `true`, services shall reject requests to the `PowerControl` action.
    PowerControlLocked: ?bool = null,
    /// Indicates whether the configuration is locked.
    ///
    /// This property shall indicate whether modification requests to this resource are not permitted.  If `true`, services shall reject modification requests to other properties in this resource.
    ConfigurationLocked: ?bool = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
