//! Namespace `ComponentIntegrity`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const certificate = @import("certificate.zig");
const resource = @import("resource.zig");

pub const ComponentIntegrityType = enum {
    /// Security Protocol and Data Model (SPDM) protocol.
    ///
    /// This value shall indicate the integrity information is obtained through the Security Protocol and Data Model (SPDM) protocol as defined in DMTF DSP0274.
    SPDM,
    /// Trusted Platform Module (TPM).
    ///
    /// This value shall indicate the integrity information is related to a Trusted Platform Module (TPM) as defined by the Trusted Computing Group (TCG).
    TPM,
    /// Trusted Cryptography Module (TCM).
    ///
    /// This value shall indicate the integrity information is related to a Trusted Cryptography Module (TCM) as defined by the China TCM Union (TCMU).
    TCM,
    /// Trusted Platform Control Module (TPCM).
    ///
    /// This value shall indicate the integrity information is related to a Trusted Platform Control Module (TPCM) as defined by the Zhongguancun Trusted Computing Industry Alliance (ZTCIA).
    TPCM,
    /// OEM-specific.
    ///
    /// This value shall indicate the integrity information is OEM-specific and the OEM section may include additional information.
    OEM,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const DmtFmeasurementTypes = enum {
    /// Immutable ROM.
    ///
    /// This value shall indicate the measurement is for an immutable ROM, as defined by entry '0x0' in the 'DMTFSpecMeasurementValueType values' table of DSP0274.
    ImmutableROM,
    /// Mutable firmware or any mutable code.
    ///
    /// This value shall indicate the measurement is for mutable firmware, as defined by entry '0x1' in the 'DMTFSpecMeasurementValueType values' table of DSP0274.
    MutableFirmware,
    /// Hardware configuration, such as straps.
    ///
    /// This value shall indicate the measurement is for hardware configuration, as defined by entry '0x2' in the 'DMTFSpecMeasurementValueType values' table of DSP0274.
    HardwareConfiguration,
    /// Firmware configuration, such as configurable firmware policy.
    ///
    /// This value shall indicate the measurement is for firmware configuration, as defined by entry '0x3' in the 'DMTFSpecMeasurementValueType values' table of DSP0274.
    FirmwareConfiguration,
    /// Mutable firmware version.
    ///
    /// This value shall indicate the measurement is for a version number of mutable firmware, as defined by entry '0x6' in the 'DMTFSpecMeasurementValueType values' table of DSP0274.
    MutableFirmwareVersion,
    /// Mutable firmware security version number.
    ///
    /// This value shall indicate the measurement is for a security version number of mutable firmware, as defined by entry '0x7' in the 'DMTFSpecMeasurementValueType values' table of DSP0274.
    MutableFirmwareSecurityVersionNumber,
    /// Freeform measurement manifest.
    ///
    /// This value shall indicate the measurement is for a freeform measurement manifest, as defined by entry '0x4' in the 'DMTFSpecMeasurementValueType values' table of DSP0274.
    MeasurementManifest,
    /// Structured representation of debug and device mode.
    ///
    /// This value shall indicate the measurement is for a structured representation of debug and device mode, as defined by entry '0x5' in the 'DMTFSpecMeasurementValueType values' table of DSP0274.
    DebugAndDeviceMode,
    /// Hash-extend measurement.
    ///
    /// This value shall indicate the measurement is for a hash-extend measurement, as defined by entry '0x8' in the 'DMTFSpecMeasurementValueType values' table of DSP0274.
    HashExtendMeasurement,
    /// Informational.
    ///
    /// This value shall indicate the measurement is informational, as defined by entry '0x9' in the 'DMTFSpecMeasurementValueType values' table of DSP0274.
    Informational,
    /// Structured measurement manifest.
    ///
    /// This value shall indicate the measurement is for a structured measurement manifest, as defined by entry '0xA' in the 'DMTFSpecMeasurementValueType values' table of DSP0274.
    StructuredMeasurementManifest,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const MeasurementSpecification = enum {
    /// DMTF.
    ///
    /// This value shall indicate the measurement specification is defined by DMTF in DSP0274.
    DMTF,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const SpdMmeasurementSummaryType = enum {
    /// The measurement summary covers the TCB.
    TCB,
    /// The measurement summary covers all measurements in SPDM.
    All,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const SecureSessionType = enum {
    /// A plain text session without any protection.
    Plain,
    /// An established session where both encryption and authentication are protecting the communication.
    EncryptedAuthenticated,
    /// An established session where only authentication is protecting the communication.
    AuthenticatedOnly,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const VerificationStatus = enum {
    /// Successful verification.
    Success,
    /// Unsuccessful verification.
    Failed,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// Arguments to `ComponentIntegrity.SPDMGetSignedMeasurements`.
///
/// This action generates an SPDM cryptographic signed statement over the given nonce and measurements of the SPDM Responder.
pub const ComponentIntegritySpdmGetSignedMeasurementsAction = struct {
    /// A 32-byte hex-encoded string that is signed with the measurements.  The value should be unique.
    ///
    /// This parameter shall contain a 32-byte hex-encoded string that is signed with the measurements.  If not provided by the client, the SPDM Requester shall generate the nonce.  The value should be unique and generated using a random or a pseudo-random generator.  The SPDM Requester shall send this value to the SPDM Responder in the SPDM 'GET_MEASUREMENTS' request.
    Nonce: ?[]const u8 = null,
    /// The slot identifier for the certificate containing the private key to generate the signature over the measurements.
    ///
    /// This parameter shall contain the SPDM slot identifier for the certificate containing the private key to generate the signature over the measurements.  If not provided by the client, the value shall be assumed to be `0`.  The SPDM Requester shall send this value to the SPDM Responder in the SPDM 'GET_MEASUREMENTS' request.
    SlotId: ?i64 = null,
    /// An array of indices that identify the measurement blocks to sign.
    ///
    /// This parameter shall contain an array of indices that identify the measurement blocks to sign.  This array shall contain one or more unique values between `0` to `254`, inclusive, or contain a single value of `255`.  If not provided by the client, the value shall be assumed to be an array containing a single value of `255`.
    MeasurementIndices: ?[]const i64 = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Arguments to `ComponentIntegrity.TPMGetSignedMeasurements`.
///
/// This action generates a TPM cryptographic signed statement over the given nonce and PCRs of the TPM for TPM 2.0 devices.
pub const ComponentIntegrityTpmGetSignedMeasurementsAction = struct {
    /// A set of bytes as a hex-encoded string that is signed with the measurements.  The value should be unique.
    ///
    /// This parameter shall contain a set of bytes as a hex-encoded string that is signed with the measurements.  Services shall reject the action request if the number of bytes provided is larger than the value specified by the `NonceSizeBytesMaximum` property in the `TPM` property.  If not provided by the client, the service shall generate the nonce.  The value should be unique and generated using a random or a pseudo-random generator.  The service shall send this value to the TPM in the 'qualifyingData' parameter of the 'TPM2_Quote' command defined in the Trusted Platform Module Library Specification.
    Nonce: ?[]const u8 = null,
    /// The URI for the certificate that represents the TPM attestation key.
    ///
    /// This parameter shall contain the reference to the certificate installed on the TPM that represents the TPM's attestation key for the 'signHandle' parameter of the 'TPM2_Quote' command defined in the Trusted Platform Module Library Specification.
    Certificate: ?core.Reference = null,
    /// The signing scheme to use for the TPM attestation key.
    ///
    /// This parameter shall contain a Base64-encoded string, with padding characters, of the 'TPMT_SIG_SCHEME' object as defined in the Trusted Platform Module Library Specification, that identifies the signing scheme to use for the TPM attestation key.  The service shall send this value to the TPM in the 'inScheme' parameter of the 'TPM2_Quote' command defined in the Trusted Platform Module Library Specification.
    Scheme: ?[]const u8 = null,
    /// An object that identifies the PCRs to sign.
    ///
    /// This parameter shall contain a Base64-encoded string, with padding characters, of the 'TPML_PCR_SELECTION' object as defined by the Trusted Platform Module Library Specification, that identifies the PCRs to sign.  The service shall send this value to the TPM in the 'PCRselect' parameter of the 'TPM2_Quote' command defined in the Trusted Platform Module Library Specification.
    PCRSelection: ?[]const u8 = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
    /// This action generates an SPDM cryptographic signed statement over the given nonce and measurements of the SPDM Responder.
    ///
    /// This action shall generate a cryptographic signed statement over the given nonce and measurements corresponding to the SPDM Responder.  This action shall not be present if the `ComponentIntegrityType` property does not contain the value `SPDM`.  The SPDM Requester shall issue one or more SPDM 'GET_MEASUREMENTS' requests for each of the requested measurement indices to the SPDM Responder.  When the SPDM 'GET_MEASUREMENTS' requests are made for version 1.2, the parameter 'RawBitStreamRequested' shall contain `0`.  The SPDM Requester shall provide the nonce for the action to the SPDM Responder in the last SPDM 'GET_MEASUREMENTS' request.  The SPDM Requester shall request a signature in the last SPDM 'GET_MEASUREMENTS' request.
    @"#ComponentIntegrity.SPDMGetSignedMeasurements": ?core.Action(ComponentIntegritySpdmGetSignedMeasurementsAction, SpdmGetSignedMeasurementsResponse) = null,
    /// This action generates a TPM cryptographic signed statement over the given nonce and PCRs of the TPM for TPM 2.0 devices.
    ///
    /// This action shall generate a cryptographic signed statement over the given nonce and PCRs of the TPM for TPM 2.0 devices.  This action shall not be present if the `ComponentIntegrityType` property does not contain the value `TPM`.
    @"#ComponentIntegrity.TPMGetSignedMeasurements": ?core.Action(ComponentIntegrityTpmGetSignedMeasurementsAction, TpmGetSignedMeasurementsResponse) = null,

    /// This action generates an SPDM cryptographic signed statement over the given nonce and measurements of the SPDM Responder.
    ///
    /// This action shall generate a cryptographic signed statement over the given nonce and measurements corresponding to the SPDM Responder.  This action shall not be present if the `ComponentIntegrityType` property does not contain the value `SPDM`.  The SPDM Requester shall issue one or more SPDM 'GET_MEASUREMENTS' requests for each of the requested measurement indices to the SPDM Responder.  When the SPDM 'GET_MEASUREMENTS' requests are made for version 1.2, the parameter 'RawBitStreamRequested' shall contain `0`.  The SPDM Requester shall provide the nonce for the action to the SPDM Responder in the last SPDM 'GET_MEASUREMENTS' request.  The SPDM Requester shall request a signature in the last SPDM 'GET_MEASUREMENTS' request.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn spdmGetSignedMeasurements(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ComponentIntegritySpdmGetSignedMeasurementsAction,
    ) !core.Owned(core.ModificationResponse(SpdmGetSignedMeasurementsResponse)) {
        const target = self.@"#ComponentIntegrity.SPDMGetSignedMeasurements" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }

    /// This action generates a TPM cryptographic signed statement over the given nonce and PCRs of the TPM for TPM 2.0 devices.
    ///
    /// This action shall generate a cryptographic signed statement over the given nonce and PCRs of the TPM for TPM 2.0 devices.  This action shall not be present if the `ComponentIntegrityType` property does not contain the value `TPM`.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn tpmGetSignedMeasurements(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ComponentIntegrityTpmGetSignedMeasurementsAction,
    ) !core.Owned(core.ModificationResponse(TpmGetSignedMeasurementsResponse)) {
        const target = self.@"#ComponentIntegrity.TPMGetSignedMeasurements" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }
};

/// Common Authentication information.
///
/// This object shall contain common identity-related authentication information.
pub const CommonAuthInfo = struct {
    /// The status of the verification of the identity of the component.
    ///
    /// This property shall contain the status of the verification of the identity of the component referenced by the `TargetComponentURI` property.
    VerificationStatus: ?VerificationStatus = null,
    /// A link to the certificate that represents the identity of the component.
    ///
    /// This property shall contain a link to a resource of type `Certificate` that represents the identity of the component referenced by the `TargetComponentURI` property.
    ComponentCertificate: ?core.NavProperty(certificate.Certificate) = null,
};

/// Information about communication between two components.
///
/// This object shall contain information about communication between two components.
pub const CommunicationInfo = struct {
    /// The active sessions or communication channels between two components.
    ///
    /// This property shall contain an array of the active sessions or communication channels between two components.  The active sessions or communication channels do not reflect how future sessions or communication channels are established.
    Sessions: ?[]const ?SingleSessionInfo = null,
};

/// The links to other resources that are related to this resource.
///
/// This Redfish Specification-described type shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
pub const Links = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// An array of links to resources that the target component protects.
    ///
    /// This property shall contain an array of links to resources that the component identified by the `TargetComponentURI` property provides integrity protection.  This property shall not contain the value of the `TargetComponentURI` property.
    ComponentsProtected: ?[]const core.NavProperty(resource.Item) = null,
};

/// What a client may change of `ComponentIntegrity.Links`.
///
/// The links to other resources that are related to this resource.
pub const LinksUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The SPDM signed measurement from an SPDM Responder.
///
/// This object shall contain the SPDM signed measurements from an SPDM Responder.
pub const SpdmGetSignedMeasurementsResponse = struct {
    /// Base64-encoded cryptographic signed statement generated by the signer.
    ///
    /// This property shall contain the cryptographic signed statement over the given nonce and measurement blocks corresponding to the requested measurement indices.  If the SPDM version is 1.2, this value shall be a concatenation of SPDM 'VCA' and 'GET_MEASUREMENTS' requests and responses exchanged between the SPDM Requester and the SPDM Responder.  If SPDM version is 1.0 or 1.1, this value shall be a concatenation of SPDM 'GET_MEASUREMENTS' requests and responses exchanged between the SPDM Requester and the SPDM Responder.  The last 'MEASUREMENTS' response shall contain a signature generated over the 'L2' string by the SPDM Responder.
    SignedMeasurements: ?[]const u8 = null,
    /// A Privacy Enhanced Mail (PEM)-encoded public key that can be used to validate the signature.
    ///
    /// This property shall contain a Privacy Enhanced Mail (PEM)-encoded public key, as defined in section 13 of RFC7468, that can be used to validate the signature.  This property shall only be present when the SPDM Requester was pre-provisioned with the SPDM Responder's public key and the SlotId parameter contains the value `15`.
    PublicKey: ?[]const u8 = null,
    /// The SPDM version used by the SPDM Responder to generate the cryptographic signed statement.
    ///
    /// This property shall contain the SPDM version negotiated between the SPDM Requester and the SPDM Responder to generate the cryptographic signed statement.  For example, `1.0`, `1.1`, or `1.2`.
    Version: ?[]const u8 = null,
    /// The hashing algorithm used for generating the cryptographic signed statement.
    ///
    /// This property shall contain the hashing algorithm negotiated between the SPDM Requester and the SPDM Responder.  The allowable values for this property shall be the hash algorithm names found in the 'BaseHashAlgo' field of the 'NEGOTIATE_ALGORITHMS' request message in DSP0274.  If the algorithm is an extended algorithm, this property shall contain the value `OEM`.
    HashingAlgorithm: ?[]const u8 = null,
    /// The asymmetric signing algorithm used for generating the cryptographic signed statement.
    ///
    /// This property shall contain the asymmetric signing algorithm negotiated between the SPDM Requester and the SPDM Responder.  The allowable values for this property shall be the asymmetric key signature algorithm names found in the 'SPDM Asymmetric Signature Reference Information' table in DSP0274.  If the algorithm is an extended algorithm, this property shall contain the value `OEM`.
    SigningAlgorithm: ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// A link to the certificate corresponding to the SPDM slot identifier that can be used to validate the signature.
    ///
    /// This property shall contain a link to a resource of type `Certificate` that represents the certificate corresponding to the SPDM slot identifier that can be used to validate the signature.  This property shall not be present if the SlotId parameter contains the value `15`.
    Certificate: ?core.NavProperty(certificate.Certificate) = null,
};

/// What a client may change of `ComponentIntegrity.SPDMGetSignedMeasurementsResponse`.
///
/// The SPDM signed measurement from an SPDM Responder.
pub const SpdmGetSignedMeasurementsResponseUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Identity authentication information about the SPDM Requester and SPDM Responder.
///
/// This object shall contain identity authentication information about the SPDM Requester and SPDM Responder.
pub const SpdMidentity = struct {
    /// Authentication information of the identity of the SPDM Responder.
    ///
    /// This property shall contain authentication information of the identity of the SPDM Responder.
    ResponderAuthentication: ?CommonAuthInfo = null,
    /// Authentication information of the identity of the SPDM Requester.
    ///
    /// This property shall contain authentication information of the identity of the SPDM Requester.
    RequesterAuthentication: ?SpdMrequesterAuth = null,
};

/// Integrity information about an SPDM Responder as reported by an SPDM Requester.
///
/// This object shall contain integrity information about an SPDM Responder as reported by an SPDM Requester.
pub const SpdMinfo = struct {
    /// Measurement information about the SPDM Responder.
    ///
    /// This property shall contain measurement information for the SPDM Responder.
    MeasurementSet: ?SpdMmeasurementSet = null,
    /// Identity authentication information about the SPDM Requester and SPDM Responder.
    ///
    /// This property shall contain identity authentication information about the SPDM Requester and SPDM Responder.
    IdentityAuthentication: ?SpdMidentity = null,
    /// Information about communication between the SPDM Requester and SPDM Responder.
    ///
    /// This property shall contain information about communication between the SPDM Requester and SPDM Responder.
    ComponentCommunication: ?CommunicationInfo = null,
    /// The link to the component that is reporting the integrity information of the target component.
    ///
    /// This property shall contain a link to the resource representing the SPDM Responder that is reporting the integrity of the SPDM Responder identified by the `TargetComponentURI` property.
    Requester: ?core.NavProperty(resource.Item) = null,
};

/// What a client may change of `ComponentIntegrity.SPDMinfo`.
///
/// Integrity information about an SPDM Responder as reported by an SPDM Requester.
pub const SpdMinfoUpdate = struct {
    /// Measurement information about the SPDM Responder.
    ///
    /// This property shall contain measurement information for the SPDM Responder.
    MeasurementSet: core.Nullable(SpdMmeasurementSetUpdate) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// SPDM Responder measurement information.
///
/// This object shall contain SPDM Responder measurement information.
pub const SpdMmeasurementSet = struct {
    /// The measurement specification negotiated between the SPDM Requester and SPDM Responder.
    ///
    /// This property shall contain the measurement specification negotiated between the SPDM Requester and SPDM Responder.
    MeasurementSpecification: ?MeasurementSpecification = null,
    /// Measurements from an SPDM Responder.
    ///
    /// This property shall contain measurements from an SPDM Responder.
    Measurements: ?[]const ?SpdMsingleMeasurement = null,
    /// The measurement summary data.
    ///
    /// This property shall contain a Base64-encoded string, with padding characters, of the measurement summary using the hash algorithm indicated by the `MeasurementSummaryHashAlgorithm` property.
    MeasurementSummary: ?[]const u8 = null,
    /// The hash algorithm used to compute the measurement summary.
    ///
    /// This property shall contain the hash algorithm used to compute the measurement summary.  The allowable values for this property shall be the hash algorithm names found in the 'BaseHashAlgo' field of the 'NEGOTIATE_ALGORITHMS' request message in DSP0274.  If the algorithm is an extended algorithm, this property shall contain the value `OEM`.
    MeasurementSummaryHashAlgorithm: ?[]const u8 = null,
    /// The type of measurement summary.
    ///
    /// This property shall contain the type of measurement summary.
    MeasurementSummaryType: ?SpdMmeasurementSummaryType = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
};

/// What a client may change of `ComponentIntegrity.SPDMmeasurementSet`.
///
/// SPDM Responder measurement information.
pub const SpdMmeasurementSetUpdate = struct {
    /// Measurements from an SPDM Responder.
    ///
    /// This property shall contain measurements from an SPDM Responder.
    Measurements: ?[]const ?SpdMsingleMeasurementUpdate = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Authentication information of the identity of the SPDM Requester.
///
/// This object shall contain authentication information of the identity of the SPDM Requester.
pub const SpdMrequesterAuth = struct {
    /// A link to the certificate that represents the identity of the SPDM Requester provided in mutual authentication.
    ///
    /// This property shall contain a link to a resource of type `Certificate` that represents the identity of the SPDM Requester provided in mutual authentication.
    ProvidedCertificate: ?core.NavProperty(certificate.Certificate) = null,
};

pub const SpdMsingleMeasurement = struct {
    /// The index of the measurement.
    ///
    /// This property shall contain the index of the measurement.
    MeasurementIndex: ?i64 = null,
    /// Indicates whether this measurement is part of the measurement summary.
    ///
    /// This property shall indicate if this measurement is part of the measurement summary in the `MeasurementSummary` property.  If this property is not present, it shall be assumed to be `false`.
    PartofSummaryHash: ?bool = null,
    /// The date and time when information for the measurement was last updated.
    ///
    /// This property shall contain the date and time when information for the measurement was last updated.
    LastUpdated: ?core.DateTimeOffset = null,
    /// The measurement data.
    ///
    /// This property shall contain a Base64-encoded string, with padding characters, of the measurement using the hash algorithm indicated by the `MeasurementHashAlgorithm` property.  This property shall not contain a raw bit stream as a measurement.  If the SPDM Responder provides a raw bit stream, the SPDM Requester may apply a hash algorithm to the raw bit stream in order to report the measurement.
    Measurement: ?[]const u8 = null,
    /// The hash algorithm used to compute the measurement.
    ///
    /// This property shall contain the hash algorithm used to compute the measurement.  The allowable values for this property shall be the hash algorithm names found in the 'BaseHashAlgo' field of the 'NEGOTIATE_ALGORITHMS' request message in DSP0274.  If the algorithm is an extended algorithm, this property shall contain the value `OEM`.  This property shall not be present if MeasurementSpecification does not contain `DMTF`.
    MeasurementHashAlgorithm: ?[]const u8 = null,
    /// The type or characteristics of the data that this measurement represents.
    ///
    /// This property shall contain the type or characteristics of the data that this measurement represents.  This property shall not be present if MeasurementSpecification does not contain `DMTF`.
    MeasurementType: ?DmtFmeasurementTypes = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// The security version number the measurement represents.
    ///
    /// This property shall contain an 8-byte hex-encoded string of the security version number the measurement represents.  This property shall only be present if `MeasurementType` contains the value `MutableFirmwareSecurityVersionNumber`.
    SecurityVersionNumber: ?[]const u8 = null,
};

/// What a client may change of `ComponentIntegrity.SPDMsingleMeasurement`.
pub const SpdMsingleMeasurementUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

pub const SingleSessionInfo = struct {
    /// The identifier for an active session or communication channel between two components.
    ///
    /// This property shall contain the unique identifier for the active session or communication channel between two components.
    SessionId: ?i64 = null,
    /// The type of session or communication channel between two components.
    ///
    /// This property shall contain the type of session or communication channel between two components.
    SessionType: ?SecureSessionType = null,
    /// The algorithm the session is using to secure the communication channel.
    ///
    /// This property shall contain the algorithm the session is using to secure the communication channel between the SPDM Requester and the SPDM Responder.  The allowable values for this property shall be the asymmetric signature algorithm names found in the 'SPDM Asymmetric Signature Reference Information' table in DSP0274.
    SessionAlgorithm: ?[]const u8 = null,
};

/// The TPM signed measurement from a TPM.
///
/// This object shall contain the TPM signed PCR measurements from a TPM.
pub const TpmGetSignedMeasurementsResponse = struct {
    /// The Base64-encoded cryptographic signed statement generated by the signer.
    ///
    /// This property shall contain a Base64-encoded string, with padding characters, of the cryptographic signed statement generated by the signer.  This value shall be the concatenation of the 'quoted' and 'signature' response values of the 'TPM2_Quote' command defined in the Trusted Platform Module Library Specification.
    SignedMeasurements: ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
};

/// What a client may change of `ComponentIntegrity.TPMGetSignedMeasurementsResponse`.
///
/// The TPM signed measurement from a TPM.
pub const TpmGetSignedMeasurementsResponseUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

pub const TpMinfo = struct {
    /// Measurement information from the TPM.
    ///
    /// This property shall contain measurement information from the TPM.
    MeasurementSet: ?TpMmeasurementSet = null,
    /// Identity authentication information about the TPM.
    ///
    /// This property shall contain identity authentication information about the TPM.
    IdentityAuthentication: ?CommonAuthInfo = null,
    /// Information about communication with the TPM.
    ///
    /// This property shall contain information about communication with the TPM.
    ComponentCommunication: ?CommunicationInfo = null,
    /// The maximum number of bytes that can be specified in the `Nonce` parameter of the `TPMGetSignedMeasurements` action.
    ///
    /// This property shall contain the maximum number of bytes that can be specified in the `Nonce` parameter of the `TPMGetSignedMeasurements` action.
    NonceSizeBytesMaximum: ?i64 = null,
};

/// Trusted Computing Group TPM measurement information.
///
/// This object shall contain Trusted Computing Group TPM measurement information.
pub const TpMmeasurementSet = struct {
    /// Measurements from a TPM.
    ///
    /// This property shall contain measurements from a TPM.
    Measurements: ?[]const ?TpMsingleMeasurement = null,
};

/// A single Trusted Computing Group TPM measurement.
///
/// This object shall contain a single Trusted Computing Group TPM measurement.
pub const TpMsingleMeasurement = struct {
    /// The Platform Configuration Register (PCR) bank of the measurement.
    ///
    /// This property shall contain the Platform Configuration Register (PCR) bank of the measurement.
    PCR: ?i64 = null,
    /// The measurement data.
    ///
    /// This property shall contain a Base64-encoded string, with padding characters, of the PCR digest using the hashing algorithm indicated by the `MeasurementHashAlgorithm` property.
    Measurement: ?[]const u8 = null,
    /// The hash algorithm used to compute the measurement.
    ///
    /// This property shall contain the hash algorithm used to compute the measurement.  The allowable values for this property shall be the strings in the 'Algorithm Name' field of the 'TCG_ALG_ID Constants' table, formerly the 'TPM_ALG_ID Constants' table, within the 'Trusted Computing Group Algorithm Registry'.
    MeasurementHashAlgorithm: ?[]const u8 = null,
    /// The date and time when information for the measurement was last updated.
    ///
    /// This property shall contain the date and time when information for the measurement was last updated.
    LastUpdated: ?core.DateTimeOffset = null,
};

/// The `ComponentIntegrity` resource provides critical and pertinent security information about a specific device, system, software element, or other managed entity.
///
/// This resource shall represent critical and pertinent security information about a specific device, system, software element, or other managed entity.
pub const ComponentIntegrity = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: ?resource.Id = null,
    Description: ?resource.Description = null,
    Name: ?resource.Name = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// The status and health of the resource and its subordinate or dependent resources.
    ///
    /// This property shall contain any status or health properties of the resource.
    Status: ?resource.Status = null,
    /// The type of security technology for the component.
    ///
    /// This value of this property shall contain the underlying security technology providing integrity information for the component.
    ComponentIntegrityType: ?ComponentIntegrityType = null,
    /// The version of the security technology.
    ///
    /// This value of this property shall contain the version of the security technology indicated by the `ComponentIntegrityType` property.  If the service has not established secure communication with the device or if security protocols are disabled, this property shall contain an empty string.  If `ComponentIntegrityType` contains `SPDM`, this property shall contain the negotiated or selected SPDM protocol and shall follow the regular expression pattern `^\d+\.\d+\.\d+$`.  If `ComponentIntegrityType` contains `TPM`, this property shall contain the version of the TPM.
    ComponentIntegrityTypeVersion: ?[]const u8 = null,
    /// An indication of whether security protocols are enabled for the component.
    ///
    /// This property shall indicate whether security protocols are enabled for the component.  If `ComponentIntegrityType` contains `SPDM`, a value of `false` shall prohibit the SPDM Requester from using SPDM to communicate with the component identified by the `TargetComponentURI` property.  If `ComponentIntegrityType` contains `TPM`, a value of `false` shall disable the TPM component identified by the `TargetComponentURI` property entirely.  If `false`, services shall not provide the TPM and SPDM properties in response payloads for this resource.  If `false`, services shall reject action requests to this resource.  If `true`, services shall allow security protocols with the component identified by the `TargetComponentURI` property.
    ComponentIntegrityEnabled: ?bool = null,
    /// The link to the component whose integrity that this resource reports.
    ///
    /// This value of this property shall contain a link to the resource whose integrity information is reported in this resource.  If `ComponentIntegrityType` contains `SPDM`, this property shall contain a URI to the resource that represents the SPDM Responder.  If `ComponentIntegrityType` contains `TPM`, this property shall contain a URI with RFC6901-defined JSON fragment notation to a member of the TrustedModules array in a ComputerSystem resource that represents the TPM or a resource of type `TrustedComponent` that represents the TPM.
    TargetComponentURI: ?[]const u8 = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?Links = null,
    /// The date and time when information for the component was last updated.
    ///
    /// This property shall contain the date and time when information for the component was last updated.
    LastUpdated: ?core.DateTimeOffset = null,
    /// Integrity information about the SPDM Responder as reported by an SPDM Requester.
    ///
    /// This property shall contain integrity information about the SPDM Responder identified by the `TargetComponentURI` property as reported by an SPDM Requester.  This property shall be present if `ComponentIntegrityType` contains `SPDM` and if `ComponentIntegrityEnabled` contains `true`.  For other cases, this property shall be absent.
    SPDM: ?SpdMinfo = null,
    /// Integrity information about the Trusted Platform Module (TPM).
    ///
    /// This property shall contain integrity information about the Trusted Platform Module (TPM) identified by the `TargetComponentURI` property.  This property shall be present if `ComponentIntegrityType` contains `TPM` and if `ComponentIntegrityEnabled` contains `true`.  For other cases, this property shall be absent.
    TPM: ?TpMinfo = null,
};

/// What a client may change of `ComponentIntegrity.ComponentIntegrity`.
///
/// The `ComponentIntegrity` resource provides critical and pertinent security information about a specific device, system, software element, or other managed entity.
pub const ComponentIntegrityUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// An indication of whether security protocols are enabled for the component.
    ///
    /// This property shall indicate whether security protocols are enabled for the component.  If `ComponentIntegrityType` contains `SPDM`, a value of `false` shall prohibit the SPDM Requester from using SPDM to communicate with the component identified by the `TargetComponentURI` property.  If `ComponentIntegrityType` contains `TPM`, a value of `false` shall disable the TPM component identified by the `TargetComponentURI` property entirely.  If `false`, services shall not provide the TPM and SPDM properties in response payloads for this resource.  If `false`, services shall reject action requests to this resource.  If `true`, services shall allow security protocols with the component identified by the `TargetComponentURI` property.
    ComponentIntegrityEnabled: ?bool = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?LinksUpdate = null,
    /// Integrity information about the SPDM Responder as reported by an SPDM Requester.
    ///
    /// This property shall contain integrity information about the SPDM Responder identified by the `TargetComponentURI` property as reported by an SPDM Requester.  This property shall be present if `ComponentIntegrityType` contains `SPDM` and if `ComponentIntegrityEnabled` contains `true`.  For other cases, this property shall be absent.
    SPDM: ?SpdMinfoUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
