//! Namespace `ConsistencyGroupCollection`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const consistency_group = @import("consistency_group.zig");
const resource = @import("resource.zig");

/// A Collection of ConsistencyGroup resource instances.
///
/// This collection shall contain references to all ConsistencyGroup resource instances sharing the same parent resource.
pub const ConsistencyGroupCollection = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    Description: ?resource.Description = null,
    Name: ?resource.Name = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// The value of each member references a ConsistencyGroup resource.
    ///
    /// The value of each member entry shall reference a ConsistencyGroup resource.
    Members: ?[]const core.NavProperty(consistency_group.ConsistencyGroup) = null,
    /// How many members `Members` has in total, which is not how many this response carries.
    @"Members@odata.count": ?i64 = null,
    /// The next page of `Members`. Present only when this response left members out.
    @"Members@odata.nextLink": ?core.ODataId = null,
    /// The next page of `Members`, spelled the way OData spells it for a response that is itself a collection. Services use this in place of `Members@odata.nextLink`; read both.
    @"@odata.nextLink": ?core.ODataId = null,
};

test {
    std.testing.refAllDecls(@This());
}
