//! Namespace `ConsistencyGroup`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const resource = @import("resource.zig");
const storage_replica_info = @import("storage_replica_info.zig");
const volume = @import("volume.zig");

pub const ApplicationConsistencyMethod = enum {
    /// Supports consistency method commonly orchestrated using application-specific code.
    HotStandby,
    /// Supports VMware consistency requirements, such as for VASA and VVOLs.
    VASA,
    /// Supports Microsoft virtual backup device interface (VDI).
    VDI,
    /// Supports Microsoft VSS.
    VSS,
    /// Supports consistency method orchestrated using vendor-specific code.
    Other,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const ConsistencyType = enum {
    /// Requested operations are either triggered or instituted without regard to pending IO.
    CrashConsistent,
    /// Orchestration exists to either flush or halt pending IO to ensure operations occur in a transactionally consistent manner.
    ApplicationConsistent,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// Arguments to `ConsistencyGroup.AssignReplicaTarget`.
///
/// This action is used to establish a replication relationship by assigning an existing consistency group to serve as a target replica for an existing source consistency group.
pub const ConsistencyGroupAssignReplicaTargetAction = struct {
    /// The replica update mode (synchronous vs asynchronous).
    ///
    /// This parameter shall specify the replica update mode.
    ReplicaUpdateMode: ?storage_replica_info.ReplicaUpdateMode = null,
    /// The Uri to the existing target consistency group.
    ///
    /// This parameter shall contain the Uri to the existing consistency group.
    TargetConsistencyGroup: ?[]const u8 = null,
    /// The type of replica relationship to be created (e.g., Clone, Mirror, Snap).
    ///
    /// This parameter shall contain the type of replica relationship to be created.
    ReplicaType: ?storage_replica_info.ReplicaType = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Arguments to `ConsistencyGroup.CreateReplicaTarget`.
///
/// This action is used to create a new consistency group resource to provide expanded data protection through a replica relationship with the specified source consistency group.
pub const ConsistencyGroupCreateReplicaTargetAction = struct {
    /// The replica update mode (synchronous vs asynchronous).
    ///
    /// This parameter shall specify the replica update mode.
    ReplicaUpdateMode: ?storage_replica_info.ReplicaUpdateMode = null,
    /// The Name for the new target consistency group.
    ///
    /// This parameter shall contain the Name for the target consistency group.
    ConsistencyGroupName: ?[]const u8 = null,
    /// The Uri to the existing target Storage Pool.
    ///
    /// This parameter shall contain the Uri to the existing StoragePool in which to create the target consistency group.
    TargetStoragePool: ?[]const u8 = null,
    /// The type of replica relationship to be created (e.g., Clone, Mirror, Snap).
    ///
    /// This parameter shall contain the type of replica relationship to be created.
    ReplicaType: ?storage_replica_info.ReplicaType = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Arguments to `ConsistencyGroup.RemoveReplicaRelationship`.
///
/// This action is used to disable data synchronization between a source and target consistency group, remove the replication relationship, and optionally delete the target consistency group.
pub const ConsistencyGroupRemoveReplicaRelationshipAction = struct {
    /// The Uri to the existing target consistency group.
    ///
    /// This parameter shall contain the Uri to the existing target consistency group.
    TargetConsistencyGroup: ?[]const u8 = null,
    /// Indicate whether or not to delete the target consistency group as part of the operation.
    ///
    /// This parameter shall indicate whether or not to delete the target consistency group as part of the operation. If not specified, the system should use its default behavior.
    DeleteTargetConsistencyGroup: ?bool = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Arguments to `ConsistencyGroup.ResumeReplication`.
///
/// This action is used to resume the active data synchronization between a source and target consistency group, without otherwise altering the replication relationship.
pub const ConsistencyGroupResumeReplicationAction = struct {
    /// The Uri to the existing target consistency group.
    ///
    /// This parameter shall contain the Uri to the existing target consistency group.
    TargetConsistencyGroup: ?[]const u8 = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Arguments to `ConsistencyGroup.ReverseReplicationRelationship`.
///
/// This action is used to reverse the replication relationship between a source and target consistency group.
pub const ConsistencyGroupReverseReplicationRelationshipAction = struct {
    /// The Uri to the existing target consistency group.
    ///
    /// This parameter shall contain the Uri to the existing target consistency group.
    TargetConsistencyGroup: ?[]const u8 = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Arguments to `ConsistencyGroup.SplitReplication`.
///
/// This action is used to split the replication relationship and suspend data synchronization between a source and target consistency group.
pub const ConsistencyGroupSplitReplicationAction = struct {
    /// The Uri to the existing target consistency group.
    ///
    /// This parameter shall contain the Uri to the existing target consistency group.
    TargetConsistencyGroup: ?[]const u8 = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Arguments to `ConsistencyGroup.SuspendReplication`.
///
/// This action is used to suspend active data synchronization between a source and target consistency group, without otherwise altering the replication relationship.
pub const ConsistencyGroupSuspendReplicationAction = struct {
    /// The Uri to the existing target consistency group.
    ///
    /// This parameter shall contain the Uri to the existing target consistency group.
    TargetConsistencyGroup: ?[]const u8 = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available actions for this resource.
///
/// This property shall contain any actions for this resource.
pub const Actions = struct {
    /// This property contains the available OEM specific actions for this resource.
    ///
    /// This property shall contain any additional OEM actions for this resource.
    Oem: ?OemActions = null,
    /// This action is used to establish a replication relationship by assigning an existing consistency group to serve as a target replica for an existing source consistency group.
    ///
    /// This action shall be used to establish a replication relationship by assigning an existing consistency group to serve as a target replica for an existing source consistency group.
    @"#ConsistencyGroup.AssignReplicaTarget": ?core.Action(ConsistencyGroupAssignReplicaTargetAction, std.json.Value) = null,
    /// This action is used to create a new consistency group resource to provide expanded data protection through a replica relationship with the specified source consistency group.
    ///
    /// This action shall be used to create a new consistency group resource to provide expanded data protection through a replica relationship with the specified source consistency group.
    @"#ConsistencyGroup.CreateReplicaTarget": ?core.Action(ConsistencyGroupCreateReplicaTargetAction, std.json.Value) = null,
    /// This action is used to disable data synchronization between a source and target consistency group, remove the replication relationship, and optionally delete the target consistency group.
    ///
    /// This action shall be used to disable data synchronization between a source and target consistency group, remove the replication relationship, and optionally delete the target consistency group.
    @"#ConsistencyGroup.RemoveReplicaRelationship": ?core.Action(ConsistencyGroupRemoveReplicaRelationshipAction, std.json.Value) = null,
    /// This action is used to resume the active data synchronization between a source and target consistency group, without otherwise altering the replication relationship.
    ///
    /// This action shall be used to resume the active data synchronization between a source and target consistency group, without otherwise altering the replication relationship.
    @"#ConsistencyGroup.ResumeReplication": ?core.Action(ConsistencyGroupResumeReplicationAction, std.json.Value) = null,
    /// This action is used to reverse the replication relationship between a source and target consistency group.
    ///
    /// This action shall be used to reverse the replication relationship between a source and target consistency group.
    @"#ConsistencyGroup.ReverseReplicationRelationship": ?core.Action(ConsistencyGroupReverseReplicationRelationshipAction, std.json.Value) = null,
    /// This action is used to split the replication relationship and suspend data synchronization between a source and target consistency group.
    ///
    /// This action shall be used to split the replication relationship and suspend data synchronization between a source and target consistency group.
    @"#ConsistencyGroup.SplitReplication": ?core.Action(ConsistencyGroupSplitReplicationAction, std.json.Value) = null,
    /// This action is used to suspend active data synchronization between a source and target consistency group, without otherwise altering the replication relationship.
    ///
    /// This action shall be used to suspend active data synchronization between a source and target consistency group, without otherwise altering the replication relationship.
    @"#ConsistencyGroup.SuspendReplication": ?core.Action(ConsistencyGroupSuspendReplicationAction, std.json.Value) = null,

    /// This action is used to establish a replication relationship by assigning an existing consistency group to serve as a target replica for an existing source consistency group.
    ///
    /// This action shall be used to establish a replication relationship by assigning an existing consistency group to serve as a target replica for an existing source consistency group.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn assignReplicaTarget(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ConsistencyGroupAssignReplicaTargetAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#ConsistencyGroup.AssignReplicaTarget" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }

    /// This action is used to create a new consistency group resource to provide expanded data protection through a replica relationship with the specified source consistency group.
    ///
    /// This action shall be used to create a new consistency group resource to provide expanded data protection through a replica relationship with the specified source consistency group.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn createReplicaTarget(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ConsistencyGroupCreateReplicaTargetAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#ConsistencyGroup.CreateReplicaTarget" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }

    /// This action is used to disable data synchronization between a source and target consistency group, remove the replication relationship, and optionally delete the target consistency group.
    ///
    /// This action shall be used to disable data synchronization between a source and target consistency group, remove the replication relationship, and optionally delete the target consistency group.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn removeReplicaRelationship(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ConsistencyGroupRemoveReplicaRelationshipAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#ConsistencyGroup.RemoveReplicaRelationship" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }

    /// This action is used to resume the active data synchronization between a source and target consistency group, without otherwise altering the replication relationship.
    ///
    /// This action shall be used to resume the active data synchronization between a source and target consistency group, without otherwise altering the replication relationship.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn resumeReplication(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ConsistencyGroupResumeReplicationAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#ConsistencyGroup.ResumeReplication" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }

    /// This action is used to reverse the replication relationship between a source and target consistency group.
    ///
    /// This action shall be used to reverse the replication relationship between a source and target consistency group.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn reverseReplicationRelationship(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ConsistencyGroupReverseReplicationRelationshipAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#ConsistencyGroup.ReverseReplicationRelationship" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }

    /// This action is used to split the replication relationship and suspend data synchronization between a source and target consistency group.
    ///
    /// This action shall be used to split the replication relationship and suspend data synchronization between a source and target consistency group.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn splitReplication(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ConsistencyGroupSplitReplicationAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#ConsistencyGroup.SplitReplication" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }

    /// This action is used to suspend active data synchronization between a source and target consistency group, without otherwise altering the replication relationship.
    ///
    /// This action shall be used to suspend active data synchronization between a source and target consistency group, without otherwise altering the replication relationship.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn suspendReplication(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ConsistencyGroupSuspendReplicationAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#ConsistencyGroup.SuspendReplication" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }
};

/// The available OEM specific actions for this resource.
///
/// This type shall contain any additional OEM actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// A collection of volumes grouped together to ensure write order consistency across all those volumes.
///
/// A collection of volumes grouped together to ensure write order consistency across all those volumes. A management operation on a consistency group, such as configuring replication properties, applies to all the volumes within the consistency group.
pub const ConsistencyGroup = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: ?resource.Id = null,
    Description: ?resource.Description = null,
    Name: ?resource.Name = null,
    /// This value is true when the consistency group is in a consistent state.
    ///
    /// The value of this property shall be set to true when the consistency group is in a consistent state.
    IsConsistent: ?bool = null,
    /// The consistency method used by this group.
    ///
    /// The property shall set the consistency method used by this group.
    ConsistencyMethod: ?ApplicationConsistencyMethod = null,
    /// The consistency type used by this group.
    ///
    /// This property shall set the consistency type used by this group.
    ConsistencyType: ?ConsistencyType = null,
    /// The property contains the status of the ConsistencyGroup.
    ///
    /// The property shall contain the status of the ConsistencyGroup.
    Status: ?resource.Status = null,
    /// Describes this storage group in its role as a target for replication.
    ///
    /// This property shall describe the replication relationship between this storage group and a corresponding source storage group.
    ReplicaInfo: ?storage_replica_info.ReplicaInfo = null,
    /// Contains links to other resources that are related to this resource.
    ///
    /// This property shall contain links to other resources that are related to this resource.
    Links: ?resource.Links = null,
    /// The available actions for this resource.
    ///
    /// The Actions property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// URIs to the resources that are remote target replicas of this source.
    ///
    /// The value shall reference the URIs to the remote target replicas that are sourced by this replica. Remote indicates that the replica is managed by a separate Swordfish service instance.
    RemoteReplicaTargets: ?[]const ?[]const u8 = null,
    /// The resources that are target replicas of this source.
    ///
    /// The value shall reference the target replicas that are sourced by this replica.
    ReplicaTargets: ?[]const core.NavProperty(resource.Item) = null,
    /// Volumes in this storage group.
    ///
    /// An array of references to volumes managed by this storage group.
    Volumes: ?[]const core.NavProperty(volume.Volume) = null,
};

/// What a client may change of `ConsistencyGroup.ConsistencyGroup`.
///
/// A collection of volumes grouped together to ensure write order consistency across all those volumes.
pub const ConsistencyGroupUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The consistency method used by this group.
    ///
    /// The property shall set the consistency method used by this group.
    ConsistencyMethod: core.Nullable(ApplicationConsistencyMethod) = .absent,
    /// The consistency type used by this group.
    ///
    /// This property shall set the consistency type used by this group.
    ConsistencyType: core.Nullable(ConsistencyType) = .absent,
    /// Contains links to other resources that are related to this resource.
    ///
    /// This property shall contain links to other resources that are related to this resource.
    Links: ?resource.LinksUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
