//! Namespace `Control`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const physical_context = @import("physical_context.zig");
const resource = @import("resource.zig");
const sensor = @import("sensor.zig");

pub const ControlMode = enum {
    /// Set point is automatically adjusted by the service.
    ///
    /// This value shall indicate that the system or equipment will automatically make operational adjustments to the set point.
    Automatic,
    /// Set point is controlled by the user.
    ///
    /// This value shall indicate that the user controls the value of the `SetPoint` property, which shall override any automatic adjustment by the service.  In this mode, the system or equipment shall automatically make operational adjustments to meet the user-defined set point, and shall not modify the `SetPoint` value.
    Override,
    /// Set point is manually adjusted.
    ///
    /// This value shall indicate that the control is manually operated with no ability to make set point adjustments through this interface.  This value generally indicates a physical control that only allows monitoring of the set point, and therefore the `SetPoint` property for this control is likely read-only.
    Manual,
    /// The control is disabled.
    ///
    /// This value shall indicate that the control is disabled.
    Disabled,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const ControlType = enum {
    /// Temperature (C) control or thermostat.
    ///
    /// This value shall indicate a control used to regulate temperature, in degree Celsius units, either to a single set point or within a range.  The `SetPointUnits` property shall contain `Cel`.
    Temperature,
    /// Power (W) control or power limit.
    ///
    /// This value shall indicate a control used to regulate or limit maximum power consumption, in watt units, either to a single set point or within a range.  The `SetPointUnits` property shall contain `W`.
    Power,
    /// Frequency (Hz) control.
    ///
    /// This value shall indicate a control used to limit the operating frequency, in hertz units, of a device, either to a single set point or within a range.  The `SetPointUnits` property shall contain `Hz`.
    Frequency,
    /// Frequency (MHz) control.
    ///
    /// This value shall indicate a control used to limit the operating frequency, in megahertz units, of a device, either to a single set point or within a range.  The `SetPointUnits` property shall contain `MHz`.
    FrequencyMHz,
    /// Pressure (kPa) control.
    ///
    /// This value shall indicate a control used to adjust pressure in a system, in kilopascal units.  The `SetPointUnits` property shall contain `kPa`.
    ///
    /// Deprecated in v1_3_0.
    /// This value has been deprecated in favor of `PressurekPa` for units consistency with the equivalent `Sensor` resource `ReadingType` value.
    Pressure,
    /// Pressure (kPa) control.
    ///
    /// This value shall indicate a control used to adjust pressure in a system, in kilopascal units.  The `SetPointUnits` property shall contain `kPa`.
    PressurekPa,
    /// Valve (% open) control.
    ///
    /// This value shall indicate a control used to adjust a valve in a system, in percent units.  The `SetPointUnits` property shall contain `%`.  A value of `100` shall indicate the valve is completely open, and a value of `0` shall indicate the valve is completely closed.
    Valve,
    /// Percent-based control.
    ///
    /// This value shall indicate a percent-based control, in percent units.  The `SetPointUnits` property shall contain `%`.
    Percent,
    /// Duty cycle (%) control.
    ///
    /// This value shall indicate a control used to adjust the duty cycle, such as a PWM-based control, in percent units.  The `SetPointUnits` property shall contain `%`.
    DutyCycle,
    /// Linear position or distance (m) control.
    ///
    /// This value shall indicate a control used to adjust linear position or distance, in meter units.  The `SetPointUnits` property shall contain `m`.
    LinearPosition,
    /// Linear velocity (m/s) control.
    ///
    /// This value shall indicate a control used to adjust linear velocity, in meters per second units.  The `SetPointUnits` property shall contain `m/s`.
    LinearVelocity,
    /// Linear acceleration (m/s^2) control.
    ///
    /// This value shall indicate a control used to adjust linear acceleration, in meters per square second units.  The `SetPointUnits` property shall contain `m/s2`.
    LinearAcceleration,
    /// Rotational position (rad) control.
    ///
    /// This value shall indicate a control used to adjust rotational position, in radian units.  The `SetPointUnits` property shall contain `rad`.
    RotationalPosition,
    /// Rotational velocity (rad/s) control.
    ///
    /// This value shall indicate a control used to adjust rotational velocity, in radians per second units.  The `SetPointUnits` property shall contain `rad/s`.
    RotationalVelocity,
    /// Rotational acceleration (rad/s^2) control.
    ///
    /// This value shall indicate a control used to adjust rotational acceleration, in radians per square second units.  The `SetPointUnits` property shall contain `rad/s2`.
    RotationalAcceleration,
    /// Liquid flow (L/min) control.
    ///
    /// This value shall indicate a control used to adjust the volume of liquid per unit of time, in liters per minute units, that flows through a particular junction.  The `SetPointUnits` property shall contain `L/min`.
    LiquidFlowLPM,
    /// Voltage (V) control.
    ///
    /// This value shall indicate a control used to select a operating voltage, in volts units, of a device.  The `SetPointUnits` property shall contain `V`.
    Voltage,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const ImplementationType = enum {
    /// The set point can be adjusted through this interface.
    Programmable,
    /// The set point directly affects the control value.
    Direct,
    /// A physical control that cannot be adjusted through this interface.
    Monitored,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const SetPointType = enum {
    /// Control uses a single set point.
    ///
    /// This value shall indicate the control utilizes a single set point for its operation.  The `SetPoint` property shall be present for this control type.  The `SettingMin` and `SettingMax` properties shall not be present for this control type.
    Single,
    /// Control uses a range of values.
    ///
    /// This value shall indicate the control utilizes a set point range for its operation.  The `SettingMin` and `SettingMax` properties shall be present for this control type.  The `SetPoint` property shall not be present for this control type.
    Range,
    /// Control only monitors a reading.
    ///
    /// This value shall indicate the control provides only monitoring of a sensor reading, and does not provide the ability to affect the reading.  This value allows for multiple controls to be populated while only some of those controls provide a set point.  The `SetPoint,`SettingMin` and `SettingMax` properties shall not be present for this control type.  For example, a motion controller may provide both position-based and velocity-based control modes, where the selected mode provides the `SetPoint`, and the control for the non-selected mode provides only a sensor reading.
    Monitor,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// Arguments to `Control.ResetToDefaults`.
///
/// The action resets the values of writable properties to factory defaults.
pub const ControlResetToDefaultsAction = struct {
    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
    /// The action resets the values of writable properties to factory defaults.
    ///
    /// This action shall reset the values of writable properties in this resource to their default values as specified by the manufacturer.
    @"#Control.ResetToDefaults": ?core.Action(ControlResetToDefaultsAction, std.json.Value) = null,

    /// The action resets the values of writable properties to factory defaults.
    ///
    /// This action shall reset the values of writable properties in this resource to their default values as specified by the manufacturer.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn resetToDefaults(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ControlResetToDefaultsAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#Control.ResetToDefaults" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }
};

/// The details and coefficients used to operate a control loop.
///
/// This type shall describe the details of a control loop.
pub const ControlLoop = struct {
    /// The proportional coefficient.
    ///
    /// This property shall contain the coefficient for the proportional factor in a control loop.
    Proportional: ?core.Decimal = null,
    /// The integral coefficient.
    ///
    /// This property shall contain the coefficient for the integral factor in a control loop.
    Integral: ?core.Decimal = null,
    /// The differential coefficient.
    ///
    /// This property shall contain the coefficient for the differential factor in a control loop.
    Differential: ?core.Decimal = null,
    /// The date and time that the control loop coefficients were changed.
    ///
    /// This property shall contain the date and time that any of the coefficients for the control loop were last changed.
    CoefficientUpdateTime: ?core.DateTimeOffset = null,
};

/// What a client may change of `Control.ControlLoop`.
///
/// The details and coefficients used to operate a control loop.
pub const ControlLoopUpdate = struct {
    /// The proportional coefficient.
    ///
    /// This property shall contain the coefficient for the proportional factor in a control loop.
    Proportional: core.Nullable(core.Decimal) = .absent,
    /// The integral coefficient.
    ///
    /// This property shall contain the coefficient for the integral factor in a control loop.
    Integral: core.Nullable(core.Decimal) = .absent,
    /// The differential coefficient.
    ///
    /// This property shall contain the coefficient for the differential factor in a control loop.
    Differential: core.Nullable(core.Decimal) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The `Control` schema describes a control point and its properties.
///
/// This resource shall represent a control point for a Redfish implementation.
pub const Control = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: ?resource.Id = null,
    Description: ?resource.Description = null,
    Name: ?resource.Name = null,
    /// The type of control.
    ///
    /// This property shall contain the type of the control.
    ControlType: ?ControlType = null,
    /// The set point type used to operate the control.
    ///
    /// This property shall contain the type of set point definitions used to describe this control.
    SetPointType: ?SetPointType = null,
    /// The status and health of the resource and its subordinate or dependent resources.
    ///
    /// This property shall contain any status or health properties of the resource.
    Status: ?resource.Status = null,
    /// The current operating mode of the control.
    ///
    /// This property shall contain the operating mode of the control.
    ControlMode: ?ControlMode = null,
    /// The desired set point of the control.
    ///
    /// This property shall contain the desired set point control value.  The units shall follow the value of `SetPointUnits`.  If the `DefaultSetPoint` property is not supported and if a user-defined set point is not configured, the property may contain `null` in responses.
    SetPoint: ?core.Decimal = null,
    /// The minimum set point in the allowed range.
    ///
    /// This property shall contain the minimum desired set point within the acceptable range.  The service shall reject values less than the value of `AllowableMin`.  The units shall follow the value of `SetPointUnits`.
    SettingMin: ?core.Decimal = null,
    /// The maximum set point in the allowed range.
    ///
    /// This property shall contain the maximum desired set point within the acceptable range.  The service shall reject values greater than the value of `AllowableMax`.  The units shall follow the value of `SetPointUnits`.
    SettingMax: ?core.Decimal = null,
    /// The supported values for the set point.
    ///
    /// This property shall contain the supported values for this control.  The units shall follow the value of `SetPointUnits`.  This property should only be present when the set point or range has a limited set of supported values that cannot be accurately described using the `Increment` property.
    AllowableNumericValues: ?[]const ?core.Decimal = null,
    /// The units of the set point and related properties in UCUM c/s format.
    ///
    /// This property shall contain the units of the control's set point and related properties.  The value shall follow the case-sensitive symbol format defined by the Unified Code for Units of Measure (UCUM), as specified by the 'Units of measure annotation' clause of the Redfish Specification.
    SetPointUnits: ?[]const u8 = null,
    /// The maximum deviation from the set point allowed before the control will activate.
    ///
    /// This property shall contain the maximum deviation value allowed above or below the value of `SetPoint` before the control will activate.
    DeadBand: ?core.Decimal = null,
    /// The time delay in seconds before the control will activate once the value has deviated from the set point.
    ///
    /// This property shall contain the time in seconds that will elapse after the control value deviates above or below the value of `SetPoint` before the control will activate.
    ControlDelaySeconds: ?core.Decimal = null,
    /// The maximum possible setting for this control.
    ///
    /// This property shall indicate the maximum possible value of the `SetPoint` or `SettingMax` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMax` above this value.
    AllowableMax: ?core.Decimal = null,
    /// The minimum possible setting for this control.
    ///
    /// This property shall indicate the minimum possible value of the `SetPoint` or `SettingMin` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMin` below this value.
    AllowableMin: ?core.Decimal = null,
    /// The smallest increment supported for the set point.
    ///
    /// This property shall contain the smallest change allowed to the value of the `SetPoint`, `SettingMin`, or `SettingMax` properties.  The units shall follow the value of `SetPointUnits`.
    Increment: ?core.Decimal = null,
    /// The estimated percent error of measured versus actual values.
    ///
    /// This property shall contain the percent error of the measured versus actual values of the `SetPoint` property.
    ///
    /// Deprecated in v1_4_0.
    /// This property has been deprecated in favor of `SetPointAccuracy` to provide a range instead of a percentage.
    Accuracy: ?core.Decimal = null,
    /// The area or device to which this control applies.
    ///
    /// This property shall contain a description of the affected component or region within the equipment to which this control applies.
    PhysicalContext: ?physical_context.PhysicalContext = null,
    /// The usage or location within a device to which this control applies.
    ///
    /// This property shall contain a description of the usage or sub-region within the equipment to which this control applies.  This property generally differentiates multiple controls within the same `PhysicalContext` instance.
    PhysicalSubContext: ?physical_context.PhysicalSubContext = null,
    /// The implementation of the control.
    ///
    /// This property shall contain the implementation of the control.
    Implementation: ?ImplementationType = null,
    /// The date and time that the set point was changed.
    ///
    /// This property shall contain the date and time that the value of `SetPoint` was last changed.
    SetPointUpdateTime: ?core.DateTimeOffset = null,
    /// The control loop details.
    ///
    /// This property shall contain the details for the control loop described by this resource.
    ControlLoop: ?ControlLoop = null,
    /// The location information for this control.
    ///
    /// This property shall indicate the location information for this control.
    Location: ?resource.Location = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// The default set point of the control.
    ///
    /// This property shall contain the default set point control value.  The units shall follow the value of `SetPointUnits`.  Services apply this value to the `SetPoint` property under certain conditions, such as a reset of the manager or a `ResetToDefaults` action.
    DefaultSetPoint: ?core.Decimal = null,
    /// Accuracy (+/-) of the set point.
    ///
    /// This property shall contain the accuracy of the value of the `SetPoint` for this control.  The value shall be the absolute value of the maximum deviation of the `SetPoint` from its actual value.  The value shall be in units that follow the `SetPointUnits` for this control.
    SetPointAccuracy: ?core.Decimal = null,
    /// The error (difference) from the desired set point of the control.
    ///
    /// This property shall contain the error, or difference, of the related Sensor `Reading` value from the value of the `SetPoint`.  The units shall follow the value of `SetPointUnits`.
    SetPointError: ?core.Decimal = null,
    /// An array of links to resources that this control services.
    ///
    /// This property shall contain an array of links to resources that this control services.
    RelatedItem: ?[]const core.NavProperty(resource.Item) = null,
    /// How many members `RelatedItem` has in total, which is not how many this response carries.
    @"RelatedItem@odata.count": ?i64 = null,
    /// The next page of `RelatedItem`. Present only when this response left members out.
    @"RelatedItem@odata.nextLink": ?core.ODataId = null,
    /// The sensor reading associated with this control.
    ///
    /// This property shall contain the `Sensor` excerpt directly associated with this control.  The value of the `DataSourceUri` property shall reference a resource of type `Sensor`.  This property shall not be present if multiple sensors are associated with a single control.
    Sensor: ?sensor.SensorExcerpt = null,
    /// An array of links to the sensors associated with this control.
    ///
    /// This property shall contain an array of links to resources of type `Sensor` that represent the sensors related to this control.
    AssociatedSensors: ?[]const core.NavProperty(sensor.Sensor) = null,
    /// How many members `AssociatedSensors` has in total, which is not how many this response carries.
    @"AssociatedSensors@odata.count": ?i64 = null,
    /// The next page of `AssociatedSensors`. Present only when this response left members out.
    @"AssociatedSensors@odata.nextLink": ?core.ODataId = null,
};

/// What a client may change of `Control.Control`.
///
/// The `Control` schema describes a control point and its properties.
pub const ControlUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The current operating mode of the control.
    ///
    /// This property shall contain the operating mode of the control.
    ControlMode: core.Nullable(ControlMode) = .absent,
    /// The desired set point of the control.
    ///
    /// This property shall contain the desired set point control value.  The units shall follow the value of `SetPointUnits`.  If the `DefaultSetPoint` property is not supported and if a user-defined set point is not configured, the property may contain `null` in responses.
    SetPoint: core.Nullable(core.Decimal) = .absent,
    /// The minimum set point in the allowed range.
    ///
    /// This property shall contain the minimum desired set point within the acceptable range.  The service shall reject values less than the value of `AllowableMin`.  The units shall follow the value of `SetPointUnits`.
    SettingMin: core.Nullable(core.Decimal) = .absent,
    /// The maximum set point in the allowed range.
    ///
    /// This property shall contain the maximum desired set point within the acceptable range.  The service shall reject values greater than the value of `AllowableMax`.  The units shall follow the value of `SetPointUnits`.
    SettingMax: core.Nullable(core.Decimal) = .absent,
    /// The maximum deviation from the set point allowed before the control will activate.
    ///
    /// This property shall contain the maximum deviation value allowed above or below the value of `SetPoint` before the control will activate.
    DeadBand: core.Nullable(core.Decimal) = .absent,
    /// The time delay in seconds before the control will activate once the value has deviated from the set point.
    ///
    /// This property shall contain the time in seconds that will elapse after the control value deviates above or below the value of `SetPoint` before the control will activate.
    ControlDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The control loop details.
    ///
    /// This property shall contain the details for the control loop described by this resource.
    ControlLoop: ?ControlLoopUpdate = null,
    /// The location information for this control.
    ///
    /// This property shall indicate the location information for this control.
    Location: ?resource.LocationUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The `Control` schema describes a control point and its properties.
///
/// This resource shall represent a control point for a Redfish implementation.
pub const ControlExcerptSingle = struct {
    /// The link to the resource that provides the data for this control.
    ///
    /// This property shall contain a URI to the resource that provides the source of the excerpt contained within this copy.  If no source resource is implemented, meaning the excerpt represents the only available data, this property shall not be present.
    DataSourceUri: ?[]const u8 = null,
    /// The current operating mode of the control.
    ///
    /// This property shall contain the operating mode of the control.
    ControlMode: ?ControlMode = null,
    /// The desired set point of the control.
    ///
    /// This property shall contain the desired set point control value.  The units shall follow the value of `SetPointUnits`.  If the `DefaultSetPoint` property is not supported and if a user-defined set point is not configured, the property may contain `null` in responses.
    SetPoint: ?core.Decimal = null,
    /// The maximum possible setting for this control.
    ///
    /// This property shall indicate the maximum possible value of the `SetPoint` or `SettingMax` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMax` above this value.
    AllowableMax: ?core.Decimal = null,
    /// The minimum possible setting for this control.
    ///
    /// This property shall indicate the minimum possible value of the `SetPoint` or `SettingMin` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMin` below this value.
    AllowableMin: ?core.Decimal = null,
    /// The reading of the sensor associated with this control.
    ///
    /// This property shall contain the value of the `Reading` property of the `Sensor` resource directly associated with this control.  This property shall not be present if multiple sensors are associated with a single control.
    Reading: ?core.Decimal = null,
    /// The default set point of the control.
    ///
    /// This property shall contain the default set point control value.  The units shall follow the value of `SetPointUnits`.  Services apply this value to the `SetPoint` property under certain conditions, such as a reset of the manager or a `ResetToDefaults` action.
    DefaultSetPoint: ?core.Decimal = null,
};

/// The `Control` schema describes a control point and its properties.
///
/// This resource shall represent a control point for a Redfish implementation.
pub const ControlExcerptRange = struct {
    /// The link to the resource that provides the data for this control.
    ///
    /// This property shall contain a URI to the resource that provides the source of the excerpt contained within this copy.  If no source resource is implemented, meaning the excerpt represents the only available data, this property shall not be present.
    DataSourceUri: ?[]const u8 = null,
    /// The current operating mode of the control.
    ///
    /// This property shall contain the operating mode of the control.
    ControlMode: ?ControlMode = null,
    /// The minimum set point in the allowed range.
    ///
    /// This property shall contain the minimum desired set point within the acceptable range.  The service shall reject values less than the value of `AllowableMin`.  The units shall follow the value of `SetPointUnits`.
    SettingMin: ?core.Decimal = null,
    /// The maximum set point in the allowed range.
    ///
    /// This property shall contain the maximum desired set point within the acceptable range.  The service shall reject values greater than the value of `AllowableMax`.  The units shall follow the value of `SetPointUnits`.
    SettingMax: ?core.Decimal = null,
    /// The supported values for the set point.
    ///
    /// This property shall contain the supported values for this control.  The units shall follow the value of `SetPointUnits`.  This property should only be present when the set point or range has a limited set of supported values that cannot be accurately described using the `Increment` property.
    AllowableNumericValues: ?[]const ?core.Decimal = null,
    /// The maximum possible setting for this control.
    ///
    /// This property shall indicate the maximum possible value of the `SetPoint` or `SettingMax` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMax` above this value.
    AllowableMax: ?core.Decimal = null,
    /// The minimum possible setting for this control.
    ///
    /// This property shall indicate the minimum possible value of the `SetPoint` or `SettingMin` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMin` below this value.
    AllowableMin: ?core.Decimal = null,
    /// The reading of the sensor associated with this control.
    ///
    /// This property shall contain the value of the `Reading` property of the `Sensor` resource directly associated with this control.  This property shall not be present if multiple sensors are associated with a single control.
    Reading: ?core.Decimal = null,
};

/// The `Control` schema describes a control point and its properties.
///
/// This resource shall represent a control point for a Redfish implementation.
pub const ControlExcerpt = struct {
    /// The link to the resource that provides the data for this control.
    ///
    /// This property shall contain a URI to the resource that provides the source of the excerpt contained within this copy.  If no source resource is implemented, meaning the excerpt represents the only available data, this property shall not be present.
    DataSourceUri: ?[]const u8 = null,
    /// The current operating mode of the control.
    ///
    /// This property shall contain the operating mode of the control.
    ControlMode: ?ControlMode = null,
    /// The desired set point of the control.
    ///
    /// This property shall contain the desired set point control value.  The units shall follow the value of `SetPointUnits`.  If the `DefaultSetPoint` property is not supported and if a user-defined set point is not configured, the property may contain `null` in responses.
    SetPoint: ?core.Decimal = null,
    /// The minimum set point in the allowed range.
    ///
    /// This property shall contain the minimum desired set point within the acceptable range.  The service shall reject values less than the value of `AllowableMin`.  The units shall follow the value of `SetPointUnits`.
    SettingMin: ?core.Decimal = null,
    /// The maximum set point in the allowed range.
    ///
    /// This property shall contain the maximum desired set point within the acceptable range.  The service shall reject values greater than the value of `AllowableMax`.  The units shall follow the value of `SetPointUnits`.
    SettingMax: ?core.Decimal = null,
    /// The supported values for the set point.
    ///
    /// This property shall contain the supported values for this control.  The units shall follow the value of `SetPointUnits`.  This property should only be present when the set point or range has a limited set of supported values that cannot be accurately described using the `Increment` property.
    AllowableNumericValues: ?[]const ?core.Decimal = null,
    /// The units of the set point and related properties in UCUM c/s format.
    ///
    /// This property shall contain the units of the control's set point and related properties.  The value shall follow the case-sensitive symbol format defined by the Unified Code for Units of Measure (UCUM), as specified by the 'Units of measure annotation' clause of the Redfish Specification.
    SetPointUnits: ?[]const u8 = null,
    /// The maximum possible setting for this control.
    ///
    /// This property shall indicate the maximum possible value of the `SetPoint` or `SettingMax` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMax` above this value.
    AllowableMax: ?core.Decimal = null,
    /// The minimum possible setting for this control.
    ///
    /// This property shall indicate the minimum possible value of the `SetPoint` or `SettingMin` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMin` below this value.
    AllowableMin: ?core.Decimal = null,
    /// The control loop details.
    ///
    /// This property shall contain the details for the control loop described by this resource.
    ControlLoop: ?ControlLoop = null,
    /// The reading of the sensor associated with this control.
    ///
    /// This property shall contain the value of the `Reading` property of the `Sensor` resource directly associated with this control.  This property shall not be present if multiple sensors are associated with a single control.
    Reading: ?core.Decimal = null,
    /// The units of the sensor reading associated with this control.
    ///
    /// This property shall contain the units of the sensor's reading and thresholds.  This property shall not be present if multiple sensors are associated with a single control.
    ReadingUnits: ?[]const u8 = null,
    /// The default set point of the control.
    ///
    /// This property shall contain the default set point control value.  The units shall follow the value of `SetPointUnits`.  Services apply this value to the `SetPoint` property under certain conditions, such as a reset of the manager or a `ResetToDefaults` action.
    DefaultSetPoint: ?core.Decimal = null,
};

/// The `Control` schema describes a control point and its properties.
///
/// This resource shall represent a control point for a Redfish implementation.
pub const ControlExcerptSingleLoop = struct {
    /// The link to the resource that provides the data for this control.
    ///
    /// This property shall contain a URI to the resource that provides the source of the excerpt contained within this copy.  If no source resource is implemented, meaning the excerpt represents the only available data, this property shall not be present.
    DataSourceUri: ?[]const u8 = null,
    /// The current operating mode of the control.
    ///
    /// This property shall contain the operating mode of the control.
    ControlMode: ?ControlMode = null,
    /// The desired set point of the control.
    ///
    /// This property shall contain the desired set point control value.  The units shall follow the value of `SetPointUnits`.  If the `DefaultSetPoint` property is not supported and if a user-defined set point is not configured, the property may contain `null` in responses.
    SetPoint: ?core.Decimal = null,
    /// The maximum possible setting for this control.
    ///
    /// This property shall indicate the maximum possible value of the `SetPoint` or `SettingMax` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMax` above this value.
    AllowableMax: ?core.Decimal = null,
    /// The minimum possible setting for this control.
    ///
    /// This property shall indicate the minimum possible value of the `SetPoint` or `SettingMin` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMin` below this value.
    AllowableMin: ?core.Decimal = null,
    /// The control loop details.
    ///
    /// This property shall contain the details for the control loop described by this resource.
    ControlLoop: ?ControlLoop = null,
    /// The reading of the sensor associated with this control.
    ///
    /// This property shall contain the value of the `Reading` property of the `Sensor` resource directly associated with this control.  This property shall not be present if multiple sensors are associated with a single control.
    Reading: ?core.Decimal = null,
};

/// The `Control` schema describes a control point and its properties.
///
/// This resource shall represent a control point for a Redfish implementation.
pub const ControlExcerptNode = struct {
    /// The link to the resource that provides the data for this control.
    ///
    /// This property shall contain a URI to the resource that provides the source of the excerpt contained within this copy.  If no source resource is implemented, meaning the excerpt represents the only available data, this property shall not be present.
    DataSourceUri: ?[]const u8 = null,
    /// The current operating mode of the control.
    ///
    /// This property shall contain the operating mode of the control.
    ControlMode: ?ControlMode = null,
    /// The desired set point of the control.
    ///
    /// This property shall contain the desired set point control value.  The units shall follow the value of `SetPointUnits`.  If the `DefaultSetPoint` property is not supported and if a user-defined set point is not configured, the property may contain `null` in responses.
    SetPoint: ?core.Decimal = null,
    /// The units of the set point and related properties in UCUM c/s format.
    ///
    /// This property shall contain the units of the control's set point and related properties.  The value shall follow the case-sensitive symbol format defined by the Unified Code for Units of Measure (UCUM), as specified by the 'Units of measure annotation' clause of the Redfish Specification.
    SetPointUnits: ?[]const u8 = null,
    /// The maximum possible setting for this control.
    ///
    /// This property shall indicate the maximum possible value of the `SetPoint` or `SettingMax` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMax` above this value.
    AllowableMax: ?core.Decimal = null,
    /// The minimum possible setting for this control.
    ///
    /// This property shall indicate the minimum possible value of the `SetPoint` or `SettingMin` properties for this control.  Services shall not accept values for `SetPoint` or `SettingMin` below this value.
    AllowableMin: ?core.Decimal = null,
    /// The reading of the sensor associated with this control.
    ///
    /// This property shall contain the value of the `Reading` property of the `Sensor` resource directly associated with this control.  This property shall not be present if multiple sensors are associated with a single control.
    Reading: ?core.Decimal = null,
    /// The units of the sensor reading associated with this control.
    ///
    /// This property shall contain the units of the sensor's reading and thresholds.  This property shall not be present if multiple sensors are associated with a single control.
    ReadingUnits: ?[]const u8 = null,
};

test {
    std.testing.refAllDecls(@This());
}
