//! Namespace `FileShare`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const class_of_service = @import("class_of_service.zig");
const data_storage_lo_scapabilities = @import("data_storage_lo_scapabilities.zig");
const ethernet_interface_collection = @import("ethernet_interface_collection.zig");
const file_system = @import("file_system.zig");
const resource = @import("resource.zig");
const storage_replica_info = @import("storage_replica_info.zig");

/// Indicates whether quotas are enabled and enforced by this file share. A value of Soft means that quotas are enabled but not enforced, and a value of Hard means that quotas are enabled and enforced.
///
/// The value shall indicate whether quotas are enabled and enforced by this file share. If QuotaType is present, a value of Soft shall mean that quotas are enabled but not enforced, and a value of Hard shall mean that quotas are enabled and enforced.
pub const QuotaType = enum {
    /// Quotas are enabled but not enforced.
    ///
    /// This value shall indicate that quotas are enabled but not enforced.
    Soft,
    /// Quotas are enabled and enforced.
    ///
    /// This value shall indicate that quotas are enabled and enforced.
    Hard,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// This property contains the available OEM specific actions for this resource.
    ///
    /// This property shall contain any additional OEM actions for this resource.
    Oem: ?OemActions = null,
};

/// The links object contains the links to other resources that are related to this resource.
///
/// The Links property, as described by the Redfish Specification, shall contain references to resources that are related to, but not contained by (subordinate to), this resource.
pub const Links = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// A link to the ClassOfService for this file share.
    ///
    /// This value shall be a link to the ClassOfService for this file share.
    ClassOfService: ?core.NavProperty(class_of_service.ClassOfService) = null,
    /// A link to the file system containing the file share.
    ///
    /// The value shall be a link to the file system containing the file share.
    FileSystem: ?core.NavProperty(file_system.FileSystem) = null,
};

/// What a client may change of `FileShare.Links`.
///
/// The links object contains the links to other resources that are related to this resource.
pub const LinksUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available OEM specific actions for this resource.
///
/// This type shall contain any additional OEM actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// An instance of a shared set of files with a common directory structure.
///
/// This resource shall be used to represent a shared set of files with a common directory structure.
pub const FileShare = struct {
    /// Where the resource lives.
    @"@odata.id": core.ODataId,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: resource.Id,
    Description: ?resource.Description = null,
    Name: resource.Name,
    /// A path to an exported file or directory on the file system where this file share is hosted.
    ///
    /// The value of this property shall be a path (relative to the file system root) to the exported file or directory on the file system where this file share is hosted.
    FileSharePath: ?[]const u8 = null,
    /// An array of file sharing protocols supported by this file share.
    ///
    /// This property shall be an array containing entries for the file sharing protocols supported by this file share. Each entry shall specify a file sharing protocol supported by the file system.
    FileSharingProtocols: ?[]const file_system.FileProtocol = null,
    /// Indicates the status of the file share.
    ///
    /// This value of this property shall indicate the status of the file share.
    Status: ?resource.Status = null,
    /// An array of default access capabilities for the file share. The types of default access can include Read, Write, and/or Execute.
    ///
    /// The value of this property shall be an array containing entries for the default access capabilities for the file share. Each entry shall specify a default access privilege. The types of default access can include Read, Write, and/or Execute.
    DefaultAccessCapabilities: ?[]const data_storage_lo_scapabilities.StorageAccessCapability = null,
    /// Execute access is supported by the file share.
    ///
    /// The value of this property shall indicate whether Execute access is supported by the file share. The default value for this property is false.
    ExecuteSupport: ?bool = null,
    /// Root access is allowed by the file share.
    ///
    /// The value of this property shall indicate whether Root access is allowed by the file share. The default value for this property is false.
    RootAccess: ?bool = null,
    /// Defines how writes are replicated to the shared source.
    ///
    /// The value of this property shall define how writes are replicated to the shared source.
    WritePolicy: ?storage_replica_info.ReplicaUpdateMode = null,
    /// Continuous Availability is supported. Client/Server mediated recovery from network and server failure with application transparency.
    ///
    /// The value of this property shall indicate that Continuous Availability is supported. Client/Server mediated recovery from network and server failure with application transparency. This property shall be NULL unless the FileSharingProtocols property includes SMB.  The default value for this property is false.
    CASupported: ?bool = null,
    /// The maximum number of bytes that may be used by this file share.
    ///
    /// If present, the value of this property shall indicate the maximum number of bytes that may be consumed by this file share.
    FileShareTotalQuotaBytes: ?i64 = null,
    /// The number of remaining bytes that may be used by this file share.
    ///
    /// If present, the value of this property shall indicate the remaining number of bytes that may be consumed by this file share.
    FileShareRemainingQuotaBytes: ?i64 = null,
    /// An array of low space warning threshold percentages for the file share.
    ///
    /// This property shall be an array containing entries for the percentages of file share capacity at which low space warning events are be issued. A LOW_SPACE_THRESHOLD_WARNING event shall be triggered each time the remaining file share capacity value becomes less than one of the values in the array. The following shall be true: Across all CapacitySources entries, percent = (SUM(AllocatedBytes) - SUM(ConsumedBytes))/SUM(AllocatedBytes).
    LowSpaceWarningThresholdPercents: ?[]const i64 = null,
    /// Specifies the type of quota enforcement.
    ///
    /// If FileShareQuotaType is present, a value of Soft shall specify that quotas are not enforced, and a value of Hard shall specify that writes shall fail if the space consumed would exceed the value of the FileShareTotalQuotaBytes property.
    FileShareQuotaType: ?QuotaType = null,
    /// The links object contains the links to other resources that are related to this resource.
    ///
    /// The Links property, as described by the Redfish Specification, shall contain references to resources that are related to, but not contained by (subordinate to), this resource.
    Links: ?Links = null,
    /// The percentage of the capacity remaining in the FileShare.
    ///
    /// If present, this value shall return  {[(SUM(AllocatedBytes) - SUM(ConsumedBytes)]/SUM(AllocatedBytes)}*100 represented as an integer value.
    RemainingCapacityPercent: ?i64 = null,
    /// The available actions for this resource.
    ///
    /// The Actions property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// Indicates whether or not replication is enabled on the file share.
    ///
    /// The property shall indicate whether or not replication is enabled on the file share. This property shall be consistent with the state reflected at the storage pool level.
    ReplicationEnabled: ?bool = null,
    /// A link to the collection of Ethernet interfaces that provide access to this file share.
    ///
    /// The value shall be a link to an EthernetInterfaceCollection with members that provide access to the file share.
    EthernetInterfaces: ?core.NavProperty(ethernet_interface_collection.EthernetInterfaceCollection) = null,
};

/// What a client may change of `FileShare.FileShare`.
///
/// An instance of a shared set of files with a common directory structure.
pub const FileShareUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// Continuous Availability is supported. Client/Server mediated recovery from network and server failure with application transparency.
    ///
    /// The value of this property shall indicate that Continuous Availability is supported. Client/Server mediated recovery from network and server failure with application transparency. This property shall be NULL unless the FileSharingProtocols property includes SMB.  The default value for this property is false.
    CASupported: core.Nullable(bool) = .absent,
    /// The maximum number of bytes that may be used by this file share.
    ///
    /// If present, the value of this property shall indicate the maximum number of bytes that may be consumed by this file share.
    FileShareTotalQuotaBytes: core.Nullable(i64) = .absent,
    /// An array of low space warning threshold percentages for the file share.
    ///
    /// This property shall be an array containing entries for the percentages of file share capacity at which low space warning events are be issued. A LOW_SPACE_THRESHOLD_WARNING event shall be triggered each time the remaining file share capacity value becomes less than one of the values in the array. The following shall be true: Across all CapacitySources entries, percent = (SUM(AllocatedBytes) - SUM(ConsumedBytes))/SUM(AllocatedBytes).
    LowSpaceWarningThresholdPercents: core.Nullable([]const i64) = .absent,
    /// Specifies the type of quota enforcement.
    ///
    /// If FileShareQuotaType is present, a value of Soft shall specify that quotas are not enforced, and a value of Hard shall specify that writes shall fail if the space consumed would exceed the value of the FileShareTotalQuotaBytes property.
    FileShareQuotaType: core.Nullable(QuotaType) = .absent,
    /// The links object contains the links to other resources that are related to this resource.
    ///
    /// The Links property, as described by the Redfish Specification, shall contain references to resources that are related to, but not contained by (subordinate to), this resource.
    Links: ?LinksUpdate = null,
    /// Indicates whether or not replication is enabled on the file share.
    ///
    /// The property shall indicate whether or not replication is enabled on the file share. This property shall be consistent with the state reflected at the storage pool level.
    ReplicationEnabled: core.Nullable(bool) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// What a client may supply when creating an instance of `FileShare.FileShare`.
///
/// An instance of a shared set of files with a common directory structure.
pub const FileShareCreate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// Continuous Availability is supported. Client/Server mediated recovery from network and server failure with application transparency.
    ///
    /// The value of this property shall indicate that Continuous Availability is supported. Client/Server mediated recovery from network and server failure with application transparency. This property shall be NULL unless the FileSharingProtocols property includes SMB.  The default value for this property is false.
    CASupported: core.Nullable(bool) = .absent,
    /// The maximum number of bytes that may be used by this file share.
    ///
    /// If present, the value of this property shall indicate the maximum number of bytes that may be consumed by this file share.
    FileShareTotalQuotaBytes: core.Nullable(i64) = .absent,
    /// An array of low space warning threshold percentages for the file share.
    ///
    /// This property shall be an array containing entries for the percentages of file share capacity at which low space warning events are be issued. A LOW_SPACE_THRESHOLD_WARNING event shall be triggered each time the remaining file share capacity value becomes less than one of the values in the array. The following shall be true: Across all CapacitySources entries, percent = (SUM(AllocatedBytes) - SUM(ConsumedBytes))/SUM(AllocatedBytes).
    LowSpaceWarningThresholdPercents: core.Nullable([]const i64) = .absent,
    /// Specifies the type of quota enforcement.
    ///
    /// If FileShareQuotaType is present, a value of Soft shall specify that quotas are not enforced, and a value of Hard shall specify that writes shall fail if the space consumed would exceed the value of the FileShareTotalQuotaBytes property.
    FileShareQuotaType: core.Nullable(QuotaType) = .absent,
    /// The links object contains the links to other resources that are related to this resource.
    ///
    /// The Links property, as described by the Redfish Specification, shall contain references to resources that are related to, but not contained by (subordinate to), this resource.
    Links: ?LinksUpdate = null,
    /// Indicates whether or not replication is enabled on the file share.
    ///
    /// The property shall indicate whether or not replication is enabled on the file share. This property shall be consistent with the state reflected at the storage pool level.
    ReplicationEnabled: core.Nullable(bool) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
