//! Namespace `GraphicsController`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const pcie_device = @import("pcie_device.zig");
const port_collection = @import("port_collection.zig");
const processor = @import("processor.zig");
const resource = @import("resource.zig");

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
};

/// The links to other resources that are related to this resource.
///
/// This Redfish Specification-described type shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
pub const Links = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// An array of links to the processors that are a part of this graphics controller.
    ///
    /// This property shall contain an array of links to resources of type `Processor` that represent the processors that this graphics controller contains.
    Processors: ?[]const core.NavProperty(processor.Processor) = null,
    /// A link to the PCIe device that represents this graphics controller.
    ///
    /// This property shall contain a link to a resource of type `PCIeDevice` that represents this graphics controller.
    PCIeDevice: ?core.NavProperty(pcie_device.PcieDevice) = null,
};

/// What a client may change of `GraphicsController.Links`.
///
/// The links to other resources that are related to this resource.
pub const LinksUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The `GraphicsController` schema defines a graphics controller that can be used to drive one or more display devices.
///
/// This resource shall represent a graphics output device in a Redfish implementation.
pub const GraphicsController = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: ?resource.Id = null,
    Description: ?resource.Description = null,
    Name: ?resource.Name = null,
    /// The user-assigned asset tag for this graphics controller.
    ///
    /// This property shall contain the user-assigned asset tag, which is an identifying string that tracks the drive for inventory purposes.
    AssetTag: ?[]const u8 = null,
    /// The manufacturer of this graphics controller.
    ///
    /// This property shall contain the name of the organization responsible for producing the graphics controller.  This organization may be the entity from which the graphics controller is purchased, but this is not necessarily true.
    Manufacturer: ?[]const u8 = null,
    /// The product model number of this graphics controller.
    ///
    /// This property shall contain the manufacturer-provided model information of this graphics controller.
    Model: ?[]const u8 = null,
    /// The SKU for this graphics controller.
    ///
    /// This property shall contain the SKU number for this graphics controller.
    SKU: ?[]const u8 = null,
    /// The serial number for this graphics controller.
    ///
    /// This property shall contain a manufacturer-allocated number that identifies the graphics controller.
    SerialNumber: ?[]const u8 = null,
    /// The part number for this graphics controller.
    ///
    /// This property shall contain the manufacturer-provided part number for the graphics controller.
    PartNumber: ?[]const u8 = null,
    /// The spare part number of the graphics controller.
    ///
    /// This property shall contain the spare part number of the graphics controller.
    SparePartNumber: ?[]const u8 = null,
    /// The version of the graphics controller BIOS or primary graphics controller firmware.
    ///
    /// This property shall contain the version string of the currently installed and running BIOS or firmware for the graphics controller.
    BiosVersion: ?[]const u8 = null,
    /// The version of the graphics controller driver loaded in the operating system.
    ///
    /// This property shall contain the version string of the currently loaded driver for this graphics controller.
    DriverVersion: ?[]const u8 = null,
    /// The status and health of the resource and its subordinate or dependent resources.
    ///
    /// This property shall contain any status or health properties of the resource.
    Status: ?resource.Status = null,
    /// The location of the graphics controller.
    ///
    /// This property shall contain the location information of the associated graphics controller.
    Location: ?resource.Location = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?Links = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// The ports of the graphics controller.
    ///
    /// This property shall contain a link to a resource collection of type `PortCollection`.
    Ports: ?core.NavProperty(port_collection.PortCollection) = null,
};

/// What a client may change of `GraphicsController.GraphicsController`.
///
/// The `GraphicsController` schema defines a graphics controller that can be used to drive one or more display devices.
pub const GraphicsControllerUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The user-assigned asset tag for this graphics controller.
    ///
    /// This property shall contain the user-assigned asset tag, which is an identifying string that tracks the drive for inventory purposes.
    AssetTag: core.Nullable([]const u8) = .absent,
    /// The location of the graphics controller.
    ///
    /// This property shall contain the location information of the associated graphics controller.
    Location: ?resource.LocationUpdate = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?LinksUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
