//! Namespace `HeaterMetrics`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const resource = @import("resource.zig");
const sensor = @import("sensor.zig");

/// Arguments to `HeaterMetrics.ResetMetrics`.
///
/// This action resets the summary metrics related to this equipment.
pub const HeaterMetricsResetMetricsAction = struct {
    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
    /// This action resets the summary metrics related to this equipment.
    ///
    /// This action shall reset any time intervals or counted values for this equipment.
    @"#HeaterMetrics.ResetMetrics": ?core.Action(HeaterMetricsResetMetricsAction, std.json.Value) = null,

    /// This action resets the summary metrics related to this equipment.
    ///
    /// This action shall reset any time intervals or counted values for this equipment.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn resetMetrics(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: HeaterMetricsResetMetricsAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#HeaterMetrics.ResetMetrics" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The `HeaterMetrics` schema contains definitions for the metrics of a heater.
///
/// This resource shall be used to represent the metrics of a heater unit for a Redfish implementation.
pub const HeaterMetrics = struct {
    /// Where the resource lives.
    @"@odata.id": core.ODataId,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: resource.Id,
    Description: ?resource.Description = null,
    Name: resource.Name,
    /// The total number of seconds the heater was active while the device it heats was powered off.
    ///
    /// This property shall contain the total number of seconds the heater was active while the device it heats was powered off.
    PrePowerOnHeatingTimeSeconds: ?i64 = null,
    /// The total number of seconds the heater was active while the device it heats was powered on.
    ///
    /// This property shall contain the total number of seconds the heater was active while the device it heats was powered on.
    RuntimeHeatingTimeSeconds: ?i64 = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// The temperatures (in degree Celsius units) from all related sensors for this device.
    ///
    /// This property shall contain the temperatures, in degree Celsius units, for this subsystem.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Temperature`.
    TemperatureReadingsCelsius: ?[]const sensor.SensorExcerptArray = null,
    /// Power consumption (W).
    ///
    /// This property shall contain the total power consumption, in watt units, for this resource.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Power`.
    PowerWatts: ?sensor.SensorExcerptPower = null,
};

test {
    std.testing.refAllDecls(@This());
}
