//! Namespace `IPAddresses`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const resource = @import("resource.zig");

pub const PrefixLength = i64;

pub const SubnetMask = []const u8;

pub const AddressState = enum {
    /// This address is currently within both its RFC4862-defined valid and preferred lifetimes.
    Preferred,
    /// This address is currently within its valid lifetime but is now outside its RFC4862-defined preferred lifetime.
    Deprecated,
    /// This address is currently undergoing Duplicate Address Detection (DAD) testing, as defined in RFC4862, section 5.4.
    Tentative,
    /// This address has failed Duplicate Address Detection (DAD) testing, as defined in RFC4862, section 5.4, and is not currently in use.
    Failed,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const Ipv4addressOrigin = enum {
    /// A user-configured static address.
    Static,
    /// A DHCPv4 service-provided address.
    DHCP,
    /// A BOOTP service-provided address.
    BOOTP,
    /// The address is valid for only this network segment, or link.
    IPv4LinkLocal,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const Ipv6addressOrigin = enum {
    /// A static user-configured address.
    Static,
    /// A DHCPv6 service-provided address.
    DHCPv6,
    /// The address is valid for only this network segment, or link.
    LinkLocal,
    /// A stateless autoconfiguration (SLAAC) service-provided address.
    SLAAC,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const Ipv4address = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// The IPv4 address.
    ///
    /// This property shall contain an IPv4 address assigned to this interface.  If DHCPv4 is enabled on the interface, this property becomes read-only.
    Address: ?[]const u8 = null,
    /// The IPv4 subnet mask.
    ///
    /// This property shall contain the IPv4 subnet mask for this address.  If DHCPv4 is enabled on the interface, this property becomes read-only.
    SubnetMask: ?SubnetMask = null,
    /// This indicates how the address was determined.
    ///
    /// This property shall contain the IP address origin for this network interface.
    AddressOrigin: ?Ipv4addressOrigin = null,
    /// The IPv4 gateway for this address.
    ///
    /// This property shall contain the IPv4 default gateway address for this interface.  If DHCPv4 is enabled on the interface and is configured to set the IPv4 default gateway address, this property becomes read-only.  If multiple IPv4 addresses are present on the same interface, only a single default gateway is allowed.  Any additional IPv4 addresses shall not have a default gateway specified.
    Gateway: ?[]const u8 = null,
};

/// What a client may change of `IPAddresses.IPv4Address`.
pub const Ipv4addressUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The IPv4 address.
    ///
    /// This property shall contain an IPv4 address assigned to this interface.  If DHCPv4 is enabled on the interface, this property becomes read-only.
    Address: core.Nullable([]const u8) = .absent,
    /// The IPv4 subnet mask.
    ///
    /// This property shall contain the IPv4 subnet mask for this address.  If DHCPv4 is enabled on the interface, this property becomes read-only.
    SubnetMask: core.Nullable(SubnetMask) = .absent,
    /// The IPv4 gateway for this address.
    ///
    /// This property shall contain the IPv4 default gateway address for this interface.  If DHCPv4 is enabled on the interface and is configured to set the IPv4 default gateway address, this property becomes read-only.  If multiple IPv4 addresses are present on the same interface, only a single default gateway is allowed.  Any additional IPv4 addresses shall not have a default gateway specified.
    Gateway: core.Nullable([]const u8) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

pub const Ipv6address = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// The IPv6 address.
    ///
    /// This property lists an IPv6 address that is currently assigned on this interface.
    Address: ?[]const u8 = null,
    /// The IPv6 address prefix Length.
    ///
    /// This property shall contain the IPv6 address prefix length for this interface.
    PrefixLength: ?PrefixLength = null,
    /// This indicates how the address was determined.
    ///
    /// This property shall contain the IPv6 address origin for this interface.
    AddressOrigin: ?Ipv6addressOrigin = null,
    /// The current RFC4862-defined state of this address.
    ///
    /// This property shall contain the current RFC4862-defined state of this address.  Preferred and Deprecated states follow the definitions in RFC4862, section 5.5.4.  The Tentative state indicates that the address is undergoing Duplicate Address Detection (DAD), as defined in RFC4862, section 5.4.  The Failed state indicates a static address that did not pass DAD.  A static address in the Failed state is not in use on the network stack, and corrective action is required to remedy this condition.
    AddressState: ?AddressState = null,
};

/// What a client may change of `IPAddresses.IPv6Address`.
pub const Ipv6addressUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The IPv6 address.
    ///
    /// This property lists an IPv6 address that is currently assigned on this interface.
    Address: core.Nullable([]const u8) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

pub const Ipv6gatewayStaticAddress = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// A valid IPv6 address.
    ///
    /// This property provides access to a static IPv6 address that is currently assigned on a network interface.
    Address: ?[]const u8 = null,
    /// The IPv6 network prefix length, in bits, for this address.
    ///
    /// Provides the IPv6 network prefix length, in bits, for this address.
    PrefixLength: ?PrefixLength = null,
};

/// What a client may change of `IPAddresses.IPv6GatewayStaticAddress`.
pub const Ipv6gatewayStaticAddressUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// A valid IPv6 address.
    ///
    /// This property provides access to a static IPv6 address that is currently assigned on a network interface.
    Address: core.Nullable([]const u8) = .absent,
    /// The IPv6 network prefix length, in bits, for this address.
    ///
    /// Provides the IPv6 network prefix length, in bits, for this address.
    PrefixLength: core.Nullable(PrefixLength) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

pub const Ipv6staticAddress = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// A valid IPv6 address.
    ///
    /// This property provides access to a static IPv6 address that is currently assigned on a network interface.
    Address: ?[]const u8 = null,
    /// The prefix length, in bits, of this IPv6 address.
    ///
    /// This property shall contain the IPv6 network prefix length, in bits, for this address.
    PrefixLength: ?PrefixLength = null,
};

/// What a client may change of `IPAddresses.IPv6StaticAddress`.
pub const Ipv6staticAddressUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// A valid IPv6 address.
    ///
    /// This property provides access to a static IPv6 address that is currently assigned on a network interface.
    Address: core.Nullable([]const u8) = .absent,
    /// The prefix length, in bits, of this IPv6 address.
    ///
    /// This property shall contain the IPv6 network prefix length, in bits, for this address.
    PrefixLength: core.Nullable(PrefixLength) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
