//! Namespace `JsonSchemaFile`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const resource = @import("resource.zig");

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
};

/// Location information for a schema file.
///
/// This type shall describe location information for a schema file.
pub const Location = struct {
    /// The language code for the schema file.
    ///
    /// This property shall contain an RFC5646-conformant language code or the `default` string.
    Language: ?[]const u8 = null,
    /// The link to locally available URI for schema.
    ///
    /// This property shall contain a URI colocated with the Redfish service that specifies the location of the schema file, which can be retrieved using the Redfish protocol and authentication methods.  This property shall be used for only individual schema files.  The file name portion of the URI shall conform to the format specified in the Redfish Specification.
    Uri: ?[]const u8 = null,
    /// The link to an archive file, if the schema is hosted on the service in an archive file.
    ///
    /// This property shall contain a URI colocated with the Redfish service that specifies the location of the schema file, which can be retrieved using the Redfish protocol and authentication methods.  This property shall be used for only archive files, in zip or other formats.  The `ArchiveFile` value shall be the individual schema file name within the archive file.
    ArchiveUri: ?[]const u8 = null,
    /// The link to publicly available (canonical) URI for schema.
    ///
    /// This property shall contain a URI not colocated with the Redfish service that specifies the canonical location of the schema file.  This property shall be used for only individual schema files.
    PublicationUri: ?[]const u8 = null,
    /// The name of the file in the archive, if the schema is hosted on the service in an archive file.
    ///
    /// This property shall contain the file name of the individual schema file within the archive file that the `ArchiveUri` property specifies.  The file name shall conform to the Redfish Specification-described format.
    ArchiveFile: ?[]const u8 = null,
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The `JsonSchemaFile` schema contains the properties that describe the locations, as URIs, of a Redfish schema definition that a Redfish service implements or references.
///
/// This resource shall represent the schema file locator resource for a Redfish implementation.
pub const JsonSchemaFile = struct {
    /// Where the resource lives.
    @"@odata.id": core.ODataId,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: resource.Id,
    Description: ?resource.Description = null,
    Name: resource.Name,
    /// The RFC5646-conformant language codes for the available schemas.
    ///
    /// This property contains a set of RFC5646-conformant language codes.
    Languages: []const []const u8,
    /// The `@odata.type` name this schema describes.
    ///
    /// This property shall contain the `@odata.type` property value for that schema and shall conform to the Redfish Specification-specified syntax for the 'Type' property.
    Schema: []const u8,
    /// Location information for this schema file.
    ///
    /// This property shall contain the location information for this schema file.
    Location: []const Location,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
};

test {
    std.testing.refAllDecls(@This());
}
