//! Namespace `LineOfService`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const resource = @import("resource.zig");
const settings = @import("settings.zig");

/// Describes a service option.
///
/// This service option is the abstract base class for other ClassOfService and concrete lines of service.
pub const LineOfService = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The pending settings for this resource. PATCH `SettingsObject` rather than the resource itself; the service applies the result on the schedule this names.
    @"@Redfish.Settings": ?settings.Settings = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: ?resource.Id = null,
    Description: ?resource.Description = null,
    Name: ?resource.Name = null,
};

/// What a client may supply when creating an instance of `LineOfService.LineOfService`.
///
/// Describes a service option.
pub const LineOfServiceCreate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
