//! Namespace `LogEntry`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const event = @import("event.zig");
const resolution_step = @import("resolution_step.zig");
const resource = @import("resource.zig");
const settings = @import("settings.zig");

pub const LogEntryCode = []const u8;

pub const SensorType = []const u8;

pub const CxlEntryType = enum {
    /// A CXL Dynamic Capacity log entry.
    DynamicCapacity,
    /// A CXL informational log entry.
    Informational,
    /// A CXL warning log entry.
    Warning,
    /// A CXL failure log entry.
    Failure,
    /// A CXL fatal log entry.
    Fatal,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const EventSeverity = enum {
    /// Informational or operating normally.
    OK,
    /// A condition that requires attention.
    Warning,
    /// A critical condition that requires immediate attention.
    Critical,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const LogDiagnosticDataTypes = enum {
    /// Manager diagnostic data.
    Manager,
    /// Pre-OS diagnostic data.
    PreOS,
    /// Operating system (OS) diagnostic data.
    OS,
    /// OEM diagnostic data.
    OEM,
    /// UEFI Common Platform Error Record.
    ///
    /// This value shall indicate the data provided at the URI specified by the `AdditionalDataURI` property is a complete UEFI Specification-defined Common Platform Error Record.  The CPER data shall contain a Record Header and at least one Section as defined by the UEFI Specification.
    CPER,
    /// A Section of a UEFI Common Platform Error Record.
    ///
    /// This value shall indicate the data provided at the URI specified by the `AdditionalDataURI` property is a single Section of a UEFI Specification-defined Common Platform Error Record.  The CPER data shall contain one Section as defined by the UEFI Specification, with no Record Header.
    CPERSection,
    /// Device diagnostic data.
    ///
    /// This value shall indicate the data provided at the URI specified by the `AdditionalDataURI` property contains vendor-defined diagnostic data for a device.
    Device,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const LogEntryType = enum {
    /// A Redfish-defined message.
    Event,
    /// A legacy IPMI System Event Log (SEL) entry.
    SEL,
    /// An entry in an OEM-defined format.
    Oem,
    /// A CXL log entry.
    CXL,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const OriginatorTypes = enum {
    /// A client of the service created this log entry.
    Client,
    /// A process running on the service created this log entry.
    Internal,
    /// A process not running on the service but running on a supporting service, such as RDE implementations, UEFI, or host processes, created this log entry.
    SupportingService,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
};

/// Details for a CPER section or record associated with a log entry.
///
/// This object shall contain the details for a CPER section or record that is the source of a log entry.
pub const Cper = struct {
    /// The CPER Notification Type for a CPER record.
    ///
    /// This property shall contain the CPER Notification Type for a CPER record that corresponds to the contents of the `DiagnosticData` property or data retrieved from the URI specified by the `AdditionalDataURI` property.  This property shall only be present if `DiagnosticDataType` contains `CPER`.
    NotificationType: ?core.Guid = null,
    /// The CPER Section Type.
    ///
    /// This property shall contain the CPER Section Type for a CPER section that corresponds to the contents of the `DiagnosticData` property or data retrieved from the URI specified by the `AdditionalDataURI` property.  This property shall only be present if `DiagnosticDataType` contains `CPERSection`.
    SectionType: ?core.Guid = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,

    const closed = core.ClosedStruct(@This());
    pub const jsonParse = closed.jsonParse;
    pub const jsonParseFromValue = closed.jsonParseFromValue;
};

/// What a client may change of `LogEntry.CPER`.
///
/// Details for a CPER section or record associated with a log entry.
pub const CperUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

pub const Links = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// The link to the resource that caused the log entry.
    ///
    /// This property shall contain a link to the resource that caused the log entry.  For log entries that represent the creation or deletion of a resource, this property should reference the created or deleted resource and not the collection that contains the resource.
    OriginOfCondition: ?core.NavProperty(resource.Item) = null,
    /// An array of links to resources associated with this log entry.
    ///
    /// This property shall contain an array of links to resources that are related to this log entry.  It shall not contain links to `LogEntry` resources.  `RelatedLogEntries` is used to reference related log entries.  This property shall not contain the value of the `OriginOfCondition` property.
    RelatedItem: ?[]const core.NavProperty(resource.Item) = null,
    /// How many members `RelatedItem` has in total, which is not how many this response carries.
    @"RelatedItem@odata.count": ?i64 = null,
    /// The next page of `RelatedItem`. Present only when this response left members out.
    @"RelatedItem@odata.nextLink": ?core.ODataId = null,
    /// An array of links to other log entries that are related to this log entry.
    ///
    /// This property shall contain an array of links to resources of type `LogEntry` in this or other log services that are related to this log entry.  This property should be used to link a log entry indicating the resolution of a condition with a log entry for the initial condition.
    RelatedLogEntries: ?[]const core.NavProperty(LogEntry) = null,
    /// How many members `RelatedLogEntries` has in total, which is not how many this response carries.
    @"RelatedLogEntries@odata.count": ?i64 = null,
    /// The next page of `RelatedLogEntries`. Present only when this response left members out.
    @"RelatedLogEntries@odata.nextLink": ?core.ODataId = null,
};

/// What a client may change of `LogEntry.Links`.
pub const LinksUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The `LogEntry` schema defines the record format for a log.  It is designed for Redfish event logs, which utilize messages defined in a Message Registry and referenced by a `MessageId`.  For standard message definitions, see DSP2065.  Other log formats, including OEM-specific definitions and the IPMI System Event Log (SEL) are also supported.  The `EntryType` field indicates the type of log and the resource includes several additional properties dependent on the `EntryType`.
///
/// This resource shall represent the log format for log services in a Redfish implementation.
pub const LogEntry = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The pending settings for this resource. PATCH `SettingsObject` rather than the resource itself; the service applies the result on the schedule this names.
    @"@Redfish.Settings": ?settings.Settings = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: ?resource.Id = null,
    Description: ?resource.Description = null,
    Name: ?resource.Name = null,
    /// The severity of the log entry.
    ///
    /// This property shall contain the severity of the condition that created the log entry.  If `EntryType` contains `Event`, services can replace the value defined in the message registry with a value more applicable to the implementation.
    Severity: ?EventSeverity = null,
    /// The date and time when the log entry was created.
    ///
    /// This property shall contain the date and time when the log entry was created.
    Created: ?core.DateTimeOffset = null,
    /// The type of log entry.
    ///
    /// This property shall represent the type of log entry.  If the resource represents an IPMI SEL entry, the value shall contain `SEL`.  If the resource represents a Redfish event log entry, the value shall contain `Event`.  If the resource represents a CXL event record, the value shall contain `CXL`.  If the resource represents an OEM log entry format, the value shall contain `Oem`.
    EntryType: ?LogEntryType = null,
    /// The OEM-specific format of the entry.  If the entry type is `Oem`, this property contains more information about the record format from the OEM.
    ///
    /// This property shall represent the OEM-specific format of the entry.  This property shall be required if the `EntryType` value is `Oem`.
    OemRecordFormat: ?[]const u8 = null,
    /// The entry code for the log entry if the entry type is `SEL`.
    ///
    /// This property shall contain the entry code for the log entry if the `EntryType` is `SEL`.  Tables 42-1 and 42-2 of the IPMI Specification v2.0 revision 1.1 describe these enumerations.
    EntryCode: ?LogEntryCode = null,
    /// The sensor type to which the log entry pertains if the entry type is `SEL`.
    ///
    /// This property shall contain the sensor type to which the log entry pertains if the entry type is `SEL`.  Table 42-3, Sensor Type Codes, in the IPMI Specification v2.0 revision 1.1 describes these enumerations.
    SensorType: ?SensorType = null,
    /// The IPMI-defined sensor number.
    ///
    /// This property shall contain the IPMI sensor number if the value of the `EntryType` property is `SEL`.  This property should not appear in the resource for other values of `EntryType`.
    SensorNumber: ?i64 = null,
    /// The message of the log entry.  This property decodes from the entry type.  If the entry type is `Event`, this property contains a message.  If the entry type is `SEL`, this property contains an SEL-specific message.  If the entry type is `CXL`, this property contains a CXL event record.  Otherwise, this property contains an OEM-specific log entry.  In most cases, this property contains the actual log entry.
    ///
    /// This property shall contain the message of the log entry.  This property decodes from the entry type.  If the entry type is `Event`, this property contains a message.  If the entry type is `SEL`, this property contains an SEL-specific message, following the format specified in Table 32-1, SEL Event Records, in the IPMI Specification v2.0 revision 1.1.  If the entry type is `CXL`, this property contains the CXL event record as a string of hex bytes in the pattern `^([a-fA-F0-9]{2})+$`.  Otherwise, this property contains an OEM-specific log entry.  In most cases, this property contains the actual log entry.
    Message: ?[]const u8 = null,
    /// The `MessageId`, event data, or OEM-specific information.  This property decodes from the entry type.  If the entry type is `Event`, this property contains a Redfish Specification-defined `MessageId`.  If the entry type is `SEL`, this property contains the Event Data.  Otherwise, this property contains OEM-specific information.
    ///
    /// This property shall contain the `MessageId`, event data, or OEM-specific information.  This property decodes from the entry type.  If the entry type is `Event`, this property contains a Redfish Specification-defined `MessageId` property of the event.  If the entry type is `SEL`, the format should follow the pattern `^0[xX](([a-fA-F]|[0-9]){2}){4}$`, which results in a string in the form '0xNNaabbcc', where 'NN' is the EventDir/EventType byte, 'aa' is the Event Data 1 byte, 'bb' is Event Data 2 byte, 'cc' is Event Data 3 byte, corresponding with bytes 13-16 in the IPMI SEL Event Record.  If the entry type is `CXL`, this property shall not be present.  Otherwise, this property contains OEM-specific information.
    MessageId: ?[]const u8 = null,
    /// An array of message arguments that are substituted for the arguments in the message when looked up in the message registry.
    ///
    /// This property shall contain an array of message arguments that are substituted for the arguments in the message when looked up in the message registry.  It has the same semantics as the `MessageArgs` property in the Redfish `MessageRegistry` schema.  If the corresponding `ParamType` value contains `number`, the service shall convert the number to a string representation of the number.
    MessageArgs: ?[]const []const u8 = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?Links = null,
    /// The type of event recorded in this log.
    ///
    /// If present, this `LogEntry` records an event and the value shall indicate the type of event.
    ///
    /// Deprecated in v1_4_0.
    /// This property has been deprecated.  Starting with Redfish Specification v1.6 (Event v1.3), subscriptions are based on the `RegistryPrefix` and `ResourceType` properties and not on the `EventType` property.
    EventType: ?event.EventType = null,
    /// The unique instance identifier for an event.
    ///
    /// If present, this `LogEntry` records an `Event` and the value shall indicate a unique identifier for the event, the format of which is implementation dependent.
    EventId: ?[]const u8 = null,
    /// The date and time when the event occurred.
    ///
    /// If present, this `LogEntry` records an event and the value shall contain the date and time when the event occurred.
    EventTimestamp: ?core.DateTimeOffset = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// The OEM-specific entry code, if the `LogEntryCode` type is `OEM`.
    ///
    /// This property shall represent the OEM-specific Log Entry Code type of the Entry.  This property shall only be present if `EntryType` is `SEL` and `LogEntryCode` is `OEM`.
    OemLogEntryCode: ?[]const u8 = null,
    /// The OEM-specific sensor type if the sensor type is `OEM`.
    ///
    /// This property shall represent the OEM-specific sensor type of the entry.  This property shall only be used if `EntryType` is `SEL` and `SensorType` is `OEM`.
    OemSensorType: ?[]const u8 = null,
    /// An identifier that correlates events with the same cause.
    ///
    /// This property shall indicate that events are related and shall have the same value in the case where multiple event messages are produced by the same root cause.  Implementations shall use separate values for events with separate root cause.  There shall not be ordering of events implied by this property's value.
    EventGroupId: ?i64 = null,
    /// An identifier of the device that has generated the IPMI SEL Event Record.
    ///
    /// If `EntryType` is `SEL`, this property shall contain the 'Generator ID' field of the IPMI SEL Event Record.  If `EntryType` is not `SEL`, this property should not be present.
    GeneratorId: ?[]const u8 = null,
    /// The date and time when the log entry was last modified.
    ///
    /// This property shall contain the date and time when the log entry was last modified.  This property shall not appear if the log entry has not been modified since it was created.
    Modified: ?core.DateTimeOffset = null,
    /// The size of the additional data for this log entry.
    ///
    /// This property shall contain the size of the additional data retrieved from the URI specified by the `AdditionalDataURI` property for this log entry.
    AdditionalDataSizeBytes: ?i64 = null,
    /// The URI at which to access the additional data for this log entry, such as diagnostic data, image captures, or other files.
    ///
    /// This property shall contain the URI at which to access the additional data for this log entry, using the Redfish protocol and authentication methods.  If both `DiagnosticData` and `AdditionalDataURI` are present, `DiagnosticData` shall contain a Base64-encoded string, with padding characters, of the data retrieved from the URI specified by the `AdditionalDataURI` property.
    AdditionalDataURI: ?[]const u8 = null,
    /// The type of data available in the `DiagnosticData` property or retrieved from the URI specified by the `AdditionalDataURI` property.
    ///
    /// This property shall contain the type of data available in the `DiagnosticData` property or retrieved from the URI specified by the `AdditionalDataURI` property.  The `OriginOfCondition` property, if present, shall contain a link to the resource that represents the device from which the diagnostic data was collected.
    DiagnosticDataType: ?LogDiagnosticDataTypes = null,
    /// The OEM-defined type of data available in the `DiagnosticData` property or retrieved from the URI specified by the `AdditionalDataURI` property.
    ///
    /// This property shall contain the OEM-defined type of data available in the `DiagnosticData` property or retrieved from the URI specified by the `AdditionalDataURI` property.  This property shall be present if `DiagnosticDataType` is `OEM`.
    OEMDiagnosticDataType: ?[]const u8 = null,
    /// Indicates if the cause of the log entry has been resolved or repaired.
    ///
    /// This property shall contain an indication if the cause of the log entry has been resolved or repaired.  The value `true` shall indicate if the cause of the log entry has been resolved or repaired.  This property shall contain the value `false` if the log entry is still active.  The value `false` shall be the initial state.  Clients should ignore this property if `Severity` contains `OK`.
    Resolved: ?bool = null,
    /// Indicates if the log entry has been sent to the service provider.
    ///
    /// This property shall contain an indication if the log entry has been sent to the service provider.
    ServiceProviderNotified: ?bool = null,
    /// Used to provide suggestions on how to resolve the situation that caused the log entry.
    ///
    /// This property shall contain the resolution of the log entry.  Services should replace the resolution defined in the message registry with a more specific resolution in a log entry.
    Resolution: ?[]const u8 = null,
    /// The source of the log entry.
    ///
    /// This property shall contain the source of the log entry.
    Originator: ?[]const u8 = null,
    /// The type of originator data.
    ///
    /// This property shall contain the type of originator data.
    OriginatorType: ?OriginatorTypes = null,
    /// Indicates this log entry is equivalent to a more specific log entry within the same `EventGroupId`.
    ///
    /// This property shall indicate that this log entry is equivalent to another log entry, with a more specific definition, within the same `EventGroupId`.  For example, the `DriveFailed` message from the Storage Device Message Registry is more specific than the `ResourceStatusChangedCritical` message from the Resource Event Message Registry, when both occur with the same `EventGroupId`.  This property shall contain `true` if a more specific event is available, and shall contain `false` if no equivalent event exists in the same `EventGroupId`.  If this property is absent, the value shall be assumed to be `false`.
    SpecificEventExistsInGroup: ?bool = null,
    /// The count of overflow errors that occurred after this log entry.
    ///
    /// This property shall contain the count of overflow errors that occurred after this log entry.  If this log entry is the most recent log entry in the log service, this property shall not be present if no overflow errors occurred after the time of this log entry.  If this log entry is not the most recent log entry in the log service, this property shall not be present if no overflow errors occurred between the time of this log entry and the time of the next log entry.
    OverflowErrorCount: ?i64 = null,
    /// The timestamp of the first overflow captured after this log entry.
    ///
    /// This property shall contain the timestamp of the first overflow captured after this log entry.  If this log entry is the most recent log entry in the log service, this property shall not be present if no overflow errors occurred after the time of this log entry.  If this log entry is not the most recent log entry in the log service, this property shall not be present if no overflow errors occurred between the time of this log entry and the time of the next log entry.
    FirstOverflowTimestamp: ?core.DateTimeOffset = null,
    /// The timestamp of the last overflow captured after this log entry.
    ///
    /// This property shall contain the timestamp of the last overflow captured after this log entry.  If this log entry is the most recent log entry in the log service, this property shall not be present if no overflow errors occurred after the time of this log entry.  If this log entry is not the most recent log entry in the log service, this property shall not be present if no overflow errors occurred between the time of this log entry and the time of the next log entry.
    LastOverflowTimestamp: ?core.DateTimeOffset = null,
    /// The specific CXL entry type.
    ///
    /// This property shall contain the specific CXL entry type.  This property shall only be present if `EntryType` contains `CXL`.
    CXLEntryType: ?CxlEntryType = null,
    /// Indicates whether the log entry is persistent across a cold reset of the device.
    ///
    /// This property shall indicate whether the log entry is persistent across a cold reset of the device.
    Persistency: ?bool = null,
    /// Details for a CPER section or record associated with this log entry.
    ///
    /// This property shall contain the details for a CPER section or record that is the source of this log entry.
    CPER: ?Cper = null,
    /// A Base64-encoded set of diagnostic data associated with this log entry.
    ///
    /// This property shall contain a Base64-encoded string, with padding characters, that represents diagnostic data associated with this log entry.  The contents shall depend on the value of the `DiagnosticDataType` property.  The length of the value should not exceed 4 KB.  Larger diagnostic data payloads should omit this property and use the `AdditionalDataURI` property to reference the data.  If both `DiagnosticData` and `AdditionalDataURI` are present, `DiagnosticData` shall contain the Base64-encoding of the data retrieved from the URI specified by the `AdditionalDataURI` property.
    DiagnosticData: ?[]const u8 = null,
    /// The list of recommended steps to resolve the cause of the log entry.
    ///
    /// This property shall contain an array of recommended steps to resolve the cause of the log entry.  This property shall not be present if the `Severity` property contains `OK`.  A client can stop executing the resolution steps once the `Resolved` property resource contains `true` or the `Health` property in the associated resource referenced by the `OriginOfCondition` property contains `OK`.
    ResolutionSteps: ?[]const resolution_step.ResolutionStep = null,
    /// The username of the account associated with the log entry.
    ///
    /// This property shall contain the username of the account associated with the log entry.  This should be used for audit logs that result from a user action.
    Username: ?[]const u8 = null,
    /// The source of authentication for the username property associated with the log entry.
    ///
    /// This property shall contain the URL to the authentication service that is associated with the username property.  This should be used for audit logs that result from a user action.
    UserAuthenticationSource: ?[]const u8 = null,
    /// The serial number associated with the source of this log entry.
    ///
    /// This property shall contain a manufacturer-allocated number that identifies the source of this log entry.
    SerialNumber: ?[]const u8 = null,
    /// The part number associated with the source of this log entry.
    ///
    /// This property shall contain the manufacturer-provided part number for the source of this log entry.
    PartNumber: ?[]const u8 = null,
    /// Indicates whether the `OriginOfCondition` link is unavailable, such as after the deletion of the resource.
    ///
    /// This property shall indicate whether the `OriginOfCondition` link is unavailable.  If `true`, services shall not expand the `OriginOfCondition` link.  If this property is not present, the value shall be assumed to be `false`.
    OriginOfConditionUnavailable: ?bool = null,
    /// The IP address, with scheme, of the user associated with the log entry.
    ///
    /// This property shall contain the IP address, with scheme, of the user associated with the log entry.  This should be used for audit logs that result from a user action.
    OriginAddress: ?[]const u8 = null,

    const closed = core.ClosedStruct(@This());
    pub const jsonParse = closed.jsonParse;
    pub const jsonParseFromValue = closed.jsonParseFromValue;
};

/// What a client may change of `LogEntry.LogEntry`.
///
/// The `LogEntry` schema defines the record format for a log.  It is designed for Redfish event logs, which utilize messages defined in a Message Registry and referenced by a `MessageId`.  For standard message definitions, see DSP2065.  Other log formats, including OEM-specific definitions and the IPMI System Event Log (SEL) are also supported.  The `EntryType` field indicates the type of log and the resource includes several additional properties dependent on the `EntryType`.
pub const LogEntryUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?LinksUpdate = null,
    /// Indicates if the cause of the log entry has been resolved or repaired.
    ///
    /// This property shall contain an indication if the cause of the log entry has been resolved or repaired.  The value `true` shall indicate if the cause of the log entry has been resolved or repaired.  This property shall contain the value `false` if the log entry is still active.  The value `false` shall be the initial state.  Clients should ignore this property if `Severity` contains `OK`.
    Resolved: core.Nullable(bool) = .absent,
    /// Details for a CPER section or record associated with this log entry.
    ///
    /// This property shall contain the details for a CPER section or record that is the source of this log entry.
    CPER: ?CperUpdate = null,
    /// The list of recommended steps to resolve the cause of the log entry.
    ///
    /// This property shall contain an array of recommended steps to resolve the cause of the log entry.  This property shall not be present if the `Severity` property contains `OK`.  A client can stop executing the resolution steps once the `Resolved` property resource contains `true` or the `Health` property in the associated resource referenced by the `OriginOfCondition` property contains `OK`.
    ResolutionSteps: ?[]const resolution_step.ResolutionStepUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// What a client may supply when creating an instance of `LogEntry.LogEntry`.
///
/// The `LogEntry` schema defines the record format for a log.  It is designed for Redfish event logs, which utilize messages defined in a Message Registry and referenced by a `MessageId`.  For standard message definitions, see DSP2065.  Other log formats, including OEM-specific definitions and the IPMI System Event Log (SEL) are also supported.  The `EntryType` field indicates the type of log and the resource includes several additional properties dependent on the `EntryType`.
pub const LogEntryCreate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The type of log entry.
    ///
    /// This property shall represent the type of log entry.  If the resource represents an IPMI SEL entry, the value shall contain `SEL`.  If the resource represents a Redfish event log entry, the value shall contain `Event`.  If the resource represents a CXL event record, the value shall contain `CXL`.  If the resource represents an OEM log entry format, the value shall contain `Oem`.
    EntryType: LogEntryType,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?LinksUpdate = null,
    /// Indicates if the cause of the log entry has been resolved or repaired.
    ///
    /// This property shall contain an indication if the cause of the log entry has been resolved or repaired.  The value `true` shall indicate if the cause of the log entry has been resolved or repaired.  This property shall contain the value `false` if the log entry is still active.  The value `false` shall be the initial state.  Clients should ignore this property if `Severity` contains `OK`.
    Resolved: core.Nullable(bool) = .absent,
    /// Details for a CPER section or record associated with this log entry.
    ///
    /// This property shall contain the details for a CPER section or record that is the source of this log entry.
    CPER: ?CperUpdate = null,
    /// The list of recommended steps to resolve the cause of the log entry.
    ///
    /// This property shall contain an array of recommended steps to resolve the cause of the log entry.  This property shall not be present if the `Severity` property contains `OK`.  A client can stop executing the resolution steps once the `Resolved` property resource contains `true` or the `Health` property in the associated resource referenced by the `OriginOfCondition` property contains `OK`.
    ResolutionSteps: ?[]const resolution_step.ResolutionStepUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
