//! Namespace `ManagerDiagnosticData`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const resource = @import("resource.zig");

/// Arguments to `ManagerDiagnosticData.ResetMetrics`.
///
/// Resets time intervals or counted values of the diagnostic data for this manager.
pub const ManagerDiagnosticDataResetMetricsAction = struct {
    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
    /// Resets time intervals or counted values of the diagnostic data for this manager.
    ///
    /// This action shall reset any time intervals or counted values of the diagnostic data for this manager.
    @"#ManagerDiagnosticData.ResetMetrics": ?core.Action(ManagerDiagnosticDataResetMetricsAction, std.json.Value) = null,

    /// Resets time intervals or counted values of the diagnostic data for this manager.
    ///
    /// This action shall reset any time intervals or counted values of the diagnostic data for this manager.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn resetMetrics(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ManagerDiagnosticDataResetMetricsAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#ManagerDiagnosticData.ResetMetrics" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }
};

/// The boot-time statistics of a manager.
///
/// This object shall contain the boot-time statistics of a manager.
pub const BootTimeStatistics = struct {
    /// The number of seconds the manager spent in the firmware stage.
    ///
    /// This property shall contain the number of seconds the manager spent in the firmware stage.
    FirmwareTimeSeconds: ?core.Decimal = null,
    /// The number of seconds the manager spent in the loader stage.
    ///
    /// This property shall contain the number of seconds the manager spent in the loader stage.
    LoaderTimeSeconds: ?core.Decimal = null,
    /// The number of seconds the manager spent in the kernel stage.
    ///
    /// This property shall contain the number of seconds the manager spent in the kernel stage.
    KernelTimeSeconds: ?core.Decimal = null,
    /// The number of seconds the manager spent in the initrd boot stage.
    ///
    /// This property shall contain the number of seconds the manager spent in the initrd boot stage.
    InitrdTimeSeconds: ?core.Decimal = null,
    /// The number of seconds the manager spent in the user space boot stage.
    ///
    /// This property shall contain the number of seconds the manager spent in the user space boot stage.
    UserSpaceTimeSeconds: ?core.Decimal = null,
};

/// The statistics of an I2C bus.
///
/// This object shall contain statistics of an I2C bus.
pub const I2cBusStatistics = struct {
    /// The name of the I2C bus.
    ///
    /// This property shall contain the name of the I2C bus.
    I2CBusName: ?[]const u8 = null,
    /// The total number of transactions on this I2C bus.
    ///
    /// This property shall contain the total number of transactions on this I2C bus.  The count shall include the number of I2C transactions initiated by the manager and the number of I2C transactions where the manager is the target device.
    TotalTransactionCount: ?i64 = null,
    /// The number of bus errors on this I2C bus.
    ///
    /// This property shall contain the number of bus errors on this I2C bus.  Bus errors include, but are not limited to, an SDA rising or falling edge while SCL is high or a stuck bus signal.
    BusErrorCount: ?i64 = null,
    /// The number of NACKs on this I2C bus.
    ///
    /// This property shall contain the number of NACKs on this I2C bus.
    NACKCount: ?i64 = null,
};

/// The memory ECC statistics of a manager.
///
/// This object shall contain the memory ECC statistics of a manager.
pub const MemoryEccStatistics = struct {
    /// The number of correctable errors since reset.
    ///
    /// This property shall contain the number of correctable errors since reset.
    CorrectableECCErrorCount: ?i64 = null,
    /// The number of uncorrectable errors since reset.
    ///
    /// This property shall contain the number of uncorrectable errors since reset.
    UncorrectableECCErrorCount: ?i64 = null,
};

/// The memory statistics of a manager.
///
/// This object shall contain the memory statistics of a manager.
pub const MemoryStatistics = struct {
    /// The total amount of memory in bytes.
    ///
    /// This property shall contain the total amount of memory in bytes.
    TotalBytes: ?i64 = null,
    /// The amount of used memory in bytes.
    ///
    /// This property shall contain the amount of used memory in bytes.  This value is calculated as `TotalBytes` minus `FreeBytes` minus `BuffersAndCacheBytes`.
    UsedBytes: ?i64 = null,
    /// The amount of free memory in bytes.
    ///
    /// This property shall contain the amount of free memory in bytes.
    FreeBytes: ?i64 = null,
    /// The amount of shared memory in bytes.
    ///
    /// This property shall contain the amount of shared memory in bytes.  This includes things such as memory consumed by temporary file systems.
    SharedBytes: ?i64 = null,
    /// The amount of memory used in bytes by kernel buffers, page caches, and slabs.
    ///
    /// This property shall contain the amount of memory used in bytes by kernel buffers, page caches, and slabs.
    BuffersAndCacheBytes: ?i64 = null,
    /// The amount of memory available in bytes for starting new processes without swapping.
    ///
    /// This property shall contain the amount of memory available in bytes for starting new processes without swapping.  This includes free memory and reclaimable cache and buffers.
    AvailableBytes: ?i64 = null,
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

pub const ProcessStatistics = struct {
    /// The command line of this process.
    ///
    /// This property shall contain the command line with parameters of this process.
    CommandLine: ?[]const u8 = null,
    /// The number of seconds this process executed in user space.
    ///
    /// This property shall contain the number of seconds this process executed in user space.
    UserTimeSeconds: ?core.Decimal = null,
    /// The number of seconds this process executed in kernel space.
    ///
    /// This property shall contain the number of seconds this process executed in kernel space.
    KernelTimeSeconds: ?core.Decimal = null,
    /// The resident set size of this process in bytes.
    ///
    /// This property shall contain the resident set size of this process in bytes, which is the amount of memory allocated to the process and is in RAM.
    ResidentSetSizeBytes: ?i64 = null,
    /// The wall-clock time this process has been running in seconds.
    ///
    /// This property shall contain the wall-clock time this process has been running in seconds.
    UptimeSeconds: ?core.Decimal = null,
    /// The number of times this process has restarted.
    ///
    /// This property shall contain the number of times this process has restarted with the same command line including arguments.
    RestartCount: ?i64 = null,
    /// The number of times this process has restarted unexpectedly.
    ///
    /// This property shall contain the number of times this process has restarted unexpectedly, such as due to unintentional failures, restarts, or shutdowns, with the same command line including arguments.
    RestartAfterFailureCount: ?i64 = null,
};

/// The processor statistics of a manager.
///
/// This object shall contain the processor statistics of a manager.
pub const ProcessorStatistics = struct {
    /// The percentage of CPU time spent in kernel mode.
    ///
    /// This property shall contain the percentage of CPU time, `0` to `100`, spent in kernel mode.
    KernelPercent: ?core.Decimal = null,
    /// The percentage of CPU time spent in user mode.
    ///
    /// This property shall contain the percentage of CPU time, `0` to `100`, spent in user mode.
    UserPercent: ?core.Decimal = null,
};

/// The `ManagerDiagnosticData` schema defines internal diagnostic data for a manager.  It contains information that might be used by vendors to collect debug information about the manager.  Clients should not make decisions for raising alerts, creating service events, or other actions based on information in this resource.
///
/// This resource shall represent internal diagnostic data for a manager for a Redfish implementation.  Clients should not make decisions for raising alerts, creating service events, or other actions based on information in this resource.
pub const ManagerDiagnosticData = struct {
    /// Where the resource lives.
    @"@odata.id": core.ODataId,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: resource.Id,
    Description: ?resource.Description = null,
    Name: resource.Name,
    /// The statistics of the I2C buses.
    ///
    /// This property shall contain the statistics of the I2C buses.  Services may subdivide a physical bus into multiple entries in this property based on how the manager tracks bus segments, virtual buses from a controller, and other segmentation capabilities.
    I2CBuses: ?[]const I2cBusStatistics = null,
    /// The memory statistics of the manager.
    ///
    /// This property shall contain the memory statistics of the manager.
    MemoryStatistics: ?MemoryStatistics = null,
    /// The processor statistics of the manager.
    ///
    /// This property shall contain the processor statistics of the manager.
    ProcessorStatistics: ?ProcessorStatistics = null,
    /// The boot-time statistics of the manager.
    ///
    /// This property shall contain the boot-time statistics of the manager.
    BootTimeStatistics: ?BootTimeStatistics = null,
    /// The available storage space on this manager in kibibytes (KiB).
    ///
    /// This property shall contain the available storage space on this manager in kibibytes (KiB).
    FreeStorageSpaceKiB: ?i64 = null,
    /// The memory ECC statistics of the manager.
    ///
    /// This property shall contain the memory ECC statistics of the manager.
    MemoryECCStatistics: ?MemoryEccStatistics = null,
    /// The statistics of the top processes of this manager.
    ///
    /// This property shall contain the statistics of the top processes of this manager.
    TopProcesses: ?[]const ProcessStatistics = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// The wall-clock time the service root hosted by this manager has been running in seconds.
    ///
    /// This property shall contain the wall-clock time the service root hosted by this manager has been running in seconds.
    ServiceRootUptimeSeconds: ?core.Decimal = null,
};

test {
    std.testing.refAllDecls(@This());
}
