//! Namespace `MetricReportDefinitionCollection`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const metric_report_definition = @import("metric_report_definition.zig");
const resource = @import("resource.zig");

/// The collection of `MetricReportDefinition` resource instances.
///
/// This resource shall represent a resource collection of `MetricReportDefinition` instances for a Redfish implementation.
pub const MetricReportDefinitionCollection = struct {
    /// Where the resource lives.
    @"@odata.id": core.ODataId,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    Description: ?resource.Description = null,
    Name: resource.Name,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// The members of this collection.
    ///
    /// This property shall contain an array of links to the members of this collection.
    Members: []const core.NavProperty(metric_report_definition.MetricReportDefinition),
};

test {
    std.testing.refAllDecls(@This());
}
