//! Namespace `OutletGroup`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const circuit = @import("circuit.zig");
const outlet = @import("outlet.zig");
const resource = @import("resource.zig");
const sensor = @import("sensor.zig");

pub const OutletGroupType = enum {
    /// A group that is hardware-defined.
    ///
    /// This value shall represent an outlet group that is hardware-defined.
    HardwareDefined,
    /// A group that is user-defined.
    ///
    /// This value shall represent an outlet group that is user-defined.
    UserDefined,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// Arguments to `OutletGroup.PowerControl`.
///
/// This action turns the outlet group on or off.
pub const OutletGroupPowerControlAction = struct {
    /// The desired power state of the outlet group.
    ///
    /// This parameter shall contain the desired power state of the outlet group.
    PowerState: ?circuit.PowerState = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// Arguments to `OutletGroup.ResetMetrics`.
///
/// This action resets metrics related to this outlet group.
pub const OutletGroupResetMetricsAction = struct {
    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
    /// This action turns the outlet group on or off.
    ///
    /// This action shall control the power state of the outlet group.
    @"#OutletGroup.PowerControl": ?core.Action(OutletGroupPowerControlAction, std.json.Value) = null,
    /// This action resets metrics related to this outlet group.
    ///
    /// This action shall reset any time intervals or counted values for this outlet group.
    @"#OutletGroup.ResetMetrics": ?core.Action(OutletGroupResetMetricsAction, std.json.Value) = null,

    /// This action turns the outlet group on or off.
    ///
    /// This action shall control the power state of the outlet group.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn powerControl(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: OutletGroupPowerControlAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#OutletGroup.PowerControl" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }

    /// This action resets metrics related to this outlet group.
    ///
    /// This action shall reset any time intervals or counted values for this outlet group.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn resetMetrics(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: OutletGroupResetMetricsAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#OutletGroup.ResetMetrics" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }
};

pub const Links = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    /// The set of outlets in this outlet group.
    ///
    /// This property shall be an array of links to resources of type `Outlet` that represent the outlets in this outlet group.
    Outlets: ?[]const core.NavProperty(outlet.Outlet) = null,
    /// The set of outlet groups in this outlet group.
    ///
    /// This property shall be an array of links to resources of type `OutletGroup` that represent the outlet groups in this outlet group.  This allows representation of a group of outlet groups.  The outlet groups referenced by this property shall not contain other outlet groups.  Services shall only populate either the link for `Outlets` or `OutletGroups`, but not both.
    OutletGroups: ?[]const core.NavProperty(OutletGroup) = null,
};

/// What a client may change of `OutletGroup.Links`.
pub const LinksUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The `OutletGroup` schema contains definitions for an electrical outlet group.
///
/// This resource shall be used to represent an electrical outlet group for a Redfish implementation.
pub const OutletGroup = struct {
    /// Where the resource lives.
    @"@odata.id": core.ODataId,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: resource.Id,
    Description: ?resource.Description = null,
    Name: resource.Name,
    /// The status and health of the resource and its subordinate or dependent resources.
    ///
    /// This property shall contain any status or health properties of the resource.
    Status: ?resource.Status = null,
    /// The creator of this outlet group.
    ///
    /// This property shall contain the name of the person or application that created this outlet group.
    CreatedBy: ?[]const u8 = null,
    /// The number of seconds to delay power up after a power cycle or a `PowerControl` action.  Zero seconds indicates no delay to power up.
    ///
    /// This property shall contain the number of seconds to delay power up after a power cycle or a `PowerControl` action.  The value `0` shall indicate no delay to power up.
    PowerOnDelaySeconds: ?core.Decimal = null,
    /// The number of seconds to delay power off after a `PowerControl` action.  Zero seconds indicates no delay to power off.
    ///
    /// This property shall contain the number of seconds to delay power off after a `PowerControl` action.  The value `0` shall indicate no delay to power off.
    PowerOffDelaySeconds: ?core.Decimal = null,
    /// The number of seconds to delay power on after a `PowerControl` action to cycle power.  Zero seconds indicates no delay.
    ///
    /// This property shall contain the number of seconds to delay power on after a `PowerControl` action to cycle power.  The value `0` shall indicate no delay to power on.
    PowerCycleDelaySeconds: ?core.Decimal = null,
    /// The number of seconds to delay power on after power has been restored.  Zero seconds indicates no delay.
    ///
    /// This property shall contain the number of seconds to delay power on after a power fault.  The value `0` shall indicate no delay to power on.
    PowerRestoreDelaySeconds: ?core.Decimal = null,
    /// The desired power state of the outlet group when power is restored after a power loss.
    ///
    /// This property shall contain the desired `PowerState` of the outlet group when power is applied.  The value `LastState` shall return the outlet group to the `PowerState` it was in when power was lost.
    PowerRestorePolicy: ?circuit.PowerRestorePolicyTypes = null,
    /// The power state of the outlet group.
    ///
    /// This property shall contain the power state of the outlet group.
    PowerState: ?resource.PowerState = null,
    /// Indicates if the outlet group can be powered.
    ///
    /// This property shall contain the power enable state of the outlet group.  The value `true` shall indicate that the group can be powered on, and the value `false` shall indicate that the group cannot be powered.
    PowerEnabled: ?bool = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?Links = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// Indicates whether power control requests are locked.
    ///
    /// This property shall indicate whether requests to the `PowerControl` action are locked.  If `true`, services shall reject requests to the `PowerControl` action.
    PowerControlLocked: ?bool = null,
    /// Indicates whether the configuration is locked.
    ///
    /// This property shall indicate whether modification requests to this resource are not permitted.  If `true`, services shall reject modification requests to other properties in this resource.
    ConfigurationLocked: ?bool = null,
    /// Indicates whether the power state is undergoing a delayed transition.
    ///
    /// This property shall indicate whether the `PowerState` property will undergo a transition between on and off states due to a configured delay.  The transition may be due to the configuration of the power on, off, or restore delay properties.  If `true`, the `PowerState` property will transition at the conclusion of a configured delay.
    PowerStateInTransition: ?bool = null,
    /// The type of outlet group that this resource represents.
    ///
    /// This property shall describe the type of this outlet group.
    OutletGroupType: ?OutletGroupType = null,
    /// The power (W) for this outlet group.
    ///
    /// This property shall contain the total power, in watt units, for this outlet group that represents the `Total` `ElectricalContext` sensor when multiple power sensors exist for this outlet group.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Power`.
    PowerWatts: ?sensor.SensorExcerptPower = null,
    /// The energy (kWh) for this outlet group.
    ///
    /// This property shall contain the total energy, in kilowatt-hour units, for this outlet group that represents the `Total` `ElectricalContext` sensor when multiple energy sensors exist for this outlet group.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `EnergykWh`.
    EnergykWh: ?sensor.SensorExcerptEnergykWh = null,
};

/// What a client may change of `OutletGroup.OutletGroup`.
///
/// The `OutletGroup` schema contains definitions for an electrical outlet group.
pub const OutletGroupUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The creator of this outlet group.
    ///
    /// This property shall contain the name of the person or application that created this outlet group.
    CreatedBy: core.Nullable([]const u8) = .absent,
    /// The number of seconds to delay power up after a power cycle or a `PowerControl` action.  Zero seconds indicates no delay to power up.
    ///
    /// This property shall contain the number of seconds to delay power up after a power cycle or a `PowerControl` action.  The value `0` shall indicate no delay to power up.
    PowerOnDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The number of seconds to delay power off after a `PowerControl` action.  Zero seconds indicates no delay to power off.
    ///
    /// This property shall contain the number of seconds to delay power off after a `PowerControl` action.  The value `0` shall indicate no delay to power off.
    PowerOffDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The number of seconds to delay power on after a `PowerControl` action to cycle power.  Zero seconds indicates no delay.
    ///
    /// This property shall contain the number of seconds to delay power on after a `PowerControl` action to cycle power.  The value `0` shall indicate no delay to power on.
    PowerCycleDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The number of seconds to delay power on after power has been restored.  Zero seconds indicates no delay.
    ///
    /// This property shall contain the number of seconds to delay power on after a power fault.  The value `0` shall indicate no delay to power on.
    PowerRestoreDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The desired power state of the outlet group when power is restored after a power loss.
    ///
    /// This property shall contain the desired `PowerState` of the outlet group when power is applied.  The value `LastState` shall return the outlet group to the `PowerState` it was in when power was lost.
    PowerRestorePolicy: ?circuit.PowerRestorePolicyTypes = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?LinksUpdate = null,
    /// Indicates whether power control requests are locked.
    ///
    /// This property shall indicate whether requests to the `PowerControl` action are locked.  If `true`, services shall reject requests to the `PowerControl` action.
    PowerControlLocked: ?bool = null,
    /// Indicates whether the configuration is locked.
    ///
    /// This property shall indicate whether modification requests to this resource are not permitted.  If `true`, services shall reject modification requests to other properties in this resource.
    ConfigurationLocked: ?bool = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// What a client may supply when creating an instance of `OutletGroup.OutletGroup`.
///
/// The `OutletGroup` schema contains definitions for an electrical outlet group.
pub const OutletGroupCreate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// The creator of this outlet group.
    ///
    /// This property shall contain the name of the person or application that created this outlet group.
    CreatedBy: core.Nullable([]const u8) = .absent,
    /// The number of seconds to delay power up after a power cycle or a `PowerControl` action.  Zero seconds indicates no delay to power up.
    ///
    /// This property shall contain the number of seconds to delay power up after a power cycle or a `PowerControl` action.  The value `0` shall indicate no delay to power up.
    PowerOnDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The number of seconds to delay power off after a `PowerControl` action.  Zero seconds indicates no delay to power off.
    ///
    /// This property shall contain the number of seconds to delay power off after a `PowerControl` action.  The value `0` shall indicate no delay to power off.
    PowerOffDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The number of seconds to delay power on after a `PowerControl` action to cycle power.  Zero seconds indicates no delay.
    ///
    /// This property shall contain the number of seconds to delay power on after a `PowerControl` action to cycle power.  The value `0` shall indicate no delay to power on.
    PowerCycleDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The number of seconds to delay power on after power has been restored.  Zero seconds indicates no delay.
    ///
    /// This property shall contain the number of seconds to delay power on after a power fault.  The value `0` shall indicate no delay to power on.
    PowerRestoreDelaySeconds: core.Nullable(core.Decimal) = .absent,
    /// The desired power state of the outlet group when power is restored after a power loss.
    ///
    /// This property shall contain the desired `PowerState` of the outlet group when power is applied.  The value `LastState` shall return the outlet group to the `PowerState` it was in when power was lost.
    PowerRestorePolicy: ?circuit.PowerRestorePolicyTypes = null,
    /// The links to other resources that are related to this resource.
    ///
    /// This property shall contain links to resources that are related to but are not contained by, or subordinate to, this resource.
    Links: ?LinksUpdate = null,
    /// Indicates whether power control requests are locked.
    ///
    /// This property shall indicate whether requests to the `PowerControl` action are locked.  If `true`, services shall reject requests to the `PowerControl` action.
    PowerControlLocked: ?bool = null,
    /// Indicates whether the configuration is locked.
    ///
    /// This property shall indicate whether modification requests to this resource are not permitted.  If `true`, services shall reject modification requests to other properties in this resource.
    ConfigurationLocked: ?bool = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
