//! Namespace `ProcessorMetrics`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const pcie_device = @import("pcie_device.zig");
const resource = @import("resource.zig");
const sensor = @import("sensor.zig");
const settings = @import("settings.zig");

/// Arguments to `ProcessorMetrics.ClearCurrentPeriod`.
///
/// This action sets the `CurrentPeriod` property's values to 0.
pub const ProcessorMetricsClearCurrentPeriodAction = struct {
    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
    /// This action sets the `CurrentPeriod` property's values to 0.
    ///
    /// This action shall set the `CurrentPeriod` property's values to 0.
    @"#ProcessorMetrics.ClearCurrentPeriod": ?core.Action(ProcessorMetricsClearCurrentPeriodAction, std.json.Value) = null,

    /// This action sets the `CurrentPeriod` property's values to 0.
    ///
    /// This action shall set the `CurrentPeriod` property's values to 0.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn clearCurrentPeriod(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: ProcessorMetricsClearCurrentPeriodAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#ProcessorMetrics.ClearCurrentPeriod" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }
};

/// The C-state residency of the processor.
///
/// This type shall contain properties that describe the C-state residency of the processor or core.
pub const CstateResidency = struct {
    /// The C-state level, such as C0, C1, or C2.
    ///
    /// This property shall contain the C-state level, such as C0, C1, or C2.  When this resource is subordinate to the `ProcessorSummary` object, this property is not applicable.
    Level: ?[]const u8 = null,
    /// The percentage of time that the processor or core has spent in this particular level of C-state.
    ///
    /// This property shall contain the percentage of time, `0` to `100`, that the processor or core has spent in this particular level of C-state.  When this resource is subordinate to the `ProcessorSummary` object, this property is not applicable.
    ResidencyPercent: ?core.Decimal = null,
};

/// The processor core metrics.
///
/// This type shall contain properties that describe cache metrics of a processor or core.
pub const CacheMetrics = struct {
    /// The cache level.
    ///
    /// This property shall contain the level of the cache in the processor or core.
    Level: ?[]const u8 = null,
    /// The number of cache line misses in millions.
    ///
    /// This property shall contain the number of cache line misses of the processor or core in millions.
    CacheMiss: ?core.Decimal = null,
    /// The cache line hit ratio.
    ///
    /// This property shall contain the cache hit ratio of the processor or core.
    HitRatio: ?core.Decimal = null,
    /// The number of cache misses per instruction.
    ///
    /// This property shall contain the number of cache misses per instruction of the processor or core.
    CacheMissesPerInstruction: ?core.Decimal = null,
    /// The total cache level occupancy in bytes.
    ///
    /// This property shall contain the total cache occupancy of the processor or core in bytes.
    OccupancyBytes: ?i64 = null,
    /// The total cache occupancy percentage.
    ///
    /// This property shall contain the total cache occupancy percentage, `0` to `100`, of the processor or core.
    OccupancyPercent: ?core.Decimal = null,
};

/// The total cache metrics for a processor.
///
/// This property shall contain properties that describe the metrics for all of the cache memory for a processor.
pub const CacheMetricsTotal = struct {
    /// The cache metrics since the last reset or `ClearCurrentPeriod` action for this processor.
    ///
    /// This property shall contain properties that describe the metrics for the current period of cache memory for this processor.
    CurrentPeriod: ?CurrentPeriod = null,
    /// The cache metrics for the lifetime of this processor.
    ///
    /// This property shall contain properties that describe the metrics for the lifetime of the cache memory for this processor.
    LifeTime: ?LifeTime = null,
};

pub const CoreMetrics = struct {
    /// The processor core identifier.
    ///
    /// This property shall contain the identifier of the core within the processor.
    CoreId: ?[]const u8 = null,
    /// The number of instructions per clock cycle of this core.
    ///
    /// This property shall contain the number of instructions per clock cycle of this core in the processor.
    InstructionsPerCycle: ?core.Decimal = null,
    /// The unhalted cycles count of this core.
    ///
    /// This property shall contain the number of unhalted cycles of this core in the processor.
    UnhaltedCycles: ?core.Decimal = null,
    /// The number of stalled cycles due to memory operations.
    ///
    /// This property shall contain the number of stalled cycles due to memory operations of this core in the processor.
    MemoryStallCount: ?core.Decimal = null,
    /// The number of stalled cycles due to I/O operations.
    ///
    /// This property shall contain the number of stalled cycles due to I/O operations of this core in the processor.
    IOStallCount: ?core.Decimal = null,
    /// The cache metrics of this core in the processor.
    ///
    /// This property shall contain properties that describe the cache metrics of this core in the processor.
    CoreCache: ?[]const CacheMetrics = null,
    /// The C-state residency of this core in the processor.
    ///
    /// This property shall contain properties that describe the C-state residency of this core in the processor.
    CStateResidency: ?[]const CstateResidency = null,
    /// The number of correctable core errors.
    ///
    /// This property shall contain the number of correctable core errors, such as TLB or cache errors.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `CorrectableCoreErrorCount` over all processors.
    CorrectableCoreErrorCount: ?i64 = null,
    /// The number of uncorrectable core errors.
    ///
    /// This property shall contain the number of uncorrectable core errors, such as TLB or cache errors.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `UncorrectableCoreErrorCount` over all processors.
    UncorrectableCoreErrorCount: ?i64 = null,
    /// The number of correctable errors of all other components.
    ///
    /// This property shall contain the number of correctable errors of all other components.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `CorrectableOtherErrorCount` over all processors.
    CorrectableOtherErrorCount: ?i64 = null,
    /// The number of uncorrectable errors of all other components.
    ///
    /// This property shall contain the number of uncorrectable errors of all other components.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `UncorrectableOtherErrorCount` over all processors.
    UncorrectableOtherErrorCount: ?i64 = null,
};

/// The cache memory metrics since the last system reset or `ClearCurrentPeriod` action for a processor.
///
/// This type shall describe the cache memory metrics since last system reset or `ClearCurrentPeriod` action for a processor.
pub const CurrentPeriod = struct {
    /// The number of correctable errors of cache memory since reset or `ClearCurrentPeriod` action for this processor.
    ///
    /// This property shall contain the number of correctable errors of cache memory since reset or `ClearCurrentPeriod` action for this processor.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `CorrectableECCErrorCount` over all processors.
    CorrectableECCErrorCount: ?i64 = null,
    /// The number of uncorrectable errors of cache memory since reset or `ClearCurrentPeriod` action for this processor.
    ///
    /// This property shall contain the number of uncorrectable errors of cache memory since reset or `ClearCurrentPeriod` action for this processor.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `UncorrectableECCErrorCount` over all processors.
    UncorrectableECCErrorCount: ?i64 = null,
};

/// The cache memory metrics for the lifetime for a processor.
///
/// This type shall describe the cache memory metrics since manufacturing for a processor.
pub const LifeTime = struct {
    /// The number of correctable errors for the lifetime of the cache memory.
    ///
    /// This property shall contain the number of correctable errors for the lifetime of the cache memory.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `CorrectableECCErrorCount` over all processors.
    CorrectableECCErrorCount: ?i64 = null,
    /// The number of uncorrectable errors for the lifetime of the cache memory.
    ///
    /// This property shall contain the number of uncorrectable errors for the lifetime of the cache memory.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `UncorrectableECCErrorCount` over all processors.
    UncorrectableECCErrorCount: ?i64 = null,
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The `ProcessorMetrics` schema contains usage and health statistics for a processor.
///
/// This resource contains the processor metrics for a single processor in a Redfish implementation.
pub const ProcessorMetrics = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The pending settings for this resource. PATCH `SettingsObject` rather than the resource itself; the service applies the result on the schedule this names.
    @"@Redfish.Settings": ?settings.Settings = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: ?resource.Id = null,
    Description: ?resource.Description = null,
    Name: ?resource.Name = null,
    /// The bandwidth usage of this processor as a percentage.
    ///
    /// This property shall contain the bandwidth usage of the processor as a percentage, typically `0` to `100`.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the CPU utilization over all processors as a percentage.
    BandwidthPercent: ?core.Decimal = null,
    /// The average frequency of the processor.
    ///
    /// This property shall contain average frequency in MHz, across all enabled cores in the processor.  When this resource is subordinate to the `ProcessorSummary` object, this property is not applicable.
    ///
    /// Deprecated in v1_1_0.
    /// This property has been deprecated in favor of the `OperatingSpeedMHz` property.
    AverageFrequencyMHz: ?core.Decimal = null,
    /// The CPU margin to throttle (temperature offset in degree Celsius units).
    ///
    /// This property shall contain the CPU margin to throttle based on an offset between the maximum temperature in which the processor can operate, and the processor's current temperature.  When this resource is subordinate to the `ProcessorSummary` object, this property is not applicable.
    ThrottlingCelsius: ?core.Decimal = null,
    /// The temperature of the processor.
    ///
    /// This property shall contain the temperature, in degree Celsius units, of the processor.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the average temperature, in Celsius, over all processors.
    ///
    /// Deprecated in v1_2_0.
    /// This property has been deprecated in favor of the properties in `EnvironmentMetrics`.
    TemperatureCelsius: ?core.Decimal = null,
    /// The power, in watt units, that the processor has consumed.
    ///
    /// This property shall contain the power, in watt units, that the processor has consumed.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of power, in watt units, that all processors have consumed.
    ///
    /// Deprecated in v1_2_0.
    /// This property has been deprecated in favor of the properties in `EnvironmentMetrics`.
    ConsumedPowerWatt: ?core.Decimal = null,
    /// The frequency relative to the nominal processor frequency ratio.
    ///
    /// This property shall contain the frequency relative to the nominal processor frequency ratio of this processor.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the average FrequencyRatio over all processors.
    FrequencyRatio: ?core.Decimal = null,
    /// The processor cache metrics.
    ///
    /// This property shall contain properties that describe this processor's cache.  When this resource is subordinate to the `ProcessorSummary` object, this property is not applicable.
    Cache: ?[]const CacheMetrics = null,
    /// The local memory bandwidth usage in bytes.
    ///
    /// This property shall contain the local memory bandwidth usage of this processor in bytes.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of LocalMemoryBandwidthBytes over all processors.
    LocalMemoryBandwidthBytes: ?i64 = null,
    /// The remote memory bandwidth usage in bytes.
    ///
    /// This property shall contain the remote memory bandwidth usage of this processor in bytes.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of RemoteMemoryBandwidthBytes over all processors.
    RemoteMemoryBandwidthBytes: ?i64 = null,
    /// The percentage of time spent in kernel mode.
    ///
    /// This property shall contain total percentage of time, `0` to `100`, the processor has spent in kernel mode.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the average KernelPercent over all processors.
    KernelPercent: ?core.Decimal = null,
    /// The percentage of time spent in user mode.
    ///
    /// This property shall contain total percentage of time, `0` to `100`, the processor has spent in user mode.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the average UserPercent over all processors.
    UserPercent: ?core.Decimal = null,
    /// The processor core metrics.
    ///
    /// This property shall contain properties that describe the cores of this processor.  When this resource is subordinate to the `ProcessorSummary` object, this property is not applicable.
    CoreMetrics: ?[]const CoreMetrics = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// Operating speed of the processor in MHz.
    ///
    /// This property shall contain the operating speed of the processor in MHz.  The operating speed of the processor may change more frequently than the manager is able to monitor.
    OperatingSpeedMHz: ?i64 = null,
    /// The total cache metrics for this processor.
    ///
    /// This property shall contain properties that describe the metrics for all of the cache memory of this processor.
    CacheMetricsTotal: ?CacheMetricsTotal = null,
    /// The PCIe errors associated with this processor.
    ///
    /// This property shall contain the PCIe errors associated with this processor.
    PCIeErrors: ?pcie_device.PcieErrors = null,
    /// The number of correctable core errors.
    ///
    /// This property shall contain the number of correctable core errors, such as TLB or cache errors.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `CorrectableCoreErrorCount` over all processors.
    CorrectableCoreErrorCount: ?i64 = null,
    /// The number of uncorrectable core errors.
    ///
    /// This property shall contain the number of uncorrectable core errors, such as TLB or cache errors.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `UncorrectableCoreErrorCount` over all processors.
    UncorrectableCoreErrorCount: ?i64 = null,
    /// The number of correctable errors of all other components.
    ///
    /// This property shall contain the number of correctable errors of all other components.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `CorrectableOtherErrorCount` over all processors.
    CorrectableOtherErrorCount: ?i64 = null,
    /// The number of uncorrectable errors of all other components.
    ///
    /// This property shall contain the number of uncorrectable errors of all other components.  When this resource is subordinate to the `ProcessorSummary` object, this property shall be the sum of `UncorrectableOtherErrorCount` over all processors.
    UncorrectableOtherErrorCount: ?i64 = null,
    /// The total duration of throttling caused by a power limit of the processor since reset.
    ///
    /// This property shall contain the total duration of throttling caused by a power limit of the processor since reset.
    PowerLimitThrottleDuration: ?core.Duration = null,
    /// The total duration of throttling caused by a thermal limit of the processor since reset.
    ///
    /// This property shall contain the total duration of throttling caused by a thermal limit of the processor since reset.
    ThermalLimitThrottleDuration: ?core.Duration = null,
    /// The date and time when the processor started accumulating data for the `LifeTime` property.
    ///
    /// This property shall contain the date and time when the processor started accumulating data for the `LifeTime` property.  This might contain the same value as the production date of the processor.
    LifetimeStartDateTime: ?core.DateTimeOffset = null,
    /// The core voltage (V) of this processor.
    ///
    /// The value of this property shall contain the core voltage, in volt units, of this processor.  The core voltage of the processor may change more frequently than the manager is able to monitor.  The value of the `DataSourceUri` property, if present, shall reference a resource of type `Sensor` with the `ReadingType` property containing the value `Voltage`.
    CoreVoltage: ?sensor.SensorExcerptVoltage = null,

    const closed = core.ClosedStruct(@This());
    pub const jsonParse = closed.jsonParse;
    pub const jsonParseFromValue = closed.jsonParseFromValue;
};

test {
    std.testing.refAllDecls(@This());
}
