//! Namespace `ResolutionStep`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const action_info = @import("action_info.zig");
const resource = @import("resource.zig");

pub const ResolutionType = enum {
    /// Contact vendor for service.
    ContactVendor,
    /// Replace a component.
    ReplaceComponent,
    /// Perform a firmware update operation.
    FirmwareUpdate,
    /// Perform a reset operation.
    Reset,
    /// Perform a power cycle operation.
    PowerCycle,
    /// Reset the settings to factory defaults.
    ResetToDefaults,
    /// Collect diagnostic data.
    CollectDiagnosticData,
    /// Perform an OEM-defined resolution step.
    OEM,
    /// Retry the requested operation.
    RetryOperation,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const ResolutionStep = struct {
    /// The type of the resolution step.
    ///
    /// This property shall contain the type of the resolution step.
    ResolutionType: ?ResolutionType = null,
    /// The priority in the set of resolution steps.
    ///
    /// This property shall contain the priority in the set of resolution steps.  The value `0` shall indicate the highest priority.  Increasing values shall represent decreasing priority.  If two or more resolution steps have the same priority, the execution order of the resolution steps shall be in array order.  If a resolution step does not have a priority assignment, the default is 0.  The priority is used to determine the execution order of the resolution steps.
    Priority: ?i64 = null,
    /// The action URI for a resolution step.
    ///
    /// This property shall contain the action URI for a resolution step.
    ActionURI: ?[]const u8 = null,
    /// The parameters of the action URI for a resolution step.
    ///
    /// This property shall contain the parameters of the action URI for a resolution step.
    ActionParameters: ?[]const action_info.Parameters = null,
    /// The target URI of the component for a resolution step.
    ///
    /// This property shall contain the target URI of the component for a resolution step.  This property shall be present if the `ActionURI` property is not supported.
    TargetComponentURI: ?[]const u8 = null,
    /// The interval between retries for a resolution step.
    ///
    /// This property shall contain the interval, in seconds, between the retries for a resolution step.
    RetryIntervalSeconds: ?i64 = null,
    /// The number of retries for a resolution step.
    ///
    /// This property shall contain the number of the retries for a resolution step.
    RetryCount: ?i64 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
};

/// What a client may change of `ResolutionStep.ResolutionStep`.
pub const ResolutionStepUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties contained in this object shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
