//! Namespace `SecureBoot`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const resource = @import("resource.zig");
const secure_boot_database_collection = @import("secure_boot_database_collection.zig");

pub const ResetKeysType = enum {
    /// Reset the contents of all UEFI Secure Boot key databases, including the PK key database, to the default values.
    ResetAllKeysToDefault,
    /// Delete the contents of all UEFI Secure Boot key databases, including the PK key database.  This puts the system in Setup Mode.
    DeleteAllKeys,
    /// Delete the contents of the PK UEFI Secure Boot database.  This puts the system in Setup Mode.
    DeletePK,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const SecureBootCurrentBootType = enum {
    /// UEFI Secure Boot is currently enabled.
    Enabled,
    /// UEFI Secure Boot is currently disabled.
    Disabled,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const SecureBootModeType = enum {
    /// UEFI Secure Boot is currently in Setup Mode.
    SetupMode,
    /// UEFI Secure Boot is currently in User Mode.
    UserMode,
    /// UEFI Secure Boot is currently in Audit Mode.
    AuditMode,
    /// UEFI Secure Boot is currently in Deployed Mode.
    DeployedMode,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// Arguments to `SecureBoot.ResetKeys`.
///
/// This action resets the UEFI Secure Boot keys.
pub const SecureBootResetKeysAction = struct {
    /// The type of reset or delete to perform on the UEFI Secure Boot databases.
    ///
    /// This parameter shall specify the type of reset or delete to perform on the UEFI Secure Boot databases.
    ResetKeysType: ?ResetKeysType = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
    /// This action resets the UEFI Secure Boot keys.
    ///
    /// This action shall reset the UEFI Secure Boot key databases.  The `ResetAllKeysToDefault` value shall reset all UEFI Secure Boot key databases to their default values.  The `DeleteAllKeys` value shall delete the contents of all UEFI Secure Boot key databases.  The `DeletePK` value shall delete the contents of the PK Secure Boot key database.
    @"#SecureBoot.ResetKeys": ?core.Action(SecureBootResetKeysAction, std.json.Value) = null,

    /// This action resets the UEFI Secure Boot keys.
    ///
    /// This action shall reset the UEFI Secure Boot key databases.  The `ResetAllKeysToDefault` value shall reset all UEFI Secure Boot key databases to their default values.  The `DeleteAllKeys` value shall delete the contents of all UEFI Secure Boot key databases.  The `DeletePK` value shall delete the contents of the PK Secure Boot key database.
    ///
    /// Returns `error.ActionNotSupported` if the service did not
    /// advertise this action on the resource.
    pub fn resetKeys(
        self: @This(),
        gpa: std.mem.Allocator,
        transport: *core.BmcTransport,
        params: SecureBootResetKeysAction,
    ) !core.Owned(core.ModificationResponse(std.json.Value)) {
        const target = self.@"#SecureBoot.ResetKeys" orelse return error.ActionNotSupported;
        return core.bmc.invokeAction(gpa, transport, target, params);
    }
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The `SecureBoot` schema contains UEFI Secure Boot information and represents properties for managing the UEFI Secure Boot functionality of a system.
///
/// This resource contains UEFI Secure Boot information for a Redfish implementation.
pub const SecureBoot = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: ?resource.Id = null,
    Description: ?resource.Description = null,
    Name: ?resource.Name = null,
    /// An indication of whether UEFI Secure Boot is enabled.
    ///
    /// This property shall indicate whether the UEFI Secure Boot takes effect on next boot.  This property can be enabled in UEFI boot mode only.
    SecureBootEnable: ?bool = null,
    /// The UEFI Secure Boot state during the current boot cycle.
    ///
    /// This property shall indicate the UEFI Secure Boot state during the current boot cycle.
    SecureBootCurrentBoot: ?SecureBootCurrentBootType = null,
    /// The current UEFI Secure Boot Mode.
    ///
    /// This property shall contain the current UEFI Secure Boot mode, as defined in the UEFI Specification.
    SecureBootMode: ?SecureBootModeType = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// The desired UEFI Secure Boot Mode for the next boot.
    ///
    /// This property shall contain the desired UEFI Secure Boot mode, as defined in the UEFI Specification, to be applied on the next boot.
    SecureBootDesiredMode: ?SecureBootModeType = null,
    /// A link to the collection of UEFI Secure Boot databases.
    ///
    /// The value of this property shall be a link to a resource collection of type `SecureBootDatabaseCollection`.
    SecureBootDatabases: ?core.NavProperty(secure_boot_database_collection.SecureBootDatabaseCollection) = null,
};

/// What a client may change of `SecureBoot.SecureBoot`.
///
/// The `SecureBoot` schema contains UEFI Secure Boot information and represents properties for managing the UEFI Secure Boot functionality of a system.
pub const SecureBootUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// An indication of whether UEFI Secure Boot is enabled.
    ///
    /// This property shall indicate whether the UEFI Secure Boot takes effect on next boot.  This property can be enabled in UEFI boot mode only.
    SecureBootEnable: core.Nullable(bool) = .absent,
    /// The desired UEFI Secure Boot Mode for the next boot.
    ///
    /// This property shall contain the desired UEFI Secure Boot mode, as defined in the UEFI Specification, to be applied on the next boot.
    SecureBootDesiredMode: core.Nullable(SecureBootModeType) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
