//! Namespace `Settings`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const message = @import("message.zig");
const resource = @import("resource.zig");

pub const ApplyTime = enum {
    /// Apply immediately.  This value might result in an immediate host reset, manager reset, or other side effects.
    ///
    /// This value shall indicate the values within the settings resource are applied immediately.  This value may result in an immediate host reset, manager reset, or other side effects.
    Immediate,
    /// Apply on a reset.
    ///
    /// This value shall indicate the values within settings resource are applied when the system or service is reset.
    OnReset,
    /// Apply during a maintenance window as specified by an administrator.
    ///
    /// This value shall indicate the values within the settings resource are applied during the maintenance window specified by the `MaintenanceWindowStartTime` and `MaintenanceWindowDurationInSeconds` properties.  A service can perform resets during this maintenance window.
    AtMaintenanceWindowStart,
    /// Apply after a reset but within maintenance window as specified by an administrator.
    ///
    /// This value shall indicate the values within the settings resource are applied during the maintenance window specified by the `MaintenanceWindowStartTime` and `MaintenanceWindowDurationInSeconds` properties, and if a reset occurs within the maintenance window.
    InMaintenanceWindowOnReset,
    /// The requested settings are not applied until the user sets the `ApplyTime` property to a different value.
    ///
    /// This value shall indicate the values within the settings resource are not applied until the user sets the `ApplyTime` property to a different value.
    Deferred,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

/// The preferred time to apply configuration settings.
///
/// This type shall be specified by client to indicate the preferred time to apply the configuration settings.
pub const PreferredApplyTime = struct {
    /// The time when to apply the settings.
    ///
    /// This property shall indicate when to apply the values in this settings resource.
    ApplyTime: ?ApplyTime = null,
    /// The start time of a maintenance window.
    ///
    /// This property shall indicate the date and time when the service can start to apply the future configuration as part of a maintenance window.  Services shall provide a default value if not configured by a user.  This property shall be required if the `ApplyTime` property is `AtMaintenanceWindowStart` or `InMaintenanceWindowOnReset`.
    MaintenanceWindowStartTime: ?core.DateTimeOffset = null,
    /// The expiry time of maintenance window in seconds.
    ///
    /// This property shall indicate the end of the maintenance window as the number of seconds after the time specified by the `MaintenanceWindowStartTime` property.  This property shall be required if the `ApplyTime` property is `AtMaintenanceWindowStart` or `InMaintenanceWindowOnReset`.
    MaintenanceWindowDurationInSeconds: ?i64 = null,

    const closed = core.ClosedStruct(@This());
    pub const jsonParse = closed.jsonParse;
    pub const jsonParseFromValue = closed.jsonParseFromValue;
};

/// What a client may change of `Settings.PreferredApplyTime`.
///
/// The preferred time to apply configuration settings.
pub const PreferredApplyTimeUpdate = struct {
    /// The time when to apply the settings.
    ///
    /// This property shall indicate when to apply the values in this settings resource.
    ApplyTime: ?ApplyTime = null,
    /// The start time of a maintenance window.
    ///
    /// This property shall indicate the date and time when the service can start to apply the future configuration as part of a maintenance window.  Services shall provide a default value if not configured by a user.  This property shall be required if the `ApplyTime` property is `AtMaintenanceWindowStart` or `InMaintenanceWindowOnReset`.
    MaintenanceWindowStartTime: ?core.DateTimeOffset = null,
    /// The expiry time of maintenance window in seconds.
    ///
    /// This property shall indicate the end of the maintenance window as the number of seconds after the time specified by the `MaintenanceWindowStartTime` property.  This property shall be required if the `ApplyTime` property is `AtMaintenanceWindowStart` or `InMaintenanceWindowOnReset`.
    MaintenanceWindowDurationInSeconds: ?i64 = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

pub const Settings = struct {
    /// The time when the settings were applied.
    ///
    /// This property shall indicate the time when the settings were applied to the resource.
    Time: ?core.DateTimeOffset = null,
    /// The entity tag (ETag) of the resource to which the settings were applied, after the application.
    ///
    /// This property shall contain the entity tag (ETag) of the resource to which the settings were applied, after the application.  The client can check this value against the ETag of this resource to determine whether the resource had other changes.
    ETag: ?[]const u8 = null,
    /// An array of messages associated with the settings.
    ///
    /// This property shall contain an array of messages associated with the settings.
    Messages: ?[]const message.Message = null,
    /// The time when the settings can be applied.
    ///
    /// This property shall contain the supported apply time values a client is allowed to request when configuring the settings apply time.  Services that do not support clients configuring the apply time can support this property with a single array member in order to inform the client when the settings will be applied.
    SupportedApplyTimes: ?[]const ApplyTime = null,
    /// The link to the resource that the client can `PUT` or `PATCH` to modify the resource.
    ///
    /// This property shall contain the URI of the resource that the client can `PUT` or `PATCH` to modify the resource.
    SettingsObject: ?core.NavProperty(resource.Item) = null,
    /// The location of the maintenance window settings.
    ///
    /// This property shall contain a link to a resource that contains the `@Redfish.MaintenanceWindow` property that governs this resource.  This property should be supported if the `SupportedApplyTimes` property contains `AtMaintenanceWindowStart` or `InMaintenanceWindowOnReset`.
    MaintenanceWindowResource: ?core.NavProperty(resource.ItemOrCollection) = null,

    const closed = core.ClosedStruct(@This());
    pub const jsonParse = closed.jsonParse;
    pub const jsonParseFromValue = closed.jsonParseFromValue;
};

/// What a client may change of `Settings.Settings`.
pub const SettingsUpdate = struct {
    /// An array of messages associated with the settings.
    ///
    /// This property shall contain an array of messages associated with the settings.
    Messages: ?[]const message.MessageUpdate = null,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
