//! Namespace `ThermalEquipment`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const cooling_loop_collection = @import("cooling_loop_collection.zig");
const cooling_unit_collection = @import("cooling_unit_collection.zig");
const redundancy = @import("redundancy.zig");
const resource = @import("resource.zig");

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

/// The `ThermalEquipment` schema represents the set of cooling equipment managed by a Redfish service.
///
/// This resource shall represent the set of cooling equipment for a Redfish implementation.
pub const ThermalEquipment = struct {
    /// Where the resource lives.
    @"@odata.id": core.ODataId,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: resource.Id,
    Description: ?resource.Description = null,
    Name: resource.Name,
    /// The status and health of the resource and its subordinate or dependent resources.
    ///
    /// This property shall contain any status or health properties of the resource.
    Status: ?resource.Status = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// The redundancy information for cooling loops attached to this equipment.
    ///
    /// This property shall contain redundancy information for the set of cooling loops attached to this equipment.  The values of the `RedundancyGroup` array shall reference resources of type `CoolingLoop`.
    CoolingLoopRedundancy: ?[]const redundancy.RedundantGroup = null,
    /// A link to a collection of heat exchanger units.
    ///
    /// This property shall contain a link to a resource collection of type `CoolingUnitCollection` that contains a set of heat exchanger units.
    HeatExchangers: ?core.NavProperty(cooling_unit_collection.CoolingUnitCollection) = null,
    /// A link to a collection of coolant distribution units.
    ///
    /// This property shall contain a link to a resource collection of type `CoolingUnitCollection` that contains a set of coolant distribution units.
    CDUs: ?core.NavProperty(cooling_unit_collection.CoolingUnitCollection) = null,
    /// A link to a collection of immersion cooling units.
    ///
    /// This property shall contain a link to a resource collection of type `CoolingUnitCollection` that contains a set of immersion cooling units.
    ImmersionUnits: ?core.NavProperty(cooling_unit_collection.CoolingUnitCollection) = null,
    /// A link to a collection of cooling loops.
    ///
    /// This property shall contain a link to a resource collection of type `CoolingLoopCollection` that contains the set of cooling loops managed by the service.
    CoolingLoops: ?core.NavProperty(cooling_loop_collection.CoolingLoopCollection) = null,
    /// A link to a collection of reservoir and pumping units (RPUs).
    ///
    /// This property shall contain a link to a resource collection of type `CoolingUnitCollection` that contains a set of reservoir and pumping units.
    RPUs: ?core.NavProperty(cooling_unit_collection.CoolingUnitCollection) = null,
};

test {
    std.testing.refAllDecls(@This());
}
