//! Namespace `VLanNetworkInterface`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_std`.

const std = @import("std");

const core = @import("redfish_core");
const resource = @import("resource.zig");

pub const Vlanid = i64;

pub const VlanPriority = i64;

/// The available actions for this resource.
///
/// This type shall contain the available actions for this resource.
pub const Actions = struct {
    /// The available OEM-specific actions for this resource.
    ///
    /// This property shall contain the available OEM-specific actions for this resource.
    Oem: ?OemActions = null,
};

/// The available OEM-specific actions for this resource.
///
/// This type shall contain the available OEM-specific actions for this resource.
pub const OemActions = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

pub const Vlan = struct {
    /// An indication of whether this VLAN is enabled for this VLAN network interface.
    ///
    /// This property shall indicate whether this VLAN is enabled for this VLAN network interface.
    VLANEnable: ?bool = null,
    /// The ID for this VLAN.
    ///
    /// This property shall contain the ID for this VLAN.
    VLANId: ?Vlanid = null,
    /// The priority for this VLAN.
    ///
    /// This property shall contain the priority for this VLAN.
    VLANPriority: ?VlanPriority = null,
    /// An indication of whether this VLAN is tagged or untagged for this interface.
    ///
    /// This property shall indicate whether this VLAN is tagged or untagged for this interface.
    Tagged: ?bool = null,
};

/// What a client may change of `VLanNetworkInterface.VLAN`.
pub const VlanUpdate = struct {
    /// An indication of whether this VLAN is enabled for this VLAN network interface.
    ///
    /// This property shall indicate whether this VLAN is enabled for this VLAN network interface.
    VLANEnable: core.Nullable(bool) = .absent,
    /// The ID for this VLAN.
    ///
    /// This property shall contain the ID for this VLAN.
    VLANId: core.Nullable(Vlanid) = .absent,
    /// The priority for this VLAN.
    ///
    /// This property shall contain the priority for this VLAN.
    VLANPriority: core.Nullable(VlanPriority) = .absent,
    /// An indication of whether this VLAN is tagged or untagged for this interface.
    ///
    /// This property shall indicate whether this VLAN is tagged or untagged for this interface.
    Tagged: core.Nullable(bool) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// The `VLanNetworkInterface` schema describes a VLAN network instance that is available on a manager, system, or other device.
///
/// This resource contains information for a VLAN network instance that is available on a manager, system, or other device for a Redfish implementation.
///
/// Deprecated in v1_3_0.
/// This schema has been deprecated in favor of using individual `EthernetInterface` resources to show VLAN information.
pub const VlanNetworkInterface = struct {
    /// Where the resource lives.
    @"@odata.id": core.ODataId,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.Oem = null,
    Id: resource.Id,
    Description: ?resource.Description = null,
    Name: resource.Name,
    /// An indication of whether this VLAN is enabled for this interface.
    ///
    /// This property shall indicate whether this VLAN is enabled for this interface.
    VLANEnable: ?bool = null,
    /// The ID for this VLAN.
    ///
    /// This property shall contain the ID for this VLAN.
    VLANId: ?Vlanid = null,
    /// The available actions for this resource.
    ///
    /// This property shall contain the available actions for this resource.
    Actions: ?Actions = null,
    /// The priority for this VLAN.
    ///
    /// This property shall contain the priority for this VLAN.
    VLANPriority: ?VlanPriority = null,
};

/// What a client may change of `VLanNetworkInterface.VLanNetworkInterface`.
///
/// The `VLanNetworkInterface` schema describes a VLAN network instance that is available on a manager, system, or other device.
///
/// Deprecated in v1_3_0.
/// This schema has been deprecated in favor of using individual `EthernetInterface` resources to show VLAN information.
pub const VlanNetworkInterfaceUpdate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// An indication of whether this VLAN is enabled for this interface.
    ///
    /// This property shall indicate whether this VLAN is enabled for this interface.
    VLANEnable: core.Nullable(bool) = .absent,
    /// The ID for this VLAN.
    ///
    /// This property shall contain the ID for this VLAN.
    VLANId: core.Nullable(Vlanid) = .absent,
    /// The priority for this VLAN.
    ///
    /// This property shall contain the priority for this VLAN.
    VLANPriority: core.Nullable(VlanPriority) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

/// What a client may supply when creating an instance of `VLanNetworkInterface.VLanNetworkInterface`.
///
/// The `VLanNetworkInterface` schema describes a VLAN network instance that is available on a manager, system, or other device.
///
/// Deprecated in v1_3_0.
/// This schema has been deprecated in favor of using individual `EthernetInterface` resources to show VLAN information.
pub const VlanNetworkInterfaceCreate = struct {
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?resource.OemUpdate = null,
    /// An indication of whether this VLAN is enabled for this interface.
    ///
    /// This property shall indicate whether this VLAN is enabled for this interface.
    VLANEnable: bool,
    /// The ID for this VLAN.
    ///
    /// This property shall contain the ID for this VLAN.
    VLANId: Vlanid,
    /// The priority for this VLAN.
    ///
    /// This property shall contain the priority for this VLAN.
    VLANPriority: core.Nullable(VlanPriority) = .absent,

    pub const jsonStringify = core.Payload(@This()).jsonStringify;
};

test {
    std.testing.refAllDecls(@This());
}
