//! Namespace `DellAttributes`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_oem_dell`.

const std = @import("std");

const core = @import("redfish_core");
const base = @import("redfish_schema_std");

pub const Attributes = struct {
    /// Whatever the service sent that this schema version does not name.
    additional_properties: core.AdditionalProperties = .{},

    const open = core.OpenStruct(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
    pub const jsonStringify = open.jsonStringify;
};

pub const DellAttributes = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    /// The schema version the service implements.
    @"@odata.type": ?[]const u8 = null,
    /// The OEM extension property.
    ///
    /// This property shall contain the OEM extensions.  All values for properties that this object contains shall conform to the Redfish Specification-described requirements.
    Oem: ?base.resource.Oem = null,
    Id: ?base.resource.Id = null,
    Description: ?base.resource.Description = null,
    Name: ?base.resource.Name = null,
    Attributes: ?Attributes = null,
};

test {
    std.testing.refAllDecls(@This());
}
