//! Namespace `AmiManager`.
//!
//! Generated by `redfish-codegen`. DO NOT EDIT.
//!
//! Profile: `redfish_schema_oem_ami`.

const std = @import("std");

const core = @import("redfish_core");

pub const LockdownBiosSettingsChangeState = enum {
    Enable,
    Disable,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const LockdownBiosUpgradeDowngradeState = enum {
    Enable,
    Disable,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const LockoutBiosVariableWriteMode = enum {
    Enable,
    Disable,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const LockoutHostControlState = enum {
    Enable,
    Disable,

    /// A value this package's schema version does not name.
    UnsupportedValue,

    const open = core.OpenEnum(@This());
    pub const jsonParse = open.jsonParse;
    pub const jsonParseFromValue = open.jsonParseFromValue;
};

pub const ConfigBmc = struct {
    /// Where the resource lives.
    @"@odata.id": ?core.ODataId = null,
    /// The version of the resource this value was read at.
    @"@odata.etag": ?core.ODataETag = null,
    LockoutHostControl: ?LockoutHostControlState = null,
    LockoutBiosVariableWriteMode: ?LockoutBiosVariableWriteMode = null,
    LockdownBiosSettingsChange: ?LockdownBiosSettingsChangeState = null,
    LockdownBiosUpgradeDowngrade: ?LockdownBiosUpgradeDowngradeState = null,
};

test {
    std.testing.refAllDecls(@This());
}
